// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/network/dns_resolver/getaddrinfo/v3/getaddrinfo_dns_resolver.proto (package envoy.extensions.network.dns_resolver.getaddrinfo.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/extensions/network/dns_resolver/getaddrinfo/v3/getaddrinfo_dns_resolver.proto.
 */
export const file_envoy_extensions_network_dns_resolver_getaddrinfo_v3_getaddrinfo_dns_resolver = /*@__PURE__*/
  fileDesc("ClNlbnZveS9leHRlbnNpb25zL25ldHdvcmsvZG5zX3Jlc29sdmVyL2dldGFkZHJpbmZvL3YzL2dldGFkZHJpbmZvX2Ruc19yZXNvbHZlci5wcm90bxI0ZW52b3kuZXh0ZW5zaW9ucy5uZXR3b3JrLmRuc19yZXNvbHZlci5nZXRhZGRyaW5mby52MyKNAQocR2V0QWRkckluZm9EbnNSZXNvbHZlckNvbmZpZxIxCgtudW1fcmV0cmllcxgBIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5VSW50MzJWYWx1ZRI6ChRudW1fcmVzb2x2ZXJfdGhyZWFkcxgCIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5VSW50MzJWYWx1ZULWAQpCaW8uZW52b3lwcm94eS5lbnZveS5leHRlbnNpb25zLm5ldHdvcmsuZG5zX3Jlc29sdmVyLmdldGFkZHJpbmZvLnYzQhtHZXRhZGRyaW5mb0Ruc1Jlc29sdmVyUHJvdG9QAVppZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9uZXR3b3JrL2Ruc19yZXNvbHZlci9nZXRhZGRyaW5mby92MztnZXRhZGRyaW5mb3YzuoDI0QYCEAJiBnByb3RvMw", [file_google_protobuf_wrappers, file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.network.dns_resolver.getaddrinfo.v3.GetAddrInfoDnsResolverConfig.
 * Use `create(GetAddrInfoDnsResolverConfigSchema)` to create a new message.
 */
export const GetAddrInfoDnsResolverConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_network_dns_resolver_getaddrinfo_v3_getaddrinfo_dns_resolver, 0);

