// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/config/validators/minimum_clusters/v3/minimum_clusters.proto (package envoy.extensions.config.validators.minimum_clusters.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/extensions/config/validators/minimum_clusters/v3/minimum_clusters.proto.
 */
export declare const file_envoy_extensions_config_validators_minimum_clusters_v3_minimum_clusters: GenFile;

/**
 * Validates a CDS config, and ensures that the number of clusters is above the
 * set threshold.
 *
 * @generated from message envoy.extensions.config.validators.minimum_clusters.v3.MinimumClustersValidator
 */
export declare type MinimumClustersValidator = Message<"envoy.extensions.config.validators.minimum_clusters.v3.MinimumClustersValidator"> & {
  /**
   * The minimal clusters threshold. Any CDS config update leading to less than
   * this number will be rejected.
   * Default value is 0.
   *
   * @generated from field: uint32 min_clusters_num = 1;
   */
  minClustersNum: number;
};

/**
 * Describes the message envoy.extensions.config.validators.minimum_clusters.v3.MinimumClustersValidator.
 * Use `create(MinimumClustersValidatorSchema)` to create a new message.
 */
export declare const MinimumClustersValidatorSchema: GenMessage<MinimumClustersValidator>;

