// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/type/semantic_version.proto (package envoy.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/type/semantic_version.proto.
 */
export declare const file_envoy_type_semantic_version: GenFile;

/**
 * Envoy uses SemVer (https://semver.org/). Major/minor versions indicate
 * expected behaviors and APIs, the patch version field is used only
 * for security fixes and can be generally ignored.
 *
 * @generated from message envoy.type.SemanticVersion
 */
export declare type SemanticVersion = Message<"envoy.type.SemanticVersion"> & {
  /**
   * @generated from field: uint32 major_number = 1;
   */
  majorNumber: number;

  /**
   * @generated from field: uint32 minor_number = 2;
   */
  minorNumber: number;

  /**
   * @generated from field: uint32 patch = 3;
   */
  patch: number;
};

/**
 * Describes the message envoy.type.SemanticVersion.
 * Use `create(SemanticVersionSchema)` to create a new message.
 */
export declare const SemanticVersionSchema: GenMessage<SemanticVersion>;

