// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/filter/http/cors/v2/cors.proto (package envoy.config.filter.http.cors.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_migrate } from "../../../../../../udpa/annotations/migrate_pb";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/config/filter/http/cors/v2/cors.proto.
 */
export const file_envoy_config_filter_http_cors_v2_cors = /*@__PURE__*/
  fileDesc("CitlbnZveS9jb25maWcvZmlsdGVyL2h0dHAvY29ycy92Mi9jb3JzLnByb3RvEiBlbnZveS5jb25maWcuZmlsdGVyLmh0dHAuY29ycy52MiIGCgRDb3JzQsIBCi5pby5lbnZveXByb3h5LmVudm95LmNvbmZpZy5maWx0ZXIuaHR0cC5jb3JzLnYyQglDb3JzUHJvdG9QAVpOZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvY29uZmlnL2ZpbHRlci9odHRwL2NvcnMvdjI7Y29yc3Yy8pj+jwUnEiVlbnZveS5leHRlbnNpb25zLmZpbHRlcnMuaHR0cC5jb3JzLnYzuoDI0QYCEAFiBnByb3RvMw", [file_udpa_annotations_migrate, file_udpa_annotations_status]);

/**
 * Describes the message envoy.config.filter.http.cors.v2.Cors.
 * Use `create(CorsSchema)` to create a new message.
 */
export const CorsSchema = /*@__PURE__*/
  messageDesc(file_envoy_config_filter_http_cors_v2_cors, 0);

