// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/admin/v3/certs.proto (package envoy.admin.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../udpa/annotations/versioning_pb";

/**
 * Describes the file envoy/admin/v3/certs.proto.
 */
export const file_envoy_admin_v3_certs = /*@__PURE__*/
  fileDesc("ChplbnZveS9hZG1pbi92My9jZXJ0cy5wcm90bxIOZW52b3kuYWRtaW4udjMiagoMQ2VydGlmaWNhdGVzEjEKDGNlcnRpZmljYXRlcxgBIAMoCzIbLmVudm95LmFkbWluLnYzLkNlcnRpZmljYXRlOieaxYgeIgogZW52b3kuYWRtaW4udjJhbHBoYS5DZXJ0aWZpY2F0ZXMiogEKC0NlcnRpZmljYXRlEjMKB2NhX2NlcnQYASADKAsyIi5lbnZveS5hZG1pbi52My5DZXJ0aWZpY2F0ZURldGFpbHMSNgoKY2VydF9jaGFpbhgCIAMoCzIiLmVudm95LmFkbWluLnYzLkNlcnRpZmljYXRlRGV0YWlsczommsWIHiEKH2Vudm95LmFkbWluLnYyYWxwaGEuQ2VydGlmaWNhdGUi4gMKEkNlcnRpZmljYXRlRGV0YWlscxIMCgRwYXRoGAEgASgJEhUKDXNlcmlhbF9udW1iZXIYAiABKAkSPwoRc3ViamVjdF9hbHRfbmFtZXMYAyADKAsyJC5lbnZveS5hZG1pbi52My5TdWJqZWN0QWx0ZXJuYXRlTmFtZRIdChVkYXlzX3VudGlsX2V4cGlyYXRpb24YBCABKAQSLgoKdmFsaWRfZnJvbRgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMwoPZXhwaXJhdGlvbl90aW1lGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBJECgxvY3NwX2RldGFpbHMYByABKAsyLi5lbnZveS5hZG1pbi52My5DZXJ0aWZpY2F0ZURldGFpbHMuT2NzcERldGFpbHMabQoLT2NzcERldGFpbHMSLgoKdmFsaWRfZnJvbRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZXhwaXJhdGlvbhgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXA6LZrFiB4oCiZlbnZveS5hZG1pbi52MmFscGhhLkNlcnRpZmljYXRlRGV0YWlscyKDAQoUU3ViamVjdEFsdGVybmF0ZU5hbWUSDQoDZG5zGAEgASgJSAASDQoDdXJpGAIgASgJSAASFAoKaXBfYWRkcmVzcxgDIAEoCUgAOi+axYgeKgooZW52b3kuYWRtaW4udjJhbHBoYS5TdWJqZWN0QWx0ZXJuYXRlTmFtZUIGCgRuYW1lQnMKHGlvLmVudm95cHJveHkuZW52b3kuYWRtaW4udjNCCkNlcnRzUHJvdG9QAVo9Z2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvYWRtaW4vdjM7YWRtaW52M7qAyNEGAhACYgZwcm90bzM", [file_google_protobuf_timestamp, file_udpa_annotations_status, file_udpa_annotations_versioning]);

/**
 * Describes the message envoy.admin.v3.Certificates.
 * Use `create(CertificatesSchema)` to create a new message.
 */
export const CertificatesSchema = /*@__PURE__*/
  messageDesc(file_envoy_admin_v3_certs, 0);

/**
 * Describes the message envoy.admin.v3.Certificate.
 * Use `create(CertificateSchema)` to create a new message.
 */
export const CertificateSchema = /*@__PURE__*/
  messageDesc(file_envoy_admin_v3_certs, 1);

/**
 * Describes the message envoy.admin.v3.CertificateDetails.
 * Use `create(CertificateDetailsSchema)` to create a new message.
 */
export const CertificateDetailsSchema = /*@__PURE__*/
  messageDesc(file_envoy_admin_v3_certs, 2);

/**
 * Describes the message envoy.admin.v3.CertificateDetails.OcspDetails.
 * Use `create(CertificateDetails_OcspDetailsSchema)` to create a new message.
 */
export const CertificateDetails_OcspDetailsSchema = /*@__PURE__*/
  messageDesc(file_envoy_admin_v3_certs, 2, 0);

/**
 * Describes the message envoy.admin.v3.SubjectAlternateName.
 * Use `create(SubjectAlternateNameSchema)` to create a new message.
 */
export const SubjectAlternateNameSchema = /*@__PURE__*/
  messageDesc(file_envoy_admin_v3_certs, 3);

