// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/path/rewrite/uri_template/v3/uri_template_rewrite.proto (package envoy.extensions.path.rewrite.uri_template.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/path/rewrite/uri_template/v3/uri_template_rewrite.proto.
 */
export const file_envoy_extensions_path_rewrite_uri_template_v3_uri_template_rewrite = /*@__PURE__*/
  fileDesc("CkhlbnZveS9leHRlbnNpb25zL3BhdGgvcmV3cml0ZS91cmlfdGVtcGxhdGUvdjMvdXJpX3RlbXBsYXRlX3Jld3JpdGUucHJvdG8SLWVudm95LmV4dGVuc2lvbnMucGF0aC5yZXdyaXRlLnVyaV90ZW1wbGF0ZS52MyJFChhVcmlUZW1wbGF0ZVJld3JpdGVDb25maWcSKQoVcGF0aF90ZW1wbGF0ZV9yZXdyaXRlGAEgASgJQgr6QgdyBRABGIACQsUBCjtpby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMucGF0aC5yZXdyaXRlLnVyaV90ZW1wbGF0ZS52M0IXVXJpVGVtcGxhdGVSZXdyaXRlUHJvdG9QAVpjZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9wYXRoL3Jld3JpdGUvdXJpX3RlbXBsYXRlL3YzO3VyaV90ZW1wbGF0ZXYzuoDI0QYCEAJiBnByb3RvMw", [file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.extensions.path.rewrite.uri_template.v3.UriTemplateRewriteConfig.
 * Use `create(UriTemplateRewriteConfigSchema)` to create a new message.
 */
export const UriTemplateRewriteConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_path_rewrite_uri_template_v3_uri_template_rewrite, 0);

