// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/udp_packet_writer/v3/udp_gso_batch_writer_factory.proto (package envoy.extensions.udp_packet_writer.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/extensions/udp_packet_writer/v3/udp_gso_batch_writer_factory.proto.
 */
export declare const file_envoy_extensions_udp_packet_writer_v3_udp_gso_batch_writer_factory: GenFile;

/**
 * Configuration for the UDP GSO batch packet writer factory.
 *
 * @generated from message envoy.extensions.udp_packet_writer.v3.UdpGsoBatchWriterFactory
 */
export declare type UdpGsoBatchWriterFactory = Message<"envoy.extensions.udp_packet_writer.v3.UdpGsoBatchWriterFactory"> & {
};

/**
 * Describes the message envoy.extensions.udp_packet_writer.v3.UdpGsoBatchWriterFactory.
 * Use `create(UdpGsoBatchWriterFactorySchema)` to create a new message.
 */
export declare const UdpGsoBatchWriterFactorySchema: GenMessage<UdpGsoBatchWriterFactory>;

