// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/service/discovery/v3/ads.proto (package envoy.service.discovery.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_service_discovery_v3_discovery } from "./discovery_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../udpa/annotations/versioning_pb";

/**
 * Describes the file envoy/service/discovery/v3/ads.proto.
 */
export const file_envoy_service_discovery_v3_ads = /*@__PURE__*/
  fileDesc("CiRlbnZveS9zZXJ2aWNlL2Rpc2NvdmVyeS92My9hZHMucHJvdG8SGmVudm95LnNlcnZpY2UuZGlzY292ZXJ5LnYzIjYKCEFkc0R1bW15OiqaxYgeJQojZW52b3kuc2VydmljZS5kaXNjb3ZlcnkudjIuQWRzRHVtbXkypgIKGkFnZ3JlZ2F0ZWREaXNjb3ZlcnlTZXJ2aWNlEn4KGVN0cmVhbUFnZ3JlZ2F0ZWRSZXNvdXJjZXMSLC5lbnZveS5zZXJ2aWNlLmRpc2NvdmVyeS52My5EaXNjb3ZlcnlSZXF1ZXN0Gi0uZW52b3kuc2VydmljZS5kaXNjb3ZlcnkudjMuRGlzY292ZXJ5UmVzcG9uc2UiACgBMAEShwEKGERlbHRhQWdncmVnYXRlZFJlc291cmNlcxIxLmVudm95LnNlcnZpY2UuZGlzY292ZXJ5LnYzLkRlbHRhRGlzY292ZXJ5UmVxdWVzdBoyLmVudm95LnNlcnZpY2UuZGlzY292ZXJ5LnYzLkRlbHRhRGlzY292ZXJ5UmVzcG9uc2UiACgBMAFCjQEKKGlvLmVudm95cHJveHkuZW52b3kuc2VydmljZS5kaXNjb3ZlcnkudjNCCEFkc1Byb3RvUAFaTWdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L3NlcnZpY2UvZGlzY292ZXJ5L3YzO2Rpc2NvdmVyeXYzuoDI0QYCEAJiBnByb3RvMw", [file_envoy_service_discovery_v3_discovery, file_udpa_annotations_status, file_udpa_annotations_versioning]);

/**
 * Describes the message envoy.service.discovery.v3.AdsDummy.
 * Use `create(AdsDummySchema)` to create a new message.
 */
export const AdsDummySchema = /*@__PURE__*/
  messageDesc(file_envoy_service_discovery_v3_ads, 0);

/**
 * See https://github.com/envoyproxy/envoy-api#apis for a description of the role of
 * ADS and how it is intended to be used by a management server. ADS requests
 * have the same structure as their singleton xDS counterparts, but can
 * multiplex many resource types on a single stream. The type_url in the
 * DiscoveryRequest/DiscoveryResponse provides sufficient information to recover
 * the multiplexed singleton APIs at the Envoy instance and management server.
 *
 * @generated from service envoy.service.discovery.v3.AggregatedDiscoveryService
 */
export const AggregatedDiscoveryService = /*@__PURE__*/
  serviceDesc(file_envoy_service_discovery_v3_ads, 0);

