// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/transport_sockets/tap/v3/tap.proto (package envoy.extensions.transport_sockets.tap.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_config_core_v3_base } from "../../../../config/core/v3/base_pb";
import { file_envoy_extensions_common_tap_v3_common } from "../../../common/tap/v3/common_pb";
import { file_udpa_annotations_status } from "../../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../../udpa/annotations/versioning_pb";
import { file_validate_validate } from "../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/transport_sockets/tap/v3/tap.proto.
 */
export const file_envoy_extensions_transport_sockets_tap_v3_tap = /*@__PURE__*/
  fileDesc("CjNlbnZveS9leHRlbnNpb25zL3RyYW5zcG9ydF9zb2NrZXRzL3RhcC92My90YXAucHJvdG8SKWVudm95LmV4dGVuc2lvbnMudHJhbnNwb3J0X3NvY2tldHMudGFwLnYzIrUCCgNUYXASVgoNY29tbW9uX2NvbmZpZxgBIAEoCzI1LmVudm95LmV4dGVuc2lvbnMuY29tbW9uLnRhcC52My5Db21tb25FeHRlbnNpb25Db25maWdCCPpCBYoBAhABEkkKEHRyYW5zcG9ydF9zb2NrZXQYAiABKAsyJS5lbnZveS5jb25maWcuY29yZS52My5UcmFuc3BvcnRTb2NrZXRCCPpCBYoBAhABElUKEXNvY2tldF90YXBfY29uZmlnGAMgASgLMjouZW52b3kuZXh0ZW5zaW9ucy50cmFuc3BvcnRfc29ja2V0cy50YXAudjMuU29ja2V0VGFwQ29uZmlnOjSaxYgeLwotZW52b3kuY29uZmlnLnRyYW5zcG9ydF9zb2NrZXQudGFwLnYyYWxwaGEuVGFwIkkKD1NvY2tldFRhcENvbmZpZxIgChhzZXRfY29ubmVjdGlvbl9wZXJfZXZlbnQYASABKAgSFAoMc3RhdHNfcHJlZml4GAIgASgJQqUBCjdpby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMudHJhbnNwb3J0X3NvY2tldHMudGFwLnYzQghUYXBQcm90b1ABWlZnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9leHRlbnNpb25zL3RyYW5zcG9ydF9zb2NrZXRzL3RhcC92Mzt0YXB2M7qAyNEGAhACYgZwcm90bzM", [file_envoy_config_core_v3_base, file_envoy_extensions_common_tap_v3_common, file_udpa_annotations_status, file_udpa_annotations_versioning, file_validate_validate]);

/**
 * Describes the message envoy.extensions.transport_sockets.tap.v3.Tap.
 * Use `create(TapSchema)` to create a new message.
 */
export const TapSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_transport_sockets_tap_v3_tap, 0);

/**
 * Describes the message envoy.extensions.transport_sockets.tap.v3.SocketTapConfig.
 * Use `create(SocketTapConfigSchema)` to create a new message.
 */
export const SocketTapConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_transport_sockets_tap_v3_tap, 1);

