// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/transport_sockets/tcp_stats/v3/tcp_stats.proto (package envoy.extensions.transport_sockets.tcp_stats.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_config_core_v3_base } from "../../../../config/core/v3/base_pb";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/transport_sockets/tcp_stats/v3/tcp_stats.proto.
 */
export const file_envoy_extensions_transport_sockets_tcp_stats_v3_tcp_stats = /*@__PURE__*/
  fileDesc("Cj9lbnZveS9leHRlbnNpb25zL3RyYW5zcG9ydF9zb2NrZXRzL3RjcF9zdGF0cy92My90Y3Bfc3RhdHMucHJvdG8SL2Vudm95LmV4dGVuc2lvbnMudHJhbnNwb3J0X3NvY2tldHMudGNwX3N0YXRzLnYzIpMBCgZDb25maWcSSQoQdHJhbnNwb3J0X3NvY2tldBgBIAEoCzIlLmVudm95LmNvbmZpZy5jb3JlLnYzLlRyYW5zcG9ydFNvY2tldEII+kIFigECEAESPgoNdXBkYXRlX3BlcmlvZBgCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkIM+kIJqgEGMgQQwIQ9QrwBCj1pby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMudHJhbnNwb3J0X3NvY2tldHMudGNwX3N0YXRzLnYzQg1UY3BTdGF0c1Byb3RvUAFaYmdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2V4dGVuc2lvbnMvdHJhbnNwb3J0X3NvY2tldHMvdGNwX3N0YXRzL3YzO3RjcF9zdGF0c3YzuoDI0QYCEAJiBnByb3RvMw", [file_envoy_config_core_v3_base, file_google_protobuf_duration, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.extensions.transport_sockets.tcp_stats.v3.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export const ConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_transport_sockets_tcp_stats_v3_tcp_stats, 0);

