// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/type/matcher/v3/struct.proto (package envoy.type.matcher.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_type_matcher_v3_value } from "./value_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../udpa/annotations/versioning_pb";
import { file_validate_validate } from "../../../../validate/validate_pb";

/**
 * Describes the file envoy/type/matcher/v3/struct.proto.
 */
export const file_envoy_type_matcher_v3_struct = /*@__PURE__*/
  fileDesc("CiJlbnZveS90eXBlL21hdGNoZXIvdjMvc3RydWN0LnByb3RvEhVlbnZveS50eXBlLm1hdGNoZXIudjMirAIKDVN0cnVjdE1hdGNoZXISSAoEcGF0aBgCIAMoCzIwLmVudm95LnR5cGUubWF0Y2hlci52My5TdHJ1Y3RNYXRjaGVyLlBhdGhTZWdtZW50Qgj6QgWSAQIIARI8CgV2YWx1ZRgDIAEoCzIjLmVudm95LnR5cGUubWF0Y2hlci52My5WYWx1ZU1hdGNoZXJCCPpCBYoBAhABGmoKC1BhdGhTZWdtZW50EhYKA2tleRgBIAEoCUIH+kIEcgIQAUgAOjOaxYgeLgosZW52b3kudHlwZS5tYXRjaGVyLlN0cnVjdE1hdGNoZXIuUGF0aFNlZ21lbnRCDgoHc2VnbWVudBID+EIBOieaxYgeIgogZW52b3kudHlwZS5tYXRjaGVyLlN0cnVjdE1hdGNoZXJChAEKI2lvLmVudm95cHJveHkuZW52b3kudHlwZS5tYXRjaGVyLnYzQgtTdHJ1Y3RQcm90b1ABWkZnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS90eXBlL21hdGNoZXIvdjM7bWF0Y2hlcnYzuoDI0QYCEAJiBnByb3RvMw", [file_envoy_type_matcher_v3_value, file_udpa_annotations_status, file_udpa_annotations_versioning, file_validate_validate]);

/**
 * Describes the message envoy.type.matcher.v3.StructMatcher.
 * Use `create(StructMatcherSchema)` to create a new message.
 */
export const StructMatcherSchema = /*@__PURE__*/
  messageDesc(file_envoy_type_matcher_v3_struct, 0);

/**
 * Describes the message envoy.type.matcher.v3.StructMatcher.PathSegment.
 * Use `create(StructMatcher_PathSegmentSchema)` to create a new message.
 */
export const StructMatcher_PathSegmentSchema = /*@__PURE__*/
  messageDesc(file_envoy_type_matcher_v3_struct, 0, 0);

