// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/admin/v2alpha/clusters.proto (package envoy.admin.v2alpha, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Percent } from "../../type/percent_pb";
import type { Address } from "../../api/v2/core/address_pb";
import type { SimpleMetric } from "./metrics_pb";
import type { Locality } from "../../api/v2/core/base_pb";
import type { HealthStatus } from "../../api/v2/core/health_check_pb";

/**
 * Describes the file envoy/admin/v2alpha/clusters.proto.
 */
export declare const file_envoy_admin_v2alpha_clusters: GenFile;

/**
 * Admin endpoint uses this wrapper for `/clusters` to display cluster status information.
 * See :ref:`/clusters <operations_admin_interface_clusters>` for more information.
 *
 * @generated from message envoy.admin.v2alpha.Clusters
 */
export declare type Clusters = Message<"envoy.admin.v2alpha.Clusters"> & {
  /**
   * Mapping from cluster name to each cluster's status.
   *
   * @generated from field: repeated envoy.admin.v2alpha.ClusterStatus cluster_statuses = 1;
   */
  clusterStatuses: ClusterStatus[];
};

/**
 * Describes the message envoy.admin.v2alpha.Clusters.
 * Use `create(ClustersSchema)` to create a new message.
 */
export declare const ClustersSchema: GenMessage<Clusters>;

/**
 * Details an individual cluster's current status.
 * [#next-free-field: 6]
 *
 * @generated from message envoy.admin.v2alpha.ClusterStatus
 */
export declare type ClusterStatus = Message<"envoy.admin.v2alpha.ClusterStatus"> & {
  /**
   * Name of the cluster.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Denotes whether this cluster was added via API or configured statically.
   *
   * @generated from field: bool added_via_api = 2;
   */
  addedViaApi: boolean;

  /**
   * The success rate threshold used in the last interval.
   * If
   * :ref:`outlier_detection.split_external_local_origin_errors<envoy_api_field_cluster.OutlierDetection.split_external_local_origin_errors>`
   * is *false*, all errors: externally and locally generated were used to calculate the threshold.
   * If
   * :ref:`outlier_detection.split_external_local_origin_errors<envoy_api_field_cluster.OutlierDetection.split_external_local_origin_errors>`
   * is *true*, only externally generated errors were used to calculate the threshold.
   * The threshold is used to eject hosts based on their success rate. See
   * :ref:`Cluster outlier detection <arch_overview_outlier_detection>` documentation for details.
   *
   * Note: this field may be omitted in any of the three following cases:
   *
   * 1. There were not enough hosts with enough request volume to proceed with success rate based
   *    outlier ejection.
   * 2. The threshold is computed to be < 0 because a negative value implies that there was no
   *    threshold for that interval.
   * 3. Outlier detection is not enabled for this cluster.
   *
   * @generated from field: envoy.type.Percent success_rate_ejection_threshold = 3;
   */
  successRateEjectionThreshold?: Percent;

  /**
   * Mapping from host address to the host's current status.
   *
   * @generated from field: repeated envoy.admin.v2alpha.HostStatus host_statuses = 4;
   */
  hostStatuses: HostStatus[];

  /**
   * The success rate threshold used in the last interval when only locally originated failures were
   * taken into account and externally originated errors were treated as success.
   * This field should be interpreted only when
   * :ref:`outlier_detection.split_external_local_origin_errors<envoy_api_field_cluster.OutlierDetection.split_external_local_origin_errors>`
   * is *true*. The threshold is used to eject hosts based on their success rate.
   * See :ref:`Cluster outlier detection <arch_overview_outlier_detection>` documentation for
   * details.
   *
   * Note: this field may be omitted in any of the three following cases:
   *
   * 1. There were not enough hosts with enough request volume to proceed with success rate based
   *    outlier ejection.
   * 2. The threshold is computed to be < 0 because a negative value implies that there was no
   *    threshold for that interval.
   * 3. Outlier detection is not enabled for this cluster.
   *
   * @generated from field: envoy.type.Percent local_origin_success_rate_ejection_threshold = 5;
   */
  localOriginSuccessRateEjectionThreshold?: Percent;
};

/**
 * Describes the message envoy.admin.v2alpha.ClusterStatus.
 * Use `create(ClusterStatusSchema)` to create a new message.
 */
export declare const ClusterStatusSchema: GenMessage<ClusterStatus>;

/**
 * Current state of a particular host.
 * [#next-free-field: 10]
 *
 * @generated from message envoy.admin.v2alpha.HostStatus
 */
export declare type HostStatus = Message<"envoy.admin.v2alpha.HostStatus"> & {
  /**
   * Address of this host.
   *
   * @generated from field: envoy.api.v2.core.Address address = 1;
   */
  address?: Address;

  /**
   * List of stats specific to this host.
   *
   * @generated from field: repeated envoy.admin.v2alpha.SimpleMetric stats = 2;
   */
  stats: SimpleMetric[];

  /**
   * The host's current health status.
   *
   * @generated from field: envoy.admin.v2alpha.HostHealthStatus health_status = 3;
   */
  healthStatus?: HostHealthStatus;

  /**
   * Request success rate for this host over the last calculated interval.
   * If
   * :ref:`outlier_detection.split_external_local_origin_errors<envoy_api_field_cluster.OutlierDetection.split_external_local_origin_errors>`
   * is *false*, all errors: externally and locally generated were used in success rate
   * calculation. If
   * :ref:`outlier_detection.split_external_local_origin_errors<envoy_api_field_cluster.OutlierDetection.split_external_local_origin_errors>`
   * is *true*, only externally generated errors were used in success rate calculation.
   * See :ref:`Cluster outlier detection <arch_overview_outlier_detection>` documentation for
   * details.
   *
   * Note: the message will not be present if host did not have enough request volume to calculate
   * success rate or the cluster did not have enough hosts to run through success rate outlier
   * ejection.
   *
   * @generated from field: envoy.type.Percent success_rate = 4;
   */
  successRate?: Percent;

  /**
   * The host's weight. If not configured, the value defaults to 1.
   *
   * @generated from field: uint32 weight = 5;
   */
  weight: number;

  /**
   * The hostname of the host, if applicable.
   *
   * @generated from field: string hostname = 6;
   */
  hostname: string;

  /**
   * The host's priority. If not configured, the value defaults to 0 (highest priority).
   *
   * @generated from field: uint32 priority = 7;
   */
  priority: number;

  /**
   * Request success rate for this host over the last calculated
   * interval when only locally originated errors are taken into account and externally originated
   * errors were treated as success.
   * This field should be interpreted only when
   * :ref:`outlier_detection.split_external_local_origin_errors<envoy_api_field_cluster.OutlierDetection.split_external_local_origin_errors>`
   * is *true*.
   * See :ref:`Cluster outlier detection <arch_overview_outlier_detection>` documentation for
   * details.
   *
   * Note: the message will not be present if host did not have enough request volume to calculate
   * success rate or the cluster did not have enough hosts to run through success rate outlier
   * ejection.
   *
   * @generated from field: envoy.type.Percent local_origin_success_rate = 8;
   */
  localOriginSuccessRate?: Percent;

  /**
   * locality of the host.
   *
   * @generated from field: envoy.api.v2.core.Locality locality = 9;
   */
  locality?: Locality;
};

/**
 * Describes the message envoy.admin.v2alpha.HostStatus.
 * Use `create(HostStatusSchema)` to create a new message.
 */
export declare const HostStatusSchema: GenMessage<HostStatus>;

/**
 * Health status for a host.
 * [#next-free-field: 7]
 *
 * @generated from message envoy.admin.v2alpha.HostHealthStatus
 */
export declare type HostHealthStatus = Message<"envoy.admin.v2alpha.HostHealthStatus"> & {
  /**
   * The host is currently failing active health checks.
   *
   * @generated from field: bool failed_active_health_check = 1;
   */
  failedActiveHealthCheck: boolean;

  /**
   * The host is currently considered an outlier and has been ejected.
   *
   * @generated from field: bool failed_outlier_check = 2;
   */
  failedOutlierCheck: boolean;

  /**
   * The host is currently being marked as degraded through active health checking.
   *
   * @generated from field: bool failed_active_degraded_check = 4;
   */
  failedActiveDegradedCheck: boolean;

  /**
   * The host has been removed from service discovery, but is being stabilized due to active
   * health checking.
   *
   * @generated from field: bool pending_dynamic_removal = 5;
   */
  pendingDynamicRemoval: boolean;

  /**
   * The host has not yet been health checked.
   *
   * @generated from field: bool pending_active_hc = 6;
   */
  pendingActiveHc: boolean;

  /**
   * Health status as reported by EDS. Note: only HEALTHY and UNHEALTHY are currently supported
   * here.
   * [#comment:TODO(mrice32): pipe through remaining EDS health status possibilities.]
   *
   * @generated from field: envoy.api.v2.core.HealthStatus eds_health_status = 3;
   */
  edsHealthStatus: HealthStatus;
};

/**
 * Describes the message envoy.admin.v2alpha.HostHealthStatus.
 * Use `create(HostHealthStatusSchema)` to create a new message.
 */
export declare const HostHealthStatusSchema: GenMessage<HostHealthStatus>;

