// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/admin/v2alpha/metrics.proto (package envoy.admin.v2alpha, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/admin/v2alpha/metrics.proto.
 */
export declare const file_envoy_admin_v2alpha_metrics: GenFile;

/**
 * Proto representation of an Envoy Counter or Gauge value.
 *
 * @generated from message envoy.admin.v2alpha.SimpleMetric
 */
export declare type SimpleMetric = Message<"envoy.admin.v2alpha.SimpleMetric"> & {
  /**
   * Type of the metric represented.
   *
   * @generated from field: envoy.admin.v2alpha.SimpleMetric.Type type = 1;
   */
  type: SimpleMetric_Type;

  /**
   * Current metric value.
   *
   * @generated from field: uint64 value = 2;
   */
  value: bigint;

  /**
   * Name of the metric.
   *
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message envoy.admin.v2alpha.SimpleMetric.
 * Use `create(SimpleMetricSchema)` to create a new message.
 */
export declare const SimpleMetricSchema: GenMessage<SimpleMetric>;

/**
 * @generated from enum envoy.admin.v2alpha.SimpleMetric.Type
 */
export enum SimpleMetric_Type {
  /**
   * @generated from enum value: COUNTER = 0;
   */
  COUNTER = 0,

  /**
   * @generated from enum value: GAUGE = 1;
   */
  GAUGE = 1,
}

/**
 * Describes the enum envoy.admin.v2alpha.SimpleMetric.Type.
 */
export declare const SimpleMetric_TypeSchema: GenEnum<SimpleMetric_Type>;

