// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/api/v2/listener/listener.proto (package envoy.api.v2.listener, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file envoy/api/v2/listener/listener.proto.
 */
export declare const file_envoy_api_v2_listener_listener: GenFile;

