// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/api/v2/listener/quic_config.proto (package envoy.api.v2.listener, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_duration, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_migrate } from "../../../../udpa/annotations/migrate_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/api/v2/listener/quic_config.proto.
 */
export const file_envoy_api_v2_listener_quic_config = /*@__PURE__*/
  fileDesc("CidlbnZveS9hcGkvdjIvbGlzdGVuZXIvcXVpY19jb25maWcucHJvdG8SFWVudm95LmFwaS52Mi5saXN0ZW5lciLBAQoTUXVpY1Byb3RvY29sT3B0aW9ucxI8ChZtYXhfY29uY3VycmVudF9zdHJlYW1zGAEgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlVJbnQzMlZhbHVlEi8KDGlkbGVfdGltZW91dBgCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhI7ChhjcnlwdG9faGFuZHNoYWtlX3RpbWVvdXQYAyABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25C1QEKI2lvLmVudm95cHJveHkuZW52b3kuYXBpLnYyLmxpc3RlbmVyQg9RdWljQ29uZmlnUHJvdG9QAVo8Z2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvYXBpL3YyL2xpc3RlbmVyqgIXRW52b3kuQXBpLlYyLkxpc3RlbmVyTlPqAhpFbnZveTo6QXBpOjpWMjo6TGlzdGVuZXJOU/KY/o8FGhIYZW52b3kuY29uZmlnLmxpc3RlbmVyLnYzuoDI0QYCEAFiBnByb3RvMw", [file_google_protobuf_duration, file_google_protobuf_wrappers, file_udpa_annotations_migrate, file_udpa_annotations_status]);

/**
 * Describes the message envoy.api.v2.listener.QuicProtocolOptions.
 * Use `create(QuicProtocolOptionsSchema)` to create a new message.
 */
export const QuicProtocolOptionsSchema = /*@__PURE__*/
  messageDesc(file_envoy_api_v2_listener_quic_config, 0);

