// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/api/v2/listener/udp_listener_config.proto (package envoy.api.v2.listener, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Any } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file envoy/api/v2/listener/udp_listener_config.proto.
 */
export declare const file_envoy_api_v2_listener_udp_listener_config: GenFile;

/**
 * @generated from message envoy.api.v2.listener.UdpListenerConfig
 */
export declare type UdpListenerConfig = Message<"envoy.api.v2.listener.UdpListenerConfig"> & {
  /**
   * Used to look up UDP listener factory, matches "raw_udp_listener" or
   * "quic_listener" to create a specific udp listener.
   * If not specified, treat as "raw_udp_listener".
   *
   * @generated from field: string udp_listener_name = 1;
   */
  udpListenerName: string;

  /**
   * Used to create a specific listener factory. To some factory, e.g.
   * "raw_udp_listener", config is not needed.
   *
   * @generated from oneof envoy.api.v2.listener.UdpListenerConfig.config_type
   */
  configType: {
    /**
     * @generated from field: google.protobuf.Struct config = 2 [deprecated = true];
     * @deprecated
     */
    value: JsonObject;
    case: "config";
  } | {
    /**
     * @generated from field: google.protobuf.Any typed_config = 3;
     */
    value: Any;
    case: "typedConfig";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.api.v2.listener.UdpListenerConfig.
 * Use `create(UdpListenerConfigSchema)` to create a new message.
 */
export declare const UdpListenerConfigSchema: GenMessage<UdpListenerConfig>;

/**
 * @generated from message envoy.api.v2.listener.ActiveRawUdpListenerConfig
 */
export declare type ActiveRawUdpListenerConfig = Message<"envoy.api.v2.listener.ActiveRawUdpListenerConfig"> & {
};

/**
 * Describes the message envoy.api.v2.listener.ActiveRawUdpListenerConfig.
 * Use `create(ActiveRawUdpListenerConfigSchema)` to create a new message.
 */
export declare const ActiveRawUdpListenerConfigSchema: GenMessage<ActiveRawUdpListenerConfig>;

