// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/service/event_reporting/v3/event_reporting_service.proto (package envoy.service.event_reporting.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Any } from "@bufbuild/protobuf/wkt";
import type { Node } from "../../../config/core/v3/base_pb";

/**
 * Describes the file envoy/service/event_reporting/v3/event_reporting_service.proto.
 */
export declare const file_envoy_service_event_reporting_v3_event_reporting_service: GenFile;

/**
 * [#not-implemented-hide:]
 * An events envoy sends to the management server.
 *
 * @generated from message envoy.service.event_reporting.v3.StreamEventsRequest
 */
export declare type StreamEventsRequest = Message<"envoy.service.event_reporting.v3.StreamEventsRequest"> & {
  /**
   * Identifier data that will only be sent in the first message on the stream. This is effectively
   * structured metadata and is a performance optimization.
   *
   * @generated from field: envoy.service.event_reporting.v3.StreamEventsRequest.Identifier identifier = 1;
   */
  identifier?: StreamEventsRequest_Identifier;

  /**
   * Batch of events. When the stream is already active, it will be the events occurred
   * since the last message had been sent. If the server receives unknown event type, it should
   * silently ignore it.
   *
   * The following events are supported:
   *
   * * :ref:`HealthCheckEvent <envoy_v3_api_msg_data.core.v3.HealthCheckEvent>`
   * * :ref:`OutlierDetectionEvent <envoy_v3_api_msg_data.cluster.v3.OutlierDetectionEvent>`
   *
   * @generated from field: repeated google.protobuf.Any events = 2;
   */
  events: Any[];
};

/**
 * Describes the message envoy.service.event_reporting.v3.StreamEventsRequest.
 * Use `create(StreamEventsRequestSchema)` to create a new message.
 */
export declare const StreamEventsRequestSchema: GenMessage<StreamEventsRequest>;

/**
 * @generated from message envoy.service.event_reporting.v3.StreamEventsRequest.Identifier
 */
export declare type StreamEventsRequest_Identifier = Message<"envoy.service.event_reporting.v3.StreamEventsRequest.Identifier"> & {
  /**
   * The node sending the event messages over the stream.
   *
   * @generated from field: envoy.config.core.v3.Node node = 1;
   */
  node?: Node;
};

/**
 * Describes the message envoy.service.event_reporting.v3.StreamEventsRequest.Identifier.
 * Use `create(StreamEventsRequest_IdentifierSchema)` to create a new message.
 */
export declare const StreamEventsRequest_IdentifierSchema: GenMessage<StreamEventsRequest_Identifier>;

/**
 * [#not-implemented-hide:]
 * The management server may send envoy a StreamEventsResponse to tell which events the server
 * is interested in. In future, with aggregated event reporting service, this message will
 * contain, for example, clusters the envoy should send events for, or event types the server
 * wants to process.
 *
 * @generated from message envoy.service.event_reporting.v3.StreamEventsResponse
 */
export declare type StreamEventsResponse = Message<"envoy.service.event_reporting.v3.StreamEventsResponse"> & {
};

/**
 * Describes the message envoy.service.event_reporting.v3.StreamEventsResponse.
 * Use `create(StreamEventsResponseSchema)` to create a new message.
 */
export declare const StreamEventsResponseSchema: GenMessage<StreamEventsResponse>;

/**
 * [#not-implemented-hide:]
 * Service for streaming different types of events from Envoy to a server. The examples of
 * such events may be health check or outlier detection events.
 *
 * @generated from service envoy.service.event_reporting.v3.EventReportingService
 */
export declare const EventReportingService: GenService<{
  /**
   * Envoy will connect and send StreamEventsRequest messages forever.
   * The management server may send StreamEventsResponse to configure event stream. See below.
   * This API is designed for high throughput with the expectation that it might be lossy.
   *
   * @generated from rpc envoy.service.event_reporting.v3.EventReportingService.StreamEvents
   */
  streamEvents: {
    methodKind: "bidi_streaming";
    input: typeof StreamEventsRequestSchema;
    output: typeof StreamEventsResponseSchema;
  },
}>;

