// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/service/route/v3/rds.proto (package envoy.service.route.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_service_discovery_v3_discovery } from "../../discovery/v3/discovery_pb";
import { file_google_api_annotations } from "../../../../google/api/annotations_pb";
import { file_envoy_annotations_resource } from "../../../annotations/resource_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../udpa/annotations/versioning_pb";

/**
 * Describes the file envoy/service/route/v3/rds.proto.
 */
export const file_envoy_service_route_v3_rds = /*@__PURE__*/
  fileDesc("CiBlbnZveS9zZXJ2aWNlL3JvdXRlL3YzL3Jkcy5wcm90bxIWZW52b3kuc2VydmljZS5yb3V0ZS52MyIoCghSZHNEdW1teTocmsWIHhcKFWVudm95LmFwaS52Mi5SZHNEdW1teTLGAwoVUm91dGVEaXNjb3ZlcnlTZXJ2aWNlEnEKDFN0cmVhbVJvdXRlcxIsLmVudm95LnNlcnZpY2UuZGlzY292ZXJ5LnYzLkRpc2NvdmVyeVJlcXVlc3QaLS5lbnZveS5zZXJ2aWNlLmRpc2NvdmVyeS52My5EaXNjb3ZlcnlSZXNwb25zZSIAKAEwARJ6CgtEZWx0YVJvdXRlcxIxLmVudm95LnNlcnZpY2UuZGlzY292ZXJ5LnYzLkRlbHRhRGlzY292ZXJ5UmVxdWVzdBoyLmVudm95LnNlcnZpY2UuZGlzY292ZXJ5LnYzLkRlbHRhRGlzY292ZXJ5UmVzcG9uc2UiACgBMAESiwEKC0ZldGNoUm91dGVzEiwuZW52b3kuc2VydmljZS5kaXNjb3ZlcnkudjMuRGlzY292ZXJ5UmVxdWVzdBotLmVudm95LnNlcnZpY2UuZGlzY292ZXJ5LnYzLkRpc2NvdmVyeVJlc3BvbnNlIh+C0+STAhk6ASoiFC92My9kaXNjb3Zlcnk6cm91dGVzGjCKpJbzByoKKGVudm95LmNvbmZpZy5yb3V0ZS52My5Sb3V0ZUNvbmZpZ3VyYXRpb24yywEKG1ZpcnR1YWxIb3N0RGlzY292ZXJ5U2VydmljZRKAAQoRRGVsdGFWaXJ0dWFsSG9zdHMSMS5lbnZveS5zZXJ2aWNlLmRpc2NvdmVyeS52My5EZWx0YURpc2NvdmVyeVJlcXVlc3QaMi5lbnZveS5zZXJ2aWNlLmRpc2NvdmVyeS52My5EZWx0YURpc2NvdmVyeVJlc3BvbnNlIgAoATABGimKpJbzByMKIWVudm95LmNvbmZpZy5yb3V0ZS52My5WaXJ0dWFsSG9zdEKBAQokaW8uZW52b3lwcm94eS5lbnZveS5zZXJ2aWNlLnJvdXRlLnYzQghSZHNQcm90b1ABWkVnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9zZXJ2aWNlL3JvdXRlL3YzO3JvdXRldjO6gMjRBgIQAmIGcHJvdG8z", [file_envoy_service_discovery_v3_discovery, file_google_api_annotations, file_envoy_annotations_resource, file_udpa_annotations_status, file_udpa_annotations_versioning]);

/**
 * Describes the message envoy.service.route.v3.RdsDummy.
 * Use `create(RdsDummySchema)` to create a new message.
 */
export const RdsDummySchema = /*@__PURE__*/
  messageDesc(file_envoy_service_route_v3_rds, 0);

/**
 * The resource_names field in DiscoveryRequest specifies a route configuration.
 * This allows an Envoy configuration with multiple HTTP listeners (and
 * associated HTTP connection manager filters) to use different route
 * configurations. Each listener will bind its HTTP connection manager filter to
 * a route table via this identifier.
 *
 * @generated from service envoy.service.route.v3.RouteDiscoveryService
 */
export const RouteDiscoveryService = /*@__PURE__*/
  serviceDesc(file_envoy_service_route_v3_rds, 0);

/**
 * Virtual Host Discovery Service (VHDS) is used to dynamically update the list of virtual hosts for
 * a given RouteConfiguration. If VHDS is configured a virtual host list update will be triggered
 * during the processing of an HTTP request if a route for the request cannot be resolved. The
 * :ref:`resource_names_subscribe <envoy_v3_api_field_service.discovery.v3.DeltaDiscoveryRequest.resource_names_subscribe>`
 * field contains a list of virtual host names or aliases to track. The contents of an alias would
 * be the contents of a ``host`` or ``authority`` header used to make an http request. An xDS server
 * will match an alias to a virtual host based on the content of :ref:`domains'
 * <envoy_v3_api_field_config.route.v3.VirtualHost.domains>` field. The ``resource_names_unsubscribe`` field
 * contains a list of virtual host names that have been :ref:`unsubscribed
 * <xds_protocol_unsubscribe>` from the routing table associated with the RouteConfiguration.
 *
 * @generated from service envoy.service.route.v3.VirtualHostDiscoveryService
 */
export const VirtualHostDiscoveryService = /*@__PURE__*/
  serviceDesc(file_envoy_service_route_v3_rds, 1);

