// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/network/thrift_proxy/filters/ratelimit/v3/rate_limit.proto (package envoy.extensions.filters.network.thrift_proxy.filters.ratelimit.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_config_ratelimit_v3_rls } from "../../../../../../../config/ratelimit/v3/rls_pb";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../../../../../udpa/annotations/versioning_pb";
import { file_validate_validate } from "../../../../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/filters/network/thrift_proxy/filters/ratelimit/v3/rate_limit.proto.
 */
export const file_envoy_extensions_filters_network_thrift_proxy_filters_ratelimit_v3_rate_limit = /*@__PURE__*/
  fileDesc("ClNlbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvbmV0d29yay90aHJpZnRfcHJveHkvZmlsdGVycy9yYXRlbGltaXQvdjMvcmF0ZV9saW1pdC5wcm90bxJCZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLm5ldHdvcmsudGhyaWZ0X3Byb3h5LmZpbHRlcnMucmF0ZWxpbWl0LnYzIp0CCglSYXRlTGltaXQSFwoGZG9tYWluGAEgASgJQgf6QgRyAhABEhYKBXN0YWdlGAIgASgNQgf6QgQqAhgKEioKB3RpbWVvdXQYAyABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SGQoRZmFpbHVyZV9tb2RlX2RlbnkYBCABKAgSVwoScmF0ZV9saW1pdF9zZXJ2aWNlGAUgASgLMjEuZW52b3kuY29uZmlnLnJhdGVsaW1pdC52My5SYXRlTGltaXRTZXJ2aWNlQ29uZmlnQgj6QgWKAQIQATo/msWIHjoKOGVudm95LmNvbmZpZy5maWx0ZXIudGhyaWZ0LnJhdGVfbGltaXQudjJhbHBoYTEuUmF0ZUxpbWl0QuMBClBpby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5uZXR3b3JrLnRocmlmdF9wcm94eS5maWx0ZXJzLnJhdGVsaW1pdC52M0IOUmF0ZUxpbWl0UHJvdG9QAVp1Z2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9maWx0ZXJzL25ldHdvcmsvdGhyaWZ0X3Byb3h5L2ZpbHRlcnMvcmF0ZWxpbWl0L3YzO3JhdGVsaW1pdHYzuoDI0QYCEAJiBnByb3RvMw", [file_envoy_config_ratelimit_v3_rls, file_google_protobuf_duration, file_udpa_annotations_status, file_udpa_annotations_versioning, file_validate_validate]);

/**
 * Describes the message envoy.extensions.filters.network.thrift_proxy.filters.ratelimit.v3.RateLimit.
 * Use `create(RateLimitSchema)` to create a new message.
 */
export const RateLimitSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_network_thrift_proxy_filters_ratelimit_v3_rate_limit, 0);

