// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/network/thrift_proxy/filters/ratelimit/v3/rate_limit.proto (package envoy.extensions.filters.network.thrift_proxy.filters.ratelimit.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration } from "@bufbuild/protobuf/wkt";
import type { RateLimitServiceConfig } from "../../../../../../../config/ratelimit/v3/rls_pb";

/**
 * Describes the file envoy/extensions/filters/network/thrift_proxy/filters/ratelimit/v3/rate_limit.proto.
 */
export declare const file_envoy_extensions_filters_network_thrift_proxy_filters_ratelimit_v3_rate_limit: GenFile;

/**
 * [#next-free-field: 6]
 *
 * @generated from message envoy.extensions.filters.network.thrift_proxy.filters.ratelimit.v3.RateLimit
 */
export declare type RateLimit = Message<"envoy.extensions.filters.network.thrift_proxy.filters.ratelimit.v3.RateLimit"> & {
  /**
   * The rate limit domain to use in the rate limit service request.
   *
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * Specifies the rate limit configuration stage. Each configured rate limit filter performs a
   * rate limit check using descriptors configured in the
   * :ref:`envoy_v3_api_msg_extensions.filters.network.thrift_proxy.v3.RouteAction` for the request.
   * Only those entries with a matching stage number are used for a given filter. If not set, the
   * default stage number is 0.
   *
   * .. note::
   *
   *  The filter supports a range of 0 - 10 inclusively for stage numbers.
   *
   * @generated from field: uint32 stage = 2;
   */
  stage: number;

  /**
   * The timeout in milliseconds for the rate limit service RPC. If not
   * set, this defaults to 20ms.
   *
   * @generated from field: google.protobuf.Duration timeout = 3;
   */
  timeout?: Duration;

  /**
   * The filter's behaviour in case the rate limiting service does
   * not respond back. When it is set to true, Envoy will not allow traffic in case of
   * communication failure between rate limiting service and the proxy.
   * Defaults to false.
   *
   * @generated from field: bool failure_mode_deny = 4;
   */
  failureModeDeny: boolean;

  /**
   * Configuration for an external rate limit service provider. If not
   * specified, any calls to the rate limit service will immediately return
   * success.
   *
   * @generated from field: envoy.config.ratelimit.v3.RateLimitServiceConfig rate_limit_service = 5;
   */
  rateLimitService?: RateLimitServiceConfig;
};

/**
 * Describes the message envoy.extensions.filters.network.thrift_proxy.filters.ratelimit.v3.RateLimit.
 * Use `create(RateLimitSchema)` to create a new message.
 */
export declare const RateLimitSchema: GenMessage<RateLimit>;

