// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto (package envoy.extensions.filters.http.dynamic_forward_proxy.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_extensions_common_dynamic_forward_proxy_v3_dns_cache } from "../../../../common/dynamic_forward_proxy/v3/dns_cache_pb";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../../../udpa/annotations/versioning_pb";
import { file_validate_validate } from "../../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto.
 */
export const file_envoy_extensions_filters_http_dynamic_forward_proxy_v3_dynamic_forward_proxy = /*@__PURE__*/
  fileDesc("ClJlbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9keW5hbWljX2ZvcndhcmRfcHJveHkvdjMvZHluYW1pY19mb3J3YXJkX3Byb3h5LnByb3RvEjZlbnZveS5leHRlbnNpb25zLmZpbHRlcnMuaHR0cC5keW5hbWljX2ZvcndhcmRfcHJveHkudjMiiQMKDEZpbHRlckNvbmZpZxJcChBkbnNfY2FjaGVfY29uZmlnGAEgASgLMkAuZW52b3kuZXh0ZW5zaW9ucy5jb21tb24uZHluYW1pY19mb3J3YXJkX3Byb3h5LnYzLkRuc0NhY2hlQ29uZmlnSAASZgoSc3ViX2NsdXN0ZXJfY29uZmlnGAMgASgLMkguZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAuZHluYW1pY19mb3J3YXJkX3Byb3h5LnYzLlN1YkNsdXN0ZXJDb25maWdIABIdChVzYXZlX3Vwc3RyZWFtX2FkZHJlc3MYAiABKAgSLAokYWxsb3dfZHluYW1pY19ob3N0X2Zyb21fZmlsdGVyX3N0YXRlGAQgASgIOkqaxYgeRQpDZW52b3kuY29uZmlnLmZpbHRlci5odHRwLmR5bmFtaWNfZm9yd2FyZF9wcm94eS52MmFscGhhLkZpbHRlckNvbmZpZ0IaChhpbXBsZW1lbnRhdGlvbl9zcGVjaWZpZXIitwEKDlBlclJvdXRlQ29uZmlnEh4KFGhvc3RfcmV3cml0ZV9saXRlcmFsGAEgASgJSAASHQoTaG9zdF9yZXdyaXRlX2hlYWRlchgCIAEoCUgAOkyaxYgeRwpFZW52b3kuY29uZmlnLmZpbHRlci5odHRwLmR5bmFtaWNfZm9yd2FyZF9wcm94eS52MmFscGhhLlBlclJvdXRlQ29uZmlnQhgKFmhvc3RfcmV3cml0ZV9zcGVjaWZpZXIiVQoQU3ViQ2x1c3RlckNvbmZpZxJBChRjbHVzdGVyX2luaXRfdGltZW91dBgDIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkII+kIFqgECKgBC4QEKRGlvLmVudm95cHJveHkuZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAuZHluYW1pY19mb3J3YXJkX3Byb3h5LnYzQhhEeW5hbWljRm9yd2FyZFByb3h5UHJvdG9QAVp1Z2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9maWx0ZXJzL2h0dHAvZHluYW1pY19mb3J3YXJkX3Byb3h5L3YzO2R5bmFtaWNfZm9yd2FyZF9wcm94eXYzuoDI0QYCEAJiBnByb3RvMw", [file_envoy_extensions_common_dynamic_forward_proxy_v3_dns_cache, file_google_protobuf_duration, file_udpa_annotations_status, file_udpa_annotations_versioning, file_validate_validate]);

/**
 * Describes the message envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig.
 * Use `create(FilterConfigSchema)` to create a new message.
 */
export const FilterConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_dynamic_forward_proxy_v3_dynamic_forward_proxy, 0);

/**
 * Describes the message envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig.
 * Use `create(PerRouteConfigSchema)` to create a new message.
 */
export const PerRouteConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_dynamic_forward_proxy_v3_dynamic_forward_proxy, 1);

/**
 * Describes the message envoy.extensions.filters.http.dynamic_forward_proxy.v3.SubClusterConfig.
 * Use `create(SubClusterConfigSchema)` to create a new message.
 */
export const SubClusterConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_dynamic_forward_proxy_v3_dynamic_forward_proxy, 2);

