// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/data/core/v3/health_check_event.proto (package envoy.data.core.v3, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Address } from "../../../config/core/v3/address_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { Locality, Metadata } from "../../../config/core/v3/base_pb";

/**
 * Describes the file envoy/data/core/v3/health_check_event.proto.
 */
export declare const file_envoy_data_core_v3_health_check_event: GenFile;

/**
 * [#next-free-field: 13]
 *
 * @generated from message envoy.data.core.v3.HealthCheckEvent
 */
export declare type HealthCheckEvent = Message<"envoy.data.core.v3.HealthCheckEvent"> & {
  /**
   * @generated from field: envoy.data.core.v3.HealthCheckerType health_checker_type = 1;
   */
  healthCheckerType: HealthCheckerType;

  /**
   * @generated from field: envoy.config.core.v3.Address host = 2;
   */
  host?: Address;

  /**
   * @generated from field: string cluster_name = 3;
   */
  clusterName: string;

  /**
   * @generated from oneof envoy.data.core.v3.HealthCheckEvent.event
   */
  event: {
    /**
     * Host ejection.
     *
     * @generated from field: envoy.data.core.v3.HealthCheckEjectUnhealthy eject_unhealthy_event = 4;
     */
    value: HealthCheckEjectUnhealthy;
    case: "ejectUnhealthyEvent";
  } | {
    /**
     * Host addition.
     *
     * @generated from field: envoy.data.core.v3.HealthCheckAddHealthy add_healthy_event = 5;
     */
    value: HealthCheckAddHealthy;
    case: "addHealthyEvent";
  } | {
    /**
     * A health check was successful. Note: a host will be considered healthy either if it is
     * the first ever health check, or if the healthy threshold is reached. This kind of event
     * indicate that a health check was successful, but does not indicates that the host is
     * considered healthy. A host is considered healthy if HealthCheckAddHealthy kind of event is sent.
     *
     * @generated from field: envoy.data.core.v3.HealthCheckSuccessful successful_health_check_event = 12;
     */
    value: HealthCheckSuccessful;
    case: "successfulHealthCheckEvent";
  } | {
    /**
     * Host failure.
     *
     * @generated from field: envoy.data.core.v3.HealthCheckFailure health_check_failure_event = 7;
     */
    value: HealthCheckFailure;
    case: "healthCheckFailureEvent";
  } | {
    /**
     * Healthy host became degraded.
     *
     * @generated from field: envoy.data.core.v3.DegradedHealthyHost degraded_healthy_host = 8;
     */
    value: DegradedHealthyHost;
    case: "degradedHealthyHost";
  } | {
    /**
     * A degraded host returned to being healthy.
     *
     * @generated from field: envoy.data.core.v3.NoLongerDegradedHost no_longer_degraded_host = 9;
     */
    value: NoLongerDegradedHost;
    case: "noLongerDegradedHost";
  } | { case: undefined; value?: undefined };

  /**
   * Timestamp for event.
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 6;
   */
  timestamp?: Timestamp;

  /**
   * Host metadata
   *
   * @generated from field: envoy.config.core.v3.Metadata metadata = 10;
   */
  metadata?: Metadata;

  /**
   * Host locality
   *
   * @generated from field: envoy.config.core.v3.Locality locality = 11;
   */
  locality?: Locality;
};

/**
 * Describes the message envoy.data.core.v3.HealthCheckEvent.
 * Use `create(HealthCheckEventSchema)` to create a new message.
 */
export declare const HealthCheckEventSchema: GenMessage<HealthCheckEvent>;

/**
 * @generated from message envoy.data.core.v3.HealthCheckEjectUnhealthy
 */
export declare type HealthCheckEjectUnhealthy = Message<"envoy.data.core.v3.HealthCheckEjectUnhealthy"> & {
  /**
   * The type of failure that caused this ejection.
   *
   * @generated from field: envoy.data.core.v3.HealthCheckFailureType failure_type = 1;
   */
  failureType: HealthCheckFailureType;
};

/**
 * Describes the message envoy.data.core.v3.HealthCheckEjectUnhealthy.
 * Use `create(HealthCheckEjectUnhealthySchema)` to create a new message.
 */
export declare const HealthCheckEjectUnhealthySchema: GenMessage<HealthCheckEjectUnhealthy>;

/**
 * @generated from message envoy.data.core.v3.HealthCheckAddHealthy
 */
export declare type HealthCheckAddHealthy = Message<"envoy.data.core.v3.HealthCheckAddHealthy"> & {
  /**
   * Whether this addition is the result of the first ever health check on a host, in which case
   * the configured :ref:`healthy threshold <envoy_v3_api_field_config.core.v3.HealthCheck.healthy_threshold>`
   * is bypassed and the host is immediately added.
   *
   * @generated from field: bool first_check = 1;
   */
  firstCheck: boolean;
};

/**
 * Describes the message envoy.data.core.v3.HealthCheckAddHealthy.
 * Use `create(HealthCheckAddHealthySchema)` to create a new message.
 */
export declare const HealthCheckAddHealthySchema: GenMessage<HealthCheckAddHealthy>;

/**
 * @generated from message envoy.data.core.v3.HealthCheckSuccessful
 */
export declare type HealthCheckSuccessful = Message<"envoy.data.core.v3.HealthCheckSuccessful"> & {
};

/**
 * Describes the message envoy.data.core.v3.HealthCheckSuccessful.
 * Use `create(HealthCheckSuccessfulSchema)` to create a new message.
 */
export declare const HealthCheckSuccessfulSchema: GenMessage<HealthCheckSuccessful>;

/**
 * @generated from message envoy.data.core.v3.HealthCheckFailure
 */
export declare type HealthCheckFailure = Message<"envoy.data.core.v3.HealthCheckFailure"> & {
  /**
   * The type of failure that caused this event.
   *
   * @generated from field: envoy.data.core.v3.HealthCheckFailureType failure_type = 1;
   */
  failureType: HealthCheckFailureType;

  /**
   * Whether this event is the result of the first ever health check on a host.
   *
   * @generated from field: bool first_check = 2;
   */
  firstCheck: boolean;
};

/**
 * Describes the message envoy.data.core.v3.HealthCheckFailure.
 * Use `create(HealthCheckFailureSchema)` to create a new message.
 */
export declare const HealthCheckFailureSchema: GenMessage<HealthCheckFailure>;

/**
 * @generated from message envoy.data.core.v3.DegradedHealthyHost
 */
export declare type DegradedHealthyHost = Message<"envoy.data.core.v3.DegradedHealthyHost"> & {
};

/**
 * Describes the message envoy.data.core.v3.DegradedHealthyHost.
 * Use `create(DegradedHealthyHostSchema)` to create a new message.
 */
export declare const DegradedHealthyHostSchema: GenMessage<DegradedHealthyHost>;

/**
 * @generated from message envoy.data.core.v3.NoLongerDegradedHost
 */
export declare type NoLongerDegradedHost = Message<"envoy.data.core.v3.NoLongerDegradedHost"> & {
};

/**
 * Describes the message envoy.data.core.v3.NoLongerDegradedHost.
 * Use `create(NoLongerDegradedHostSchema)` to create a new message.
 */
export declare const NoLongerDegradedHostSchema: GenMessage<NoLongerDegradedHost>;

/**
 * @generated from enum envoy.data.core.v3.HealthCheckFailureType
 */
export enum HealthCheckFailureType {
  /**
   * @generated from enum value: ACTIVE = 0;
   */
  ACTIVE = 0,

  /**
   * @generated from enum value: PASSIVE = 1;
   */
  PASSIVE = 1,

  /**
   * @generated from enum value: NETWORK = 2;
   */
  NETWORK = 2,

  /**
   * @generated from enum value: NETWORK_TIMEOUT = 3;
   */
  NETWORK_TIMEOUT = 3,
}

/**
 * Describes the enum envoy.data.core.v3.HealthCheckFailureType.
 */
export declare const HealthCheckFailureTypeSchema: GenEnum<HealthCheckFailureType>;

/**
 * @generated from enum envoy.data.core.v3.HealthCheckerType
 */
export enum HealthCheckerType {
  /**
   * @generated from enum value: HTTP = 0;
   */
  HTTP = 0,

  /**
   * @generated from enum value: TCP = 1;
   */
  TCP = 1,

  /**
   * @generated from enum value: GRPC = 2;
   */
  GRPC = 2,

  /**
   * @generated from enum value: REDIS = 3;
   */
  REDIS = 3,

  /**
   * @generated from enum value: THRIFT = 4;
   */
  THRIFT = 4,
}

/**
 * Describes the enum envoy.data.core.v3.HealthCheckerType.
 */
export declare const HealthCheckerTypeSchema: GenEnum<HealthCheckerType>;

