// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/connect_grpc_bridge/v3/config.proto (package envoy.extensions.filters.http.connect_grpc_bridge.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/extensions/filters/http/connect_grpc_bridge/v3/config.proto.
 */
export declare const file_envoy_extensions_filters_http_connect_grpc_bridge_v3_config: GenFile;

/**
 * Connect RPC to gRPC bridge filter configuration
 *
 * @generated from message envoy.extensions.filters.http.connect_grpc_bridge.v3.FilterConfig
 */
export declare type FilterConfig = Message<"envoy.extensions.filters.http.connect_grpc_bridge.v3.FilterConfig"> & {
};

/**
 * Describes the message envoy.extensions.filters.http.connect_grpc_bridge.v3.FilterConfig.
 * Use `create(FilterConfigSchema)` to create a new message.
 */
export declare const FilterConfigSchema: GenMessage<FilterConfig>;

