// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/filter/listener/http_inspector/v2/http_inspector.proto (package envoy.config.filter.listener.http_inspector.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/config/filter/listener/http_inspector/v2/http_inspector.proto.
 */
export declare const file_envoy_config_filter_listener_http_inspector_v2_http_inspector: GenFile;

/**
 * @generated from message envoy.config.filter.listener.http_inspector.v2.HttpInspector
 */
export declare type HttpInspector = Message<"envoy.config.filter.listener.http_inspector.v2.HttpInspector"> & {
};

/**
 * Describes the message envoy.config.filter.listener.http_inspector.v2.HttpInspector.
 * Use `create(HttpInspectorSchema)` to create a new message.
 */
export declare const HttpInspectorSchema: GenMessage<HttpInspector>;

