// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/watchdog/v3/abort_action.proto (package envoy.watchdog.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/watchdog/v3/abort_action.proto.
 */
export const file_envoy_watchdog_v3_abort_action = /*@__PURE__*/
  fileDesc("CiRlbnZveS93YXRjaGRvZy92My9hYm9ydF9hY3Rpb24ucHJvdG8SEWVudm95LndhdGNoZG9nLnYzIkUKEUFib3J0QWN0aW9uQ29uZmlnEjAKDXdhaXRfZHVyYXRpb24YASABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25CggEKH2lvLmVudm95cHJveHkuZW52b3kud2F0Y2hkb2cudjNCEEFib3J0QWN0aW9uUHJvdG9QAVpDZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvd2F0Y2hkb2cvdjM7d2F0Y2hkb2d2M7qAyNEGAhACYgZwcm90bzM", [file_google_protobuf_duration, file_udpa_annotations_status]);

/**
 * Describes the message envoy.watchdog.v3.AbortActionConfig.
 * Use `create(AbortActionConfigSchema)` to create a new message.
 */
export const AbortActionConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_watchdog_v3_abort_action, 0);

