// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/api/v2/core/grpc_service.proto (package envoy.api.v2.core, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Any, Duration, Empty } from "@bufbuild/protobuf/wkt";
import type { DataSource, HeaderValue } from "./base_pb";

/**
 * Describes the file envoy/api/v2/core/grpc_service.proto.
 */
export declare const file_envoy_api_v2_core_grpc_service: GenFile;

/**
 * gRPC service configuration. This is used by :ref:`ApiConfigSource
 * <envoy_api_msg_core.ApiConfigSource>` and filter configurations.
 * [#next-free-field: 6]
 *
 * @generated from message envoy.api.v2.core.GrpcService
 */
export declare type GrpcService = Message<"envoy.api.v2.core.GrpcService"> & {
  /**
   * @generated from oneof envoy.api.v2.core.GrpcService.target_specifier
   */
  targetSpecifier: {
    /**
     * Envoy's in-built gRPC client.
     * See the :ref:`gRPC services overview <arch_overview_grpc_services>`
     * documentation for discussion on gRPC client selection.
     *
     * @generated from field: envoy.api.v2.core.GrpcService.EnvoyGrpc envoy_grpc = 1;
     */
    value: GrpcService_EnvoyGrpc;
    case: "envoyGrpc";
  } | {
    /**
     * `Google C++ gRPC client <https://github.com/grpc/grpc>`_
     * See the :ref:`gRPC services overview <arch_overview_grpc_services>`
     * documentation for discussion on gRPC client selection.
     *
     * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc google_grpc = 2;
     */
    value: GrpcService_GoogleGrpc;
    case: "googleGrpc";
  } | { case: undefined; value?: undefined };

  /**
   * The timeout for the gRPC request. This is the timeout for a specific
   * request.
   *
   * @generated from field: google.protobuf.Duration timeout = 3;
   */
  timeout?: Duration;

  /**
   * Additional metadata to include in streams initiated to the GrpcService.
   * This can be used for scenarios in which additional ad hoc authorization
   * headers (e.g. ``x-foo-bar: baz-key``) are to be injected.
   *
   * @generated from field: repeated envoy.api.v2.core.HeaderValue initial_metadata = 5;
   */
  initialMetadata: HeaderValue[];
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.
 * Use `create(GrpcServiceSchema)` to create a new message.
 */
export declare const GrpcServiceSchema: GenMessage<GrpcService>;

/**
 * @generated from message envoy.api.v2.core.GrpcService.EnvoyGrpc
 */
export declare type GrpcService_EnvoyGrpc = Message<"envoy.api.v2.core.GrpcService.EnvoyGrpc"> & {
  /**
   * The name of the upstream gRPC cluster. SSL credentials will be supplied
   * in the :ref:`Cluster <envoy_api_msg_Cluster>` :ref:`transport_socket
   * <envoy_api_field_Cluster.transport_socket>`.
   *
   * @generated from field: string cluster_name = 1;
   */
  clusterName: string;
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.EnvoyGrpc.
 * Use `create(GrpcService_EnvoyGrpcSchema)` to create a new message.
 */
export declare const GrpcService_EnvoyGrpcSchema: GenMessage<GrpcService_EnvoyGrpc>;

/**
 * [#next-free-field: 7]
 *
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc
 */
export declare type GrpcService_GoogleGrpc = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc"> & {
  /**
   * The target URI when using the `Google C++ gRPC client
   * <https://github.com/grpc/grpc>`_. SSL credentials will be supplied in
   * :ref:`channel_credentials <envoy_api_field_core.GrpcService.GoogleGrpc.channel_credentials>`.
   *
   * @generated from field: string target_uri = 1;
   */
  targetUri: string;

  /**
   * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc.ChannelCredentials channel_credentials = 2;
   */
  channelCredentials?: GrpcService_GoogleGrpc_ChannelCredentials;

  /**
   * A set of call credentials that can be composed with `channel credentials
   * <https://grpc.io/docs/guides/auth.html#credential-types>`_.
   *
   * @generated from field: repeated envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials call_credentials = 3;
   */
  callCredentials: GrpcService_GoogleGrpc_CallCredentials[];

  /**
   * The human readable prefix to use when emitting statistics for the gRPC
   * service.
   *
   * .. csv-table::
   *    :header: Name, Type, Description
   *    :widths: 1, 1, 2
   *
   *    streams_total, Counter, Total number of streams opened
   *    streams_closed_<gRPC status code>, Counter, Total streams closed with <gRPC status code>
   *
   * @generated from field: string stat_prefix = 4;
   */
  statPrefix: string;

  /**
   * The name of the Google gRPC credentials factory to use. This must have been registered with
   * Envoy. If this is empty, a default credentials factory will be used that sets up channel
   * credentials based on other configuration parameters.
   *
   * @generated from field: string credentials_factory_name = 5;
   */
  credentialsFactoryName: string;

  /**
   * Additional configuration for site-specific customizations of the Google
   * gRPC library.
   *
   * @generated from field: google.protobuf.Struct config = 6;
   */
  config?: JsonObject;
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.
 * Use `create(GrpcService_GoogleGrpcSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpcSchema: GenMessage<GrpcService_GoogleGrpc>;

/**
 * See https://grpc.io/grpc/cpp/structgrpc_1_1_ssl_credentials_options.html.
 *
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.SslCredentials
 */
export declare type GrpcService_GoogleGrpc_SslCredentials = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.SslCredentials"> & {
  /**
   * PEM encoded server root certificates.
   *
   * @generated from field: envoy.api.v2.core.DataSource root_certs = 1;
   */
  rootCerts?: DataSource;

  /**
   * PEM encoded client private key.
   *
   * @generated from field: envoy.api.v2.core.DataSource private_key = 2;
   */
  privateKey?: DataSource;

  /**
   * PEM encoded client certificate chain.
   *
   * @generated from field: envoy.api.v2.core.DataSource cert_chain = 3;
   */
  certChain?: DataSource;
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.SslCredentials.
 * Use `create(GrpcService_GoogleGrpc_SslCredentialsSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_SslCredentialsSchema: GenMessage<GrpcService_GoogleGrpc_SslCredentials>;

/**
 * Local channel credentials. Only UDS is supported for now.
 * See https://github.com/grpc/grpc/pull/15909.
 *
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.GoogleLocalCredentials
 */
export declare type GrpcService_GoogleGrpc_GoogleLocalCredentials = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.GoogleLocalCredentials"> & {
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.GoogleLocalCredentials.
 * Use `create(GrpcService_GoogleGrpc_GoogleLocalCredentialsSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_GoogleLocalCredentialsSchema: GenMessage<GrpcService_GoogleGrpc_GoogleLocalCredentials>;

/**
 * See https://grpc.io/docs/guides/auth.html#credential-types to understand Channel and Call
 * credential types.
 *
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.ChannelCredentials
 */
export declare type GrpcService_GoogleGrpc_ChannelCredentials = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.ChannelCredentials"> & {
  /**
   * @generated from oneof envoy.api.v2.core.GrpcService.GoogleGrpc.ChannelCredentials.credential_specifier
   */
  credentialSpecifier: {
    /**
     * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc.SslCredentials ssl_credentials = 1;
     */
    value: GrpcService_GoogleGrpc_SslCredentials;
    case: "sslCredentials";
  } | {
    /**
     * https://grpc.io/grpc/cpp/namespacegrpc.html#a6beb3ac70ff94bd2ebbd89b8f21d1f61
     *
     * @generated from field: google.protobuf.Empty google_default = 2;
     */
    value: Empty;
    case: "googleDefault";
  } | {
    /**
     * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc.GoogleLocalCredentials local_credentials = 3;
     */
    value: GrpcService_GoogleGrpc_GoogleLocalCredentials;
    case: "localCredentials";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.ChannelCredentials.
 * Use `create(GrpcService_GoogleGrpc_ChannelCredentialsSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_ChannelCredentialsSchema: GenMessage<GrpcService_GoogleGrpc_ChannelCredentials>;

/**
 * [#next-free-field: 8]
 *
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials
 */
export declare type GrpcService_GoogleGrpc_CallCredentials = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials"> & {
  /**
   * @generated from oneof envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.credential_specifier
   */
  credentialSpecifier: {
    /**
     * Access token credentials.
     * https://grpc.io/grpc/cpp/namespacegrpc.html#ad3a80da696ffdaea943f0f858d7a360d.
     *
     * @generated from field: string access_token = 1;
     */
    value: string;
    case: "accessToken";
  } | {
    /**
     * Google Compute Engine credentials.
     * https://grpc.io/grpc/cpp/namespacegrpc.html#a6beb3ac70ff94bd2ebbd89b8f21d1f61
     *
     * @generated from field: google.protobuf.Empty google_compute_engine = 2;
     */
    value: Empty;
    case: "googleComputeEngine";
  } | {
    /**
     * Google refresh token credentials.
     * https://grpc.io/grpc/cpp/namespacegrpc.html#a96901c997b91bc6513b08491e0dca37c.
     *
     * @generated from field: string google_refresh_token = 3;
     */
    value: string;
    case: "googleRefreshToken";
  } | {
    /**
     * Service Account JWT Access credentials.
     * https://grpc.io/grpc/cpp/namespacegrpc.html#a92a9f959d6102461f66ee973d8e9d3aa.
     *
     * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.ServiceAccountJWTAccessCredentials service_account_jwt_access = 4;
     */
    value: GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials;
    case: "serviceAccountJwtAccess";
  } | {
    /**
     * Google IAM credentials.
     * https://grpc.io/grpc/cpp/namespacegrpc.html#a9fc1fc101b41e680d47028166e76f9d0.
     *
     * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.GoogleIAMCredentials google_iam = 5;
     */
    value: GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials;
    case: "googleIam";
  } | {
    /**
     * Custom authenticator credentials.
     * https://grpc.io/grpc/cpp/namespacegrpc.html#a823c6a4b19ffc71fb33e90154ee2ad07.
     * https://grpc.io/docs/guides/auth.html#extending-grpc-to-support-other-authentication-mechanisms.
     *
     * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.MetadataCredentialsFromPlugin from_plugin = 6;
     */
    value: GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin;
    case: "fromPlugin";
  } | {
    /**
     * Custom security token service which implements OAuth 2.0 token exchange.
     * https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-16
     * See https://github.com/grpc/grpc/pull/19587.
     *
     * @generated from field: envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.StsService sts_service = 7;
     */
    value: GrpcService_GoogleGrpc_CallCredentials_StsService;
    case: "stsService";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.
 * Use `create(GrpcService_GoogleGrpc_CallCredentialsSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_CallCredentialsSchema: GenMessage<GrpcService_GoogleGrpc_CallCredentials>;

/**
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.ServiceAccountJWTAccessCredentials
 */
export declare type GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.ServiceAccountJWTAccessCredentials"> & {
  /**
   * @generated from field: string json_key = 1;
   */
  jsonKey: string;

  /**
   * @generated from field: uint64 token_lifetime_seconds = 2;
   */
  tokenLifetimeSeconds: bigint;
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.ServiceAccountJWTAccessCredentials.
 * Use `create(GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentialsSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentialsSchema: GenMessage<GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials>;

/**
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.GoogleIAMCredentials
 */
export declare type GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.GoogleIAMCredentials"> & {
  /**
   * @generated from field: string authorization_token = 1;
   */
  authorizationToken: string;

  /**
   * @generated from field: string authority_selector = 2;
   */
  authoritySelector: string;
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.GoogleIAMCredentials.
 * Use `create(GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentialsSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentialsSchema: GenMessage<GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials>;

/**
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.MetadataCredentialsFromPlugin
 */
export declare type GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.MetadataCredentialsFromPlugin"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from oneof envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.MetadataCredentialsFromPlugin.config_type
   */
  configType: {
    /**
     * @generated from field: google.protobuf.Struct config = 2 [deprecated = true];
     * @deprecated
     */
    value: JsonObject;
    case: "config";
  } | {
    /**
     * @generated from field: google.protobuf.Any typed_config = 3;
     */
    value: Any;
    case: "typedConfig";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.MetadataCredentialsFromPlugin.
 * Use `create(GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPluginSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPluginSchema: GenMessage<GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin>;

/**
 * Security token service configuration that allows Google gRPC to
 * fetch security token from an OAuth 2.0 authorization server.
 * See https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-16 and
 * https://github.com/grpc/grpc/pull/19587.
 * [#next-free-field: 10]
 *
 * @generated from message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.StsService
 */
export declare type GrpcService_GoogleGrpc_CallCredentials_StsService = Message<"envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.StsService"> & {
  /**
   * URI of the token exchange service that handles token exchange requests.
   * [#comment:TODO(asraa): Add URI validation when implemented. Tracked by
   * https://github.com/bufbuild/protoc-gen-validate/issues/303]
   *
   * @generated from field: string token_exchange_service_uri = 1;
   */
  tokenExchangeServiceUri: string;

  /**
   * Location of the target service or resource where the client
   * intends to use the requested security token.
   *
   * @generated from field: string resource = 2;
   */
  resource: string;

  /**
   * Logical name of the target service where the client intends to
   * use the requested security token.
   *
   * @generated from field: string audience = 3;
   */
  audience: string;

  /**
   * The desired scope of the requested security token in the
   * context of the service or resource where the token will be used.
   *
   * @generated from field: string scope = 4;
   */
  scope: string;

  /**
   * Type of the requested security token.
   *
   * @generated from field: string requested_token_type = 5;
   */
  requestedTokenType: string;

  /**
   * The path of subject token, a security token that represents the
   * identity of the party on behalf of whom the request is being made.
   *
   * @generated from field: string subject_token_path = 6;
   */
  subjectTokenPath: string;

  /**
   * Type of the subject token.
   *
   * @generated from field: string subject_token_type = 7;
   */
  subjectTokenType: string;

  /**
   * The path of actor token, a security token that represents the identity
   * of the acting party. The acting party is authorized to use the
   * requested security token and act on behalf of the subject.
   *
   * @generated from field: string actor_token_path = 8;
   */
  actorTokenPath: string;

  /**
   * Type of the actor token.
   *
   * @generated from field: string actor_token_type = 9;
   */
  actorTokenType: string;
};

/**
 * Describes the message envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.StsService.
 * Use `create(GrpcService_GoogleGrpc_CallCredentials_StsServiceSchema)` to create a new message.
 */
export declare const GrpcService_GoogleGrpc_CallCredentials_StsServiceSchema: GenMessage<GrpcService_GoogleGrpc_CallCredentials_StsService>;

