// @generated by protoc-gen-es v2.10.0
// @generated from file contrib/envoy/extensions/filters/http/language/v3alpha/language.proto (package envoy.extensions.filters.http.language.v3alpha, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../../../../validate/validate_pb";

/**
 * Describes the file contrib/envoy/extensions/filters/http/language/v3alpha/language.proto.
 */
export const file_contrib_envoy_extensions_filters_http_language_v3alpha_language = /*@__PURE__*/
  fileDesc("CkVjb250cmliL2Vudm95L2V4dGVuc2lvbnMvZmlsdGVycy9odHRwL2xhbmd1YWdlL3YzYWxwaGEvbGFuZ3VhZ2UucHJvdG8SLmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLmxhbmd1YWdlLnYzYWxwaGEidwoITGFuZ3VhZ2USIQoQZGVmYXVsdF9sYW5ndWFnZRgBIAEoCUIH+kIEcgIQAhItChNzdXBwb3J0ZWRfbGFuZ3VhZ2VzGAIgAygJQhD6Qg2SAQoIARgBIgRyAhACEhkKEWNsZWFyX3JvdXRlX2NhY2hlGAMgASgIQrYBCjxpby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLmxhbmd1YWdlLnYzYWxwaGFCDUxhbmd1YWdlUHJvdG9QAVpdZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvY29udHJpYi9lbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9sYW5ndWFnZS92M2FscGhhuoDI0QYCEAJiBnByb3RvMw", [file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.extensions.filters.http.language.v3alpha.Language.
 * Use `create(LanguageSchema)` to create a new message.
 */
export const LanguageSchema = /*@__PURE__*/
  messageDesc(file_contrib_envoy_extensions_filters_http_language_v3alpha_language, 0);

