// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/type/tracing/v3/custom_tag.proto (package envoy.type.tracing.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { MetadataKey, MetadataKind } from "../../metadata/v3/metadata_pb";

/**
 * Describes the file envoy/type/tracing/v3/custom_tag.proto.
 */
export declare const file_envoy_type_tracing_v3_custom_tag: GenFile;

/**
 * Describes custom tags for the active span.
 * [#next-free-field: 6]
 *
 * @generated from message envoy.type.tracing.v3.CustomTag
 */
export declare type CustomTag = Message<"envoy.type.tracing.v3.CustomTag"> & {
  /**
   * Used to populate the tag name.
   *
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * Used to specify what kind of custom tag.
   *
   * @generated from oneof envoy.type.tracing.v3.CustomTag.type
   */
  type: {
    /**
     * A literal custom tag.
     *
     * @generated from field: envoy.type.tracing.v3.CustomTag.Literal literal = 2;
     */
    value: CustomTag_Literal;
    case: "literal";
  } | {
    /**
     * An environment custom tag.
     *
     * @generated from field: envoy.type.tracing.v3.CustomTag.Environment environment = 3;
     */
    value: CustomTag_Environment;
    case: "environment";
  } | {
    /**
     * A request header custom tag.
     *
     * @generated from field: envoy.type.tracing.v3.CustomTag.Header request_header = 4;
     */
    value: CustomTag_Header;
    case: "requestHeader";
  } | {
    /**
     * A custom tag to obtain tag value from the metadata.
     *
     * @generated from field: envoy.type.tracing.v3.CustomTag.Metadata metadata = 5;
     */
    value: CustomTag_Metadata;
    case: "metadata";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.type.tracing.v3.CustomTag.
 * Use `create(CustomTagSchema)` to create a new message.
 */
export declare const CustomTagSchema: GenMessage<CustomTag>;

/**
 * Literal type custom tag with static value for the tag value.
 *
 * @generated from message envoy.type.tracing.v3.CustomTag.Literal
 */
export declare type CustomTag_Literal = Message<"envoy.type.tracing.v3.CustomTag.Literal"> & {
  /**
   * Static literal value to populate the tag value.
   *
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message envoy.type.tracing.v3.CustomTag.Literal.
 * Use `create(CustomTag_LiteralSchema)` to create a new message.
 */
export declare const CustomTag_LiteralSchema: GenMessage<CustomTag_Literal>;

/**
 * Environment type custom tag with environment name and default value.
 *
 * @generated from message envoy.type.tracing.v3.CustomTag.Environment
 */
export declare type CustomTag_Environment = Message<"envoy.type.tracing.v3.CustomTag.Environment"> & {
  /**
   * Environment variable name to obtain the value to populate the tag value.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * When the environment variable is not found,
   * the tag value will be populated with this default value if specified,
   * otherwise no tag will be populated.
   *
   * @generated from field: string default_value = 2;
   */
  defaultValue: string;
};

/**
 * Describes the message envoy.type.tracing.v3.CustomTag.Environment.
 * Use `create(CustomTag_EnvironmentSchema)` to create a new message.
 */
export declare const CustomTag_EnvironmentSchema: GenMessage<CustomTag_Environment>;

/**
 * Header type custom tag with header name and default value.
 *
 * @generated from message envoy.type.tracing.v3.CustomTag.Header
 */
export declare type CustomTag_Header = Message<"envoy.type.tracing.v3.CustomTag.Header"> & {
  /**
   * Header name to obtain the value to populate the tag value.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * When the header does not exist,
   * the tag value will be populated with this default value if specified,
   * otherwise no tag will be populated.
   *
   * @generated from field: string default_value = 2;
   */
  defaultValue: string;
};

/**
 * Describes the message envoy.type.tracing.v3.CustomTag.Header.
 * Use `create(CustomTag_HeaderSchema)` to create a new message.
 */
export declare const CustomTag_HeaderSchema: GenMessage<CustomTag_Header>;

/**
 * Metadata type custom tag using
 * :ref:`MetadataKey <envoy_v3_api_msg_type.metadata.v3.MetadataKey>` to retrieve the protobuf value
 * from :ref:`Metadata <envoy_v3_api_msg_config.core.v3.Metadata>`, and populate the tag value with
 * `the canonical JSON <https://developers.google.com/protocol-buffers/docs/proto3#json>`_
 * representation of it.
 *
 * @generated from message envoy.type.tracing.v3.CustomTag.Metadata
 */
export declare type CustomTag_Metadata = Message<"envoy.type.tracing.v3.CustomTag.Metadata"> & {
  /**
   * Specify what kind of metadata to obtain tag value from.
   *
   * @generated from field: envoy.type.metadata.v3.MetadataKind kind = 1;
   */
  kind?: MetadataKind;

  /**
   * Metadata key to define the path to retrieve the tag value.
   *
   * @generated from field: envoy.type.metadata.v3.MetadataKey metadata_key = 2;
   */
  metadataKey?: MetadataKey;

  /**
   * When no valid metadata is found,
   * the tag value would be populated with this default value if specified,
   * otherwise no tag would be populated.
   *
   * @generated from field: string default_value = 3;
   */
  defaultValue: string;
};

/**
 * Describes the message envoy.type.tracing.v3.CustomTag.Metadata.
 * Use `create(CustomTag_MetadataSchema)` to create a new message.
 */
export declare const CustomTag_MetadataSchema: GenMessage<CustomTag_Metadata>;

