// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/credential_injector/v3/credential_injector.proto (package envoy.extensions.filters.http.credential_injector.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_config_core_v3_extension } from "../../../../../config/core/v3/extension_pb";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/filters/http/credential_injector/v3/credential_injector.proto.
 */
export const file_envoy_extensions_filters_http_credential_injector_v3_credential_injector = /*@__PURE__*/
  fileDesc("Ck5lbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9jcmVkZW50aWFsX2luamVjdG9yL3YzL2NyZWRlbnRpYWxfaW5qZWN0b3IucHJvdG8SNGVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLmNyZWRlbnRpYWxfaW5qZWN0b3IudjMimwEKEkNyZWRlbnRpYWxJbmplY3RvchIRCglvdmVyd3JpdGUYASABKAgSKAogYWxsb3dfcmVxdWVzdF93aXRob3V0X2NyZWRlbnRpYWwYAiABKAgSSAoKY3JlZGVudGlhbBgDIAEoCzIqLmVudm95LmNvbmZpZy5jb3JlLnYzLlR5cGVkRXh0ZW5zaW9uQ29uZmlnQgj6QgWKAQIQAULaAQpCaW8uZW52b3lwcm94eS5lbnZveS5leHRlbnNpb25zLmZpbHRlcnMuaHR0cC5jcmVkZW50aWFsX2luamVjdG9yLnYzQhdDcmVkZW50aWFsSW5qZWN0b3JQcm90b1ABWnFnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9jcmVkZW50aWFsX2luamVjdG9yL3YzO2NyZWRlbnRpYWxfaW5qZWN0b3J2M7qAyNEGAhACYgZwcm90bzM", [file_envoy_config_core_v3_extension, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.extensions.filters.http.credential_injector.v3.CredentialInjector.
 * Use `create(CredentialInjectorSchema)` to create a new message.
 */
export const CredentialInjectorSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_credential_injector_v3_credential_injector, 0);

