// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/credential_injector/v3/credential_injector.proto (package envoy.extensions.filters.http.credential_injector.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { TypedExtensionConfig } from "../../../../../config/core/v3/extension_pb";

/**
 * Describes the file envoy/extensions/filters/http/credential_injector/v3/credential_injector.proto.
 */
export declare const file_envoy_extensions_filters_http_credential_injector_v3_credential_injector: GenFile;

/**
 * Credential Injector injects credentials into outgoing HTTP requests. The filter configuration is used to retrieve the credentials, or
 * they can be requested through the OAuth2 client credential grant. The credentials obtained are then injected into the Authorization header
 * of the proxied HTTP requests, utilizing either the Basic or Bearer scheme.
 *
 * If the credential is not present or there was a failure injecting the credential, the request will fail with ``401 Unauthorized`` unless
 * ``allow_request_without_credential`` is set to ``true``.
 *
 * Notice: This filter is intended to be used for workload authentication, which means that the identity associated with the inserted credential
 * is considered as the identity of the workload behind the envoy proxy(in this case, envoy is typically deployed as a sidecar alongside that
 * workload). Please note that this filter does not handle end user authentication. Its purpose is solely to authenticate the workload itself.
 *
 * Here is an example of CredentialInjector configuration with Generic credential, which injects an HTTP Basic Auth credential into the proxied requests.
 *
 * .. code-block:: yaml
 *
 *  overwrite: true
 *  credential:
 *    name: generic_credential
 *    typed_config:
 *      "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.generic.v3.Generic
 *      credential:
 *        name: credential
 *        sds_config:
 *          path_config_source:
 *            path: credential.yaml
 *      header: Authorization
 *
 * credential.yaml for Basic Auth:
 *
 * .. code-block:: yaml
 *
 *  resources:
 *  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
 *    name: credential
 *    generic_secret:
 *      secret:
 *        inline_string: "Basic base64EncodedUsernamePassword"
 *
 * It can also be configured to inject a Bearer token into the proxied requests.
 *
 * credential.yaml for Bearer Token:
 *
 * .. code-block:: yaml
 *
 *  resources:
 *  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
 *    name: credential
 *    generic_secret:
 *      secret:
 *        inline_string: "Bearer myToken"
 *
 *
 * @generated from message envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
 */
export declare type CredentialInjector = Message<"envoy.extensions.filters.http.credential_injector.v3.CredentialInjector"> & {
  /**
   * Whether to overwrite the value or not if the injected headers already exist.
   * Value defaults to false.
   *
   * @generated from field: bool overwrite = 1;
   */
  overwrite: boolean;

  /**
   * Whether to send the request to upstream if the credential is not present or if the credential injection
   * to the request fails.
   *
   * By default, a request will fail with ``401 Unauthorized`` if the
   * credential is not present or the injection of the credential to the request fails.
   * If set to true, the request will be sent to upstream without the credential.
   *
   * @generated from field: bool allow_request_without_credential = 2;
   */
  allowRequestWithoutCredential: boolean;

  /**
   * The credential to inject into the proxied requests
   * [#extension-category: envoy.http.injected_credentials]
   *
   * @generated from field: envoy.config.core.v3.TypedExtensionConfig credential = 3;
   */
  credential?: TypedExtensionConfig;
};

/**
 * Describes the message envoy.extensions.filters.http.credential_injector.v3.CredentialInjector.
 * Use `create(CredentialInjectorSchema)` to create a new message.
 */
export declare const CredentialInjectorSchema: GenMessage<CredentialInjector>;

