// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/early_data/v3/default_early_data_policy.proto (package envoy.extensions.early_data.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/extensions/early_data/v3/default_early_data_policy.proto.
 */
export const file_envoy_extensions_early_data_v3_default_early_data_policy = /*@__PURE__*/
  fileDesc("Cj5lbnZveS9leHRlbnNpb25zL2Vhcmx5X2RhdGEvdjMvZGVmYXVsdF9lYXJseV9kYXRhX3BvbGljeS5wcm90bxIeZW52b3kuZXh0ZW5zaW9ucy5lYXJseV9kYXRhLnYzIhgKFkRlZmF1bHRFYXJseURhdGFQb2xpY3lCqQEKLGlvLmVudm95cHJveHkuZW52b3kuZXh0ZW5zaW9ucy5lYXJseV9kYXRhLnYzQhtEZWZhdWx0RWFybHlEYXRhUG9saWN5UHJvdG9QAVpSZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9lYXJseV9kYXRhL3YzO2Vhcmx5X2RhdGF2M7qAyNEGAhACYgZwcm90bzM", [file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.early_data.v3.DefaultEarlyDataPolicy.
 * Use `create(DefaultEarlyDataPolicySchema)` to create a new message.
 */
export const DefaultEarlyDataPolicySchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_early_data_v3_default_early_data_policy, 0);

