// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/filter/http/grpc_http1_bridge/v2/config.proto (package envoy.config.filter.http.grpc_http1_bridge.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/config/filter/http/grpc_http1_bridge/v2/config.proto.
 */
export declare const file_envoy_config_filter_http_grpc_http1_bridge_v2_config: GenFile;

/**
 * gRPC HTTP/1.1 Bridge filter config.
 *
 * @generated from message envoy.config.filter.http.grpc_http1_bridge.v2.Config
 */
export declare type Config = Message<"envoy.config.filter.http.grpc_http1_bridge.v2.Config"> & {
};

/**
 * Describes the message envoy.config.filter.http.grpc_http1_bridge.v2.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export declare const ConfigSchema: GenMessage<Config>;

