// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/upstreams/tcp/generic/v3/generic_connection_pool.proto (package envoy.extensions.upstreams.tcp.generic.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/extensions/upstreams/tcp/generic/v3/generic_connection_pool.proto.
 */
export const file_envoy_extensions_upstreams_tcp_generic_v3_generic_connection_pool = /*@__PURE__*/
  fileDesc("CkdlbnZveS9leHRlbnNpb25zL3Vwc3RyZWFtcy90Y3AvZ2VuZXJpYy92My9nZW5lcmljX2Nvbm5lY3Rpb25fcG9vbC5wcm90bxIpZW52b3kuZXh0ZW5zaW9ucy51cHN0cmVhbXMudGNwLmdlbmVyaWMudjMiHAoaR2VuZXJpY0Nvbm5lY3Rpb25Qb29sUHJvdG9CxQEKN2lvLmVudm95cHJveHkuZW52b3kuZXh0ZW5zaW9ucy51cHN0cmVhbXMudGNwLmdlbmVyaWMudjNCJEdlbmVyaWNDb25uZWN0aW9uUG9vbFByb3RvT3V0ZXJDbGFzc1ABWlpnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9leHRlbnNpb25zL3Vwc3RyZWFtcy90Y3AvZ2VuZXJpYy92MztnZW5lcmljdjO6gMjRBgIQAmIGcHJvdG8z", [file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.upstreams.tcp.generic.v3.GenericConnectionPoolProto.
 * Use `create(GenericConnectionPoolProtoSchema)` to create a new message.
 */
export const GenericConnectionPoolProtoSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_upstreams_tcp_generic_v3_generic_connection_pool, 0);

