// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/grpc_field_extraction/v3/config.proto (package envoy.extensions.filters.http.grpc_field_extraction.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DataSource } from "../../../../../config/core/v3/base_pb";

/**
 * Describes the file envoy/extensions/filters/http/grpc_field_extraction/v3/config.proto.
 */
export declare const file_envoy_extensions_filters_http_grpc_field_extraction_v3_config: GenFile;

/**
 * @generated from message envoy.extensions.filters.http.grpc_field_extraction.v3.GrpcFieldExtractionConfig
 */
export declare type GrpcFieldExtractionConfig = Message<"envoy.extensions.filters.http.grpc_field_extraction.v3.GrpcFieldExtractionConfig"> & {
  /**
   * The proto descriptor set binary for the gRPC services.
   *
   * It could be passed by a local file through ``Datasource.filename`` or embedded in the
   * ``Datasource.inline_bytes``.
   *
   * @generated from field: envoy.config.core.v3.DataSource descriptor_set = 1;
   */
  descriptorSet?: DataSource;

  /**
   * Specify the extraction info.
   * The key is the fully qualified gRPC method name.
   * ``${package}.${Service}.${Method}``, like
   * ``endpoints.examples.bookstore.BookStore.GetShelf``
   *
   * The value is the field extractions for individual gRPC method.
   *
   * @generated from field: map<string, envoy.extensions.filters.http.grpc_field_extraction.v3.FieldExtractions> extractions_by_method = 2;
   */
  extractionsByMethod: { [key: string]: FieldExtractions };
};

/**
 * Describes the message envoy.extensions.filters.http.grpc_field_extraction.v3.GrpcFieldExtractionConfig.
 * Use `create(GrpcFieldExtractionConfigSchema)` to create a new message.
 */
export declare const GrpcFieldExtractionConfigSchema: GenMessage<GrpcFieldExtractionConfig>;

/**
 * This message can be used to support per route config approach later even
 * though the Istio doesn't support that so far.
 *
 * @generated from message envoy.extensions.filters.http.grpc_field_extraction.v3.FieldExtractions
 */
export declare type FieldExtractions = Message<"envoy.extensions.filters.http.grpc_field_extraction.v3.FieldExtractions"> & {
  /**
   * The field extractions for requests.
   * The key is the field path within the grpc request.
   * For example, we can define ``foo.bar.name`` if we want to extract
   * ``Request.foo.bar.name``.
   *
   * .. code-block:: proto
   *
   *  message Request {
   *    Foo foo = 1;
   *  }
   *
   *  message Foo {
   *    Bar bar = 1;
   *  }
   *
   *  message Bar {
   *    string name = 1;
   *  }
   *
   * @generated from field: map<string, envoy.extensions.filters.http.grpc_field_extraction.v3.RequestFieldValueDisposition> request_field_extractions = 1;
   */
  requestFieldExtractions: { [key: string]: RequestFieldValueDisposition };
};

/**
 * Describes the message envoy.extensions.filters.http.grpc_field_extraction.v3.FieldExtractions.
 * Use `create(FieldExtractionsSchema)` to create a new message.
 */
export declare const FieldExtractionsSchema: GenMessage<FieldExtractions>;

/**
 * @generated from message envoy.extensions.filters.http.grpc_field_extraction.v3.RequestFieldValueDisposition
 */
export declare type RequestFieldValueDisposition = Message<"envoy.extensions.filters.http.grpc_field_extraction.v3.RequestFieldValueDisposition"> & {
  /**
   * @generated from oneof envoy.extensions.filters.http.grpc_field_extraction.v3.RequestFieldValueDisposition.disposition
   */
  disposition: {
    /**
     * The dynamic metadata namespace. If empty, "envoy.filters.http.grpc_field_extraction" will be used by default.
     *
     * Unimplemented. Uses "envoy.filters.http.grpc_field_extraction" for now.
     *
     * @generated from field: string dynamic_metadata = 1;
     */
    value: string;
    case: "dynamicMetadata";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.extensions.filters.http.grpc_field_extraction.v3.RequestFieldValueDisposition.
 * Use `create(RequestFieldValueDispositionSchema)` to create a new message.
 */
export declare const RequestFieldValueDispositionSchema: GenMessage<RequestFieldValueDisposition>;

