// THIS FILE IS DEPRECATED
// Users should instead use the corresponding proto in the xds tree.
// No new changes will be accepted here.

// @generated by protoc-gen-es v2.10.0
// @generated from file udpa/service/orca/v1/orca.proto (package udpa.service.orca.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_data_orca_v1_orca_load_report } from "../../../data/orca/v1/orca_load_report_pb";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file udpa/service/orca/v1/orca.proto.
 */
export const file_udpa_service_orca_v1_orca = /*@__PURE__*/
  fileDesc("Ch91ZHBhL3NlcnZpY2Uvb3JjYS92MS9vcmNhLnByb3RvEhR1ZHBhLnNlcnZpY2Uub3JjYS52MSJnChVPcmNhTG9hZFJlcG9ydFJlcXVlc3QSMgoPcmVwb3J0X2ludGVydmFsGAEgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uEhoKEnJlcXVlc3RfY29zdF9uYW1lcxgCIAMoCTJ3Cg5PcGVuUmNhU2VydmljZRJlChFTdHJlYW1Db3JlTWV0cmljcxIrLnVkcGEuc2VydmljZS5vcmNhLnYxLk9yY2FMb2FkUmVwb3J0UmVxdWVzdBohLnVkcGEuZGF0YS5vcmNhLnYxLk9yY2FMb2FkUmVwb3J0MAFCYAokY29tLmdpdGh1Yi51ZHBhLnVkcGEuc2VydmljZS5vcmNhLnYxQglPcmNhUHJvdG9QAVorZ2l0aHViLmNvbS9jbmNmL3hkcy9nby91ZHBhL3NlcnZpY2Uvb3JjYS92MWIGcHJvdG8z", [file_udpa_data_orca_v1_orca_load_report, file_google_protobuf_duration]);

/**
 * Describes the message udpa.service.orca.v1.OrcaLoadReportRequest.
 * Use `create(OrcaLoadReportRequestSchema)` to create a new message.
 */
export const OrcaLoadReportRequestSchema = /*@__PURE__*/
  messageDesc(file_udpa_service_orca_v1_orca, 0);

/**
 * Out-of-band (OOB) load reporting service for the additional load reporting
 * agent that does not sit in the request path. Reports are periodically sampled
 * with sufficient frequency to provide temporal association with requests.
 * OOB reporting compensates the limitation of in-band reporting in revealing
 * costs for backends that do not provide a steady stream of telemetry such as
 * long running stream operations and zero QPS services. This is a server
 * streaming service, client needs to terminate current RPC and initiate
 * a new call to change backend reporting frequency.
 *
 * @generated from service udpa.service.orca.v1.OpenRcaService
 */
export const OpenRcaService = /*@__PURE__*/
  serviceDesc(file_udpa_service_orca_v1_orca, 0);

