// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/filter/network/dubbo_proxy/v2alpha1/dubbo_proxy.proto (package envoy.config.filter.network.dubbo_proxy.v2alpha1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { RouteConfiguration } from "./route_pb";
import type { Any } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file envoy/config/filter/network/dubbo_proxy/v2alpha1/dubbo_proxy.proto.
 */
export declare const file_envoy_config_filter_network_dubbo_proxy_v2alpha1_dubbo_proxy: GenFile;

/**
 * [#next-free-field: 6]
 *
 * @generated from message envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy
 */
export declare type DubboProxy = Message<"envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy"> & {
  /**
   * The human readable prefix to use when emitting statistics.
   *
   * @generated from field: string stat_prefix = 1;
   */
  statPrefix: string;

  /**
   * Configure the protocol used.
   *
   * @generated from field: envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType protocol_type = 2;
   */
  protocolType: ProtocolType;

  /**
   * Configure the serialization protocol used.
   *
   * @generated from field: envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType serialization_type = 3;
   */
  serializationType: SerializationType;

  /**
   * The route table for the connection manager is static and is specified in this property.
   *
   * @generated from field: repeated envoy.config.filter.network.dubbo_proxy.v2alpha1.RouteConfiguration route_config = 4;
   */
  routeConfig: RouteConfiguration[];

  /**
   * A list of individual Dubbo filters that make up the filter chain for requests made to the
   * Dubbo proxy. Order matters as the filters are processed sequentially. For backwards
   * compatibility, if no dubbo_filters are specified, a default Dubbo router filter
   * (`envoy.filters.dubbo.router`) is used.
   *
   * @generated from field: repeated envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter dubbo_filters = 5;
   */
  dubboFilters: DubboFilter[];
};

/**
 * Describes the message envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboProxy.
 * Use `create(DubboProxySchema)` to create a new message.
 */
export declare const DubboProxySchema: GenMessage<DubboProxy>;

/**
 * DubboFilter configures a Dubbo filter.
 *
 * @generated from message envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter
 */
export declare type DubboFilter = Message<"envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter"> & {
  /**
   * The name of the filter to instantiate. The name must match a supported
   * filter.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Filter specific configuration which depends on the filter being
   * instantiated. See the supported filters for further documentation.
   *
   * @generated from field: google.protobuf.Any config = 2;
   */
  config?: Any;
};

/**
 * Describes the message envoy.config.filter.network.dubbo_proxy.v2alpha1.DubboFilter.
 * Use `create(DubboFilterSchema)` to create a new message.
 */
export declare const DubboFilterSchema: GenMessage<DubboFilter>;

/**
 * Dubbo Protocol types supported by Envoy.
 *
 * @generated from enum envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType
 */
export enum ProtocolType {
  /**
   * the default protocol.
   *
   * @generated from enum value: Dubbo = 0;
   */
  Dubbo = 0,
}

/**
 * Describes the enum envoy.config.filter.network.dubbo_proxy.v2alpha1.ProtocolType.
 */
export declare const ProtocolTypeSchema: GenEnum<ProtocolType>;

/**
 * Dubbo Serialization types supported by Envoy.
 *
 * @generated from enum envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType
 */
export enum SerializationType {
  /**
   * the default serialization protocol.
   *
   * @generated from enum value: Hessian2 = 0;
   */
  Hessian2 = 0,
}

/**
 * Describes the enum envoy.config.filter.network.dubbo_proxy.v2alpha1.SerializationType.
 */
export declare const SerializationTypeSchema: GenEnum<SerializationType>;

