// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/retry/previous_priorities/previous_priorities_config.proto (package envoy.config.retry.previous_priorities, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_migrate } from "../../../../udpa/annotations/migrate_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../validate/validate_pb";

/**
 * Describes the file envoy/config/retry/previous_priorities/previous_priorities_config.proto.
 */
export const file_envoy_config_retry_previous_priorities_previous_priorities_config = /*@__PURE__*/
  fileDesc("CkdlbnZveS9jb25maWcvcmV0cnkvcHJldmlvdXNfcHJpb3JpdGllcy9wcmV2aW91c19wcmlvcml0aWVzX2NvbmZpZy5wcm90bxImZW52b3kuY29uZmlnLnJldHJ5LnByZXZpb3VzX3ByaW9yaXRpZXMiPQoYUHJldmlvdXNQcmlvcml0aWVzQ29uZmlnEiEKEHVwZGF0ZV9mcmVxdWVuY3kYASABKAVCB/pCBBoCIABC7AEKNGlvLmVudm95cHJveHkuZW52b3kuY29uZmlnLnJldHJ5LnByZXZpb3VzX3ByaW9yaXRpZXNCHVByZXZpb3VzUHJpb3JpdGllc0NvbmZpZ1Byb3RvUAFaTWdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2NvbmZpZy9yZXRyeS9wcmV2aW91c19wcmlvcml0aWVz8pj+jwU4EjZlbnZveS5leHRlbnNpb25zLnJldHJ5LnByaW9yaXR5LnByZXZpb3VzX3ByaW9yaXRpZXMudjO6gMjRBgIQAWIGcHJvdG8z", [file_udpa_annotations_migrate, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.config.retry.previous_priorities.PreviousPrioritiesConfig.
 * Use `create(PreviousPrioritiesConfigSchema)` to create a new message.
 */
export const PreviousPrioritiesConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_config_retry_previous_priorities_previous_priorities_config, 0);

