// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/set_filter_state/v3/set_filter_state.proto (package envoy.extensions.filters.http.set_filter_state.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_extensions_filters_common_set_filter_state_v3_value } from "../../../common/set_filter_state/v3/value_pb";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/extensions/filters/http/set_filter_state/v3/set_filter_state.proto.
 */
export const file_envoy_extensions_filters_http_set_filter_state_v3_set_filter_state = /*@__PURE__*/
  fileDesc("CkhlbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9zZXRfZmlsdGVyX3N0YXRlL3YzL3NldF9maWx0ZXJfc3RhdGUucHJvdG8SMWVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLnNldF9maWx0ZXJfc3RhdGUudjMiawoGQ29uZmlnEmEKEm9uX3JlcXVlc3RfaGVhZGVycxgBIAMoCzJFLmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5jb21tb24uc2V0X2ZpbHRlcl9zdGF0ZS52My5GaWx0ZXJTdGF0ZVZhbHVlQs0BCj9pby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLnNldF9maWx0ZXJfc3RhdGUudjNCE1NldEZpbHRlclN0YXRlUHJvdG9QAVprZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9maWx0ZXJzL2h0dHAvc2V0X2ZpbHRlcl9zdGF0ZS92MztzZXRfZmlsdGVyX3N0YXRldjO6gMjRBgIQAmIGcHJvdG8z", [file_envoy_extensions_filters_common_set_filter_state_v3_value, file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.filters.http.set_filter_state.v3.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export const ConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_set_filter_state_v3_set_filter_state, 0);

