// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/service/load_stats/v2/lrs.proto (package envoy.service.load_stats.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_api_v2_core_base } from "../../../api/v2/core/base_pb";
import { file_envoy_api_v2_endpoint_load_report } from "../../../api/v2/endpoint/load_report_pb";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/service/load_stats/v2/lrs.proto.
 */
export const file_envoy_service_load_stats_v2_lrs = /*@__PURE__*/
  fileDesc("CiVlbnZveS9zZXJ2aWNlL2xvYWRfc3RhdHMvdjIvbHJzLnByb3RvEhtlbnZveS5zZXJ2aWNlLmxvYWRfc3RhdHMudjIidQoQTG9hZFN0YXRzUmVxdWVzdBIlCgRub2RlGAEgASgLMhcuZW52b3kuYXBpLnYyLmNvcmUuTm9kZRI6Cg1jbHVzdGVyX3N0YXRzGAIgAygLMiMuZW52b3kuYXBpLnYyLmVuZHBvaW50LkNsdXN0ZXJTdGF0cyKhAQoRTG9hZFN0YXRzUmVzcG9uc2USEAoIY2x1c3RlcnMYASADKAkSGQoRc2VuZF9hbGxfY2x1c3RlcnMYBCABKAgSOgoXbG9hZF9yZXBvcnRpbmdfaW50ZXJ2YWwYAiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SIwobcmVwb3J0X2VuZHBvaW50X2dyYW51bGFyaXR5GAMgASgIMo4BChRMb2FkUmVwb3J0aW5nU2VydmljZRJ2Cg9TdHJlYW1Mb2FkU3RhdHMSLS5lbnZveS5zZXJ2aWNlLmxvYWRfc3RhdHMudjIuTG9hZFN0YXRzUmVxdWVzdBouLmVudm95LnNlcnZpY2UubG9hZF9zdGF0cy52Mi5Mb2FkU3RhdHNSZXNwb25zZSIAKAEwAUKQAQopaW8uZW52b3lwcm94eS5lbnZveS5zZXJ2aWNlLmxvYWRfc3RhdHMudjJCCExyc1Byb3RvUAFaT2dpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L3NlcnZpY2UvbG9hZF9zdGF0cy92Mjtsb2FkX3N0YXRzdjK6gMjRBgIQAWIGcHJvdG8z", [file_envoy_api_v2_core_base, file_envoy_api_v2_endpoint_load_report, file_google_protobuf_duration, file_udpa_annotations_status]);

/**
 * Describes the message envoy.service.load_stats.v2.LoadStatsRequest.
 * Use `create(LoadStatsRequestSchema)` to create a new message.
 */
export const LoadStatsRequestSchema = /*@__PURE__*/
  messageDesc(file_envoy_service_load_stats_v2_lrs, 0);

/**
 * Describes the message envoy.service.load_stats.v2.LoadStatsResponse.
 * Use `create(LoadStatsResponseSchema)` to create a new message.
 */
export const LoadStatsResponseSchema = /*@__PURE__*/
  messageDesc(file_envoy_service_load_stats_v2_lrs, 1);

/**
 * @generated from service envoy.service.load_stats.v2.LoadReportingService
 */
export const LoadReportingService = /*@__PURE__*/
  serviceDesc(file_envoy_service_load_stats_v2_lrs, 0);

