// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/service/accesslog/v2/als.proto (package envoy.service.accesslog.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_api_v2_core_base } from "../../../api/v2/core/base_pb";
import { file_envoy_data_accesslog_v2_accesslog } from "../../../data/accesslog/v2/accesslog_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../validate/validate_pb";

/**
 * Describes the file envoy/service/accesslog/v2/als.proto.
 */
export const file_envoy_service_accesslog_v2_als = /*@__PURE__*/
  fileDesc("CiRlbnZveS9zZXJ2aWNlL2FjY2Vzc2xvZy92Mi9hbHMucHJvdG8SGmVudm95LnNlcnZpY2UuYWNjZXNzbG9nLnYyIhoKGFN0cmVhbUFjY2Vzc0xvZ3NSZXNwb25zZSLZBAoXU3RyZWFtQWNjZXNzTG9nc01lc3NhZ2USUgoKaWRlbnRpZmllchgBIAEoCzI+LmVudm95LnNlcnZpY2UuYWNjZXNzbG9nLnYyLlN0cmVhbUFjY2Vzc0xvZ3NNZXNzYWdlLklkZW50aWZpZXISXQoJaHR0cF9sb2dzGAIgASgLMkguZW52b3kuc2VydmljZS5hY2Nlc3Nsb2cudjIuU3RyZWFtQWNjZXNzTG9nc01lc3NhZ2UuSFRUUEFjY2Vzc0xvZ0VudHJpZXNIABJbCgh0Y3BfbG9ncxgDIAEoCzJHLmVudm95LnNlcnZpY2UuYWNjZXNzbG9nLnYyLlN0cmVhbUFjY2Vzc0xvZ3NNZXNzYWdlLlRDUEFjY2Vzc0xvZ0VudHJpZXNIABpYCgpJZGVudGlmaWVyEi8KBG5vZGUYASABKAsyFy5lbnZveS5hcGkudjIuY29yZS5Ob2RlQgj6QgWKAQIQARIZCghsb2dfbmFtZRgCIAEoCUIH+kIEcgIgARpgChRIVFRQQWNjZXNzTG9nRW50cmllcxJICglsb2dfZW50cnkYASADKAsyKy5lbnZveS5kYXRhLmFjY2Vzc2xvZy52Mi5IVFRQQWNjZXNzTG9nRW50cnlCCPpCBZIBAggBGl4KE1RDUEFjY2Vzc0xvZ0VudHJpZXMSRwoJbG9nX2VudHJ5GAEgAygLMiouZW52b3kuZGF0YS5hY2Nlc3Nsb2cudjIuVENQQWNjZXNzTG9nRW50cnlCCPpCBZIBAggBQhIKC2xvZ19lbnRyaWVzEgP4QgEylgEKEEFjY2Vzc0xvZ1NlcnZpY2USgQEKEFN0cmVhbUFjY2Vzc0xvZ3MSMy5lbnZveS5zZXJ2aWNlLmFjY2Vzc2xvZy52Mi5TdHJlYW1BY2Nlc3NMb2dzTWVzc2FnZRo0LmVudm95LnNlcnZpY2UuYWNjZXNzbG9nLnYyLlN0cmVhbUFjY2Vzc0xvZ3NSZXNwb25zZSIAKAFCjQEKKGlvLmVudm95cHJveHkuZW52b3kuc2VydmljZS5hY2Nlc3Nsb2cudjJCCEFsc1Byb3RvUAFaTWdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L3NlcnZpY2UvYWNjZXNzbG9nL3YyO2FjY2Vzc2xvZ3YyuoDI0QYCEAFiBnByb3RvMw", [file_envoy_api_v2_core_base, file_envoy_data_accesslog_v2_accesslog, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.service.accesslog.v2.StreamAccessLogsResponse.
 * Use `create(StreamAccessLogsResponseSchema)` to create a new message.
 */
export const StreamAccessLogsResponseSchema = /*@__PURE__*/
  messageDesc(file_envoy_service_accesslog_v2_als, 0);

/**
 * Describes the message envoy.service.accesslog.v2.StreamAccessLogsMessage.
 * Use `create(StreamAccessLogsMessageSchema)` to create a new message.
 */
export const StreamAccessLogsMessageSchema = /*@__PURE__*/
  messageDesc(file_envoy_service_accesslog_v2_als, 1);

/**
 * Describes the message envoy.service.accesslog.v2.StreamAccessLogsMessage.Identifier.
 * Use `create(StreamAccessLogsMessage_IdentifierSchema)` to create a new message.
 */
export const StreamAccessLogsMessage_IdentifierSchema = /*@__PURE__*/
  messageDesc(file_envoy_service_accesslog_v2_als, 1, 0);

/**
 * Describes the message envoy.service.accesslog.v2.StreamAccessLogsMessage.HTTPAccessLogEntries.
 * Use `create(StreamAccessLogsMessage_HTTPAccessLogEntriesSchema)` to create a new message.
 */
export const StreamAccessLogsMessage_HTTPAccessLogEntriesSchema = /*@__PURE__*/
  messageDesc(file_envoy_service_accesslog_v2_als, 1, 1);

/**
 * Describes the message envoy.service.accesslog.v2.StreamAccessLogsMessage.TCPAccessLogEntries.
 * Use `create(StreamAccessLogsMessage_TCPAccessLogEntriesSchema)` to create a new message.
 */
export const StreamAccessLogsMessage_TCPAccessLogEntriesSchema = /*@__PURE__*/
  messageDesc(file_envoy_service_accesslog_v2_als, 1, 2);

/**
 * Service for streaming access logs from Envoy to an access log server.
 *
 * @generated from service envoy.service.accesslog.v2.AccessLogService
 */
export const AccessLogService = /*@__PURE__*/
  serviceDesc(file_envoy_service_accesslog_v2_als, 0);

