// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/service/auth/v2alpha/external_auth.proto (package envoy.service.auth.v2alpha, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import type { CheckRequestSchema, CheckResponseSchema } from "../v2/external_auth_pb";

/**
 * Describes the file envoy/service/auth/v2alpha/external_auth.proto.
 */
export declare const file_envoy_service_auth_v2alpha_external_auth: GenFile;

/**
 * A generic interface for performing authorization check on incoming
 * requests to a networked service.
 *
 * @generated from service envoy.service.auth.v2alpha.Authorization
 */
export declare const Authorization: GenService<{
  /**
   * Performs authorization check based on the attributes associated with the
   * incoming request, and returns status `OK` or not `OK`.
   *
   * @generated from rpc envoy.service.auth.v2alpha.Authorization.Check
   */
  check: {
    methodKind: "unary";
    input: typeof CheckRequestSchema;
    output: typeof CheckResponseSchema;
  },
}>;

