// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/api/v2/cluster/circuit_breaker.proto (package envoy.api.v2.cluster, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_api_v2_core_base } from "../core/base_pb";
import { file_envoy_type_percent } from "../../../type/percent_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_migrate } from "../../../../udpa/annotations/migrate_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../validate/validate_pb";

/**
 * Describes the file envoy/api/v2/cluster/circuit_breaker.proto.
 */
export const file_envoy_api_v2_cluster_circuit_breaker = /*@__PURE__*/
  fileDesc("CiplbnZveS9hcGkvdjIvY2x1c3Rlci9jaXJjdWl0X2JyZWFrZXIucHJvdG8SFGVudm95LmFwaS52Mi5jbHVzdGVyIqIFCg9DaXJjdWl0QnJlYWtlcnMSRAoKdGhyZXNob2xkcxgBIAMoCzIwLmVudm95LmFwaS52Mi5jbHVzdGVyLkNpcmN1aXRCcmVha2Vycy5UaHJlc2hvbGRzGsgECgpUaHJlc2hvbGRzEj4KCHByaW9yaXR5GAEgASgOMiIuZW52b3kuYXBpLnYyLmNvcmUuUm91dGluZ1ByaW9yaXR5Qgj6QgWCAQIQARI1Cg9tYXhfY29ubmVjdGlvbnMYAiABKAsyHC5nb29nbGUucHJvdG9idWYuVUludDMyVmFsdWUSOgoUbWF4X3BlbmRpbmdfcmVxdWVzdHMYAyABKAsyHC5nb29nbGUucHJvdG9idWYuVUludDMyVmFsdWUSMgoMbWF4X3JlcXVlc3RzGAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlVJbnQzMlZhbHVlEjEKC21heF9yZXRyaWVzGAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlVJbnQzMlZhbHVlElIKDHJldHJ5X2J1ZGdldBgIIAEoCzI8LmVudm95LmFwaS52Mi5jbHVzdGVyLkNpcmN1aXRCcmVha2Vycy5UaHJlc2hvbGRzLlJldHJ5QnVkZ2V0EhcKD3RyYWNrX3JlbWFpbmluZxgGIAEoCBI6ChRtYXhfY29ubmVjdGlvbl9wb29scxgHIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5VSW50MzJWYWx1ZRp3CgtSZXRyeUJ1ZGdldBIrCg5idWRnZXRfcGVyY2VudBgBIAEoCzITLmVudm95LnR5cGUuUGVyY2VudBI7ChVtaW5fcmV0cnlfY29uY3VycmVuY3kYAiABKAsyHC5nb29nbGUucHJvdG9idWYuVUludDMyVmFsdWVC1AEKImlvLmVudm95cHJveHkuZW52b3kuYXBpLnYyLmNsdXN0ZXJCE0NpcmN1aXRCcmVha2VyUHJvdG9QAVo7Z2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvYXBpL3YyL2NsdXN0ZXKqAhZFbnZveS5BcGkuVjIuQ2x1c3Rlck5T6gIZRW52b3k6OkFwaTo6VjI6OkNsdXN0ZXJOU/KY/o8FGRIXZW52b3kuY29uZmlnLmNsdXN0ZXIudjO6gMjRBgIQAWIGcHJvdG8z", [file_envoy_api_v2_core_base, file_envoy_type_percent, file_google_protobuf_wrappers, file_udpa_annotations_migrate, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.api.v2.cluster.CircuitBreakers.
 * Use `create(CircuitBreakersSchema)` to create a new message.
 */
export const CircuitBreakersSchema = /*@__PURE__*/
  messageDesc(file_envoy_api_v2_cluster_circuit_breaker, 0);

/**
 * Describes the message envoy.api.v2.cluster.CircuitBreakers.Thresholds.
 * Use `create(CircuitBreakers_ThresholdsSchema)` to create a new message.
 */
export const CircuitBreakers_ThresholdsSchema = /*@__PURE__*/
  messageDesc(file_envoy_api_v2_cluster_circuit_breaker, 0, 0);

/**
 * Describes the message envoy.api.v2.cluster.CircuitBreakers.Thresholds.RetryBudget.
 * Use `create(CircuitBreakers_Thresholds_RetryBudgetSchema)` to create a new message.
 */
export const CircuitBreakers_Thresholds_RetryBudgetSchema = /*@__PURE__*/
  messageDesc(file_envoy_api_v2_cluster_circuit_breaker, 0, 0, 0);

