// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/quic/proof_source/v3/proof_source.proto (package envoy.extensions.quic.proof_source.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/extensions/quic/proof_source/v3/proof_source.proto.
 */
export const file_envoy_extensions_quic_proof_source_v3_proof_source = /*@__PURE__*/
  fileDesc("CjhlbnZveS9leHRlbnNpb25zL3F1aWMvcHJvb2Zfc291cmNlL3YzL3Byb29mX3NvdXJjZS5wcm90bxIlZW52b3kuZXh0ZW5zaW9ucy5xdWljLnByb29mX3NvdXJjZS52MyITChFQcm9vZlNvdXJjZUNvbmZpZ0KuAQozaW8uZW52b3lwcm94eS5lbnZveS5leHRlbnNpb25zLnF1aWMucHJvb2Zfc291cmNlLnYzQhBQcm9vZlNvdXJjZVByb3RvUAFaW2dpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2V4dGVuc2lvbnMvcXVpYy9wcm9vZl9zb3VyY2UvdjM7cHJvb2Zfc291cmNldjO6gMjRBgIQAmIGcHJvdG8z", [file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.quic.proof_source.v3.ProofSourceConfig.
 * Use `create(ProofSourceConfigSchema)` to create a new message.
 */
export const ProofSourceConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_quic_proof_source_v3_proof_source, 0);

