// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/rbac/v3/rbac.proto (package envoy.extensions.filters.http.rbac.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_config_rbac_v3_rbac } from "../../../../../config/rbac/v3/rbac_pb";
import { file_xds_annotations_v3_status } from "../../../../../../xds/annotations/v3/status_pb";
import { file_xds_type_matcher_v3_matcher } from "../../../../../../xds/type/matcher/v3/matcher_pb";
import { file_udpa_annotations_migrate } from "../../../../../../udpa/annotations/migrate_pb";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../../../udpa/annotations/versioning_pb";

/**
 * Describes the file envoy/extensions/filters/http/rbac/v3/rbac.proto.
 */
export const file_envoy_extensions_filters_http_rbac_v3_rbac = /*@__PURE__*/
  fileDesc("CjBlbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9yYmFjL3YzL3JiYWMucHJvdG8SJWVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLnJiYWMudjMiywMKBFJCQUMSQgoFcnVsZXMYASABKAsyGi5lbnZveS5jb25maWcucmJhYy52My5SQkFDQhfymP6PBRESD3J1bGVzX3NwZWNpZmllchIZChFydWxlc19zdGF0X3ByZWZpeBgGIAEoCRJGCgdtYXRjaGVyGAQgASgLMhwueGRzLnR5cGUubWF0Y2hlci52My5NYXRjaGVyQhfymP6PBRESD3J1bGVzX3NwZWNpZmllchJQCgxzaGFkb3dfcnVsZXMYAiABKAsyGi5lbnZveS5jb25maWcucmJhYy52My5SQkFDQh7ymP6PBRgSFnNoYWRvd19ydWxlc19zcGVjaWZpZXISXAoOc2hhZG93X21hdGNoZXIYBSABKAsyHC54ZHMudHlwZS5tYXRjaGVyLnYzLk1hdGNoZXJCJvKY/o8FGBIWc2hhZG93X3J1bGVzX3NwZWNpZmllctLGpOEGAggBEiAKGHNoYWRvd19ydWxlc19zdGF0X3ByZWZpeBgDIAEoCRIcChR0cmFja19wZXJfcnVsZV9zdGF0cxgHIAEoCDosmsWIHicKJWVudm95LmNvbmZpZy5maWx0ZXIuaHR0cC5yYmFjLnYyLlJCQUMihQEKDFJCQUNQZXJSb3V0ZRI5CgRyYmFjGAIgASgLMisuZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAucmJhYy52My5SQkFDOjSaxYgeLwotZW52b3kuY29uZmlnLmZpbHRlci5odHRwLnJiYWMudjIuUkJBQ1BlclJvdXRlSgQIARACQp8BCjNpby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLnJiYWMudjNCCVJiYWNQcm90b1ABWlNnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9yYmFjL3YzO3JiYWN2M7qAyNEGAhACYgZwcm90bzM", [file_envoy_config_rbac_v3_rbac, file_xds_annotations_v3_status, file_xds_type_matcher_v3_matcher, file_udpa_annotations_migrate, file_udpa_annotations_status, file_udpa_annotations_versioning]);

/**
 * Describes the message envoy.extensions.filters.http.rbac.v3.RBAC.
 * Use `create(RBACSchema)` to create a new message.
 */
export const RBACSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_rbac_v3_rbac, 0);

/**
 * Describes the message envoy.extensions.filters.http.rbac.v3.RBACPerRoute.
 * Use `create(RBACPerRouteSchema)` to create a new message.
 */
export const RBACPerRouteSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_rbac_v3_rbac, 1);

