// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/type/matcher/node.proto (package envoy.type.matcher, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_type_matcher_string } from "./string_pb";
import { file_envoy_type_matcher_struct } from "./struct_pb";
import { file_udpa_annotations_status } from "../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/type/matcher/node.proto.
 */
export const file_envoy_type_matcher_node = /*@__PURE__*/
  fileDesc("Ch1lbnZveS90eXBlL21hdGNoZXIvbm9kZS5wcm90bxISZW52b3kudHlwZS5tYXRjaGVyInwKC05vZGVNYXRjaGVyEjIKB25vZGVfaWQYASABKAsyIS5lbnZveS50eXBlLm1hdGNoZXIuU3RyaW5nTWF0Y2hlchI5Cg5ub2RlX21ldGFkYXRhcxgCIAMoCzIhLmVudm95LnR5cGUubWF0Y2hlci5TdHJ1Y3RNYXRjaGVyQnIKIGlvLmVudm95cHJveHkuZW52b3kudHlwZS5tYXRjaGVyQglOb2RlUHJvdG9QAVo5Z2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvdHlwZS9tYXRjaGVyuoDI0QYCEAFiBnByb3RvMw", [file_envoy_type_matcher_string, file_envoy_type_matcher_struct, file_udpa_annotations_status]);

/**
 * Describes the message envoy.type.matcher.NodeMatcher.
 * Use `create(NodeMatcherSchema)` to create a new message.
 */
export const NodeMatcherSchema = /*@__PURE__*/
  messageDesc(file_envoy_type_matcher_node, 0);

