// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/type/matcher/value.proto (package envoy.type.matcher, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DoubleMatcher } from "./number_pb";
import type { StringMatcher } from "./string_pb";

/**
 * Describes the file envoy/type/matcher/value.proto.
 */
export declare const file_envoy_type_matcher_value: GenFile;

/**
 * Specifies the way to match a Protobuf::Value. Primitive values and ListValue are supported.
 * StructValue is not supported and is always not matched.
 * [#next-free-field: 7]
 *
 * @generated from message envoy.type.matcher.ValueMatcher
 */
export declare type ValueMatcher = Message<"envoy.type.matcher.ValueMatcher"> & {
  /**
   * Specifies how to match a value.
   *
   * @generated from oneof envoy.type.matcher.ValueMatcher.match_pattern
   */
  matchPattern: {
    /**
     * If specified, a match occurs if and only if the target value is a NullValue.
     *
     * @generated from field: envoy.type.matcher.ValueMatcher.NullMatch null_match = 1;
     */
    value: ValueMatcher_NullMatch;
    case: "nullMatch";
  } | {
    /**
     * If specified, a match occurs if and only if the target value is a double value and is
     * matched to this field.
     *
     * @generated from field: envoy.type.matcher.DoubleMatcher double_match = 2;
     */
    value: DoubleMatcher;
    case: "doubleMatch";
  } | {
    /**
     * If specified, a match occurs if and only if the target value is a string value and is
     * matched to this field.
     *
     * @generated from field: envoy.type.matcher.StringMatcher string_match = 3;
     */
    value: StringMatcher;
    case: "stringMatch";
  } | {
    /**
     * If specified, a match occurs if and only if the target value is a bool value and is equal
     * to this field.
     *
     * @generated from field: bool bool_match = 4;
     */
    value: boolean;
    case: "boolMatch";
  } | {
    /**
     * If specified, value match will be performed based on whether the path is referring to a
     * valid primitive value in the metadata. If the path is referring to a non-primitive value,
     * the result is always not matched.
     *
     * @generated from field: bool present_match = 5;
     */
    value: boolean;
    case: "presentMatch";
  } | {
    /**
     * If specified, a match occurs if and only if the target value is a list value and
     * is matched to this field.
     *
     * @generated from field: envoy.type.matcher.ListMatcher list_match = 6;
     */
    value: ListMatcher;
    case: "listMatch";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.type.matcher.ValueMatcher.
 * Use `create(ValueMatcherSchema)` to create a new message.
 */
export declare const ValueMatcherSchema: GenMessage<ValueMatcher>;

/**
 * NullMatch is an empty message to specify a null value.
 *
 * @generated from message envoy.type.matcher.ValueMatcher.NullMatch
 */
export declare type ValueMatcher_NullMatch = Message<"envoy.type.matcher.ValueMatcher.NullMatch"> & {
};

/**
 * Describes the message envoy.type.matcher.ValueMatcher.NullMatch.
 * Use `create(ValueMatcher_NullMatchSchema)` to create a new message.
 */
export declare const ValueMatcher_NullMatchSchema: GenMessage<ValueMatcher_NullMatch>;

/**
 * Specifies the way to match a list value.
 *
 * @generated from message envoy.type.matcher.ListMatcher
 */
export declare type ListMatcher = Message<"envoy.type.matcher.ListMatcher"> & {
  /**
   * @generated from oneof envoy.type.matcher.ListMatcher.match_pattern
   */
  matchPattern: {
    /**
     * If specified, at least one of the values in the list must match the value specified.
     *
     * @generated from field: envoy.type.matcher.ValueMatcher one_of = 1;
     */
    value: ValueMatcher;
    case: "oneOf";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message envoy.type.matcher.ListMatcher.
 * Use `create(ListMatcherSchema)` to create a new message.
 */
export declare const ListMatcherSchema: GenMessage<ListMatcher>;

