// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/type/matcher/value.proto (package envoy.type.matcher, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_type_matcher_number } from "./number_pb";
import { file_envoy_type_matcher_string } from "./string_pb";
import { file_udpa_annotations_status } from "../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../validate/validate_pb";

/**
 * Describes the file envoy/type/matcher/value.proto.
 */
export const file_envoy_type_matcher_value = /*@__PURE__*/
  fileDesc("Ch5lbnZveS90eXBlL21hdGNoZXIvdmFsdWUucHJvdG8SEmVudm95LnR5cGUubWF0Y2hlciLPAgoMVmFsdWVNYXRjaGVyEkAKCm51bGxfbWF0Y2gYASABKAsyKi5lbnZveS50eXBlLm1hdGNoZXIuVmFsdWVNYXRjaGVyLk51bGxNYXRjaEgAEjkKDGRvdWJsZV9tYXRjaBgCIAEoCzIhLmVudm95LnR5cGUubWF0Y2hlci5Eb3VibGVNYXRjaGVySAASOQoMc3RyaW5nX21hdGNoGAMgASgLMiEuZW52b3kudHlwZS5tYXRjaGVyLlN0cmluZ01hdGNoZXJIABIUCgpib29sX21hdGNoGAQgASgISAASFwoNcHJlc2VudF9tYXRjaBgFIAEoCEgAEjUKCmxpc3RfbWF0Y2gYBiABKAsyHy5lbnZveS50eXBlLm1hdGNoZXIuTGlzdE1hdGNoZXJIABoLCglOdWxsTWF0Y2hCFAoNbWF0Y2hfcGF0dGVybhID+EIBIlcKC0xpc3RNYXRjaGVyEjIKBm9uZV9vZhgBIAEoCzIgLmVudm95LnR5cGUubWF0Y2hlci5WYWx1ZU1hdGNoZXJIAEIUCg1tYXRjaF9wYXR0ZXJuEgP4QgFCcwogaW8uZW52b3lwcm94eS5lbnZveS50eXBlLm1hdGNoZXJCClZhbHVlUHJvdG9QAVo5Z2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvdHlwZS9tYXRjaGVyuoDI0QYCEAFiBnByb3RvMw", [file_envoy_type_matcher_number, file_envoy_type_matcher_string, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.type.matcher.ValueMatcher.
 * Use `create(ValueMatcherSchema)` to create a new message.
 */
export const ValueMatcherSchema = /*@__PURE__*/
  messageDesc(file_envoy_type_matcher_value, 0);

/**
 * Describes the message envoy.type.matcher.ValueMatcher.NullMatch.
 * Use `create(ValueMatcher_NullMatchSchema)` to create a new message.
 */
export const ValueMatcher_NullMatchSchema = /*@__PURE__*/
  messageDesc(file_envoy_type_matcher_value, 0, 0);

/**
 * Describes the message envoy.type.matcher.ListMatcher.
 * Use `create(ListMatcherSchema)` to create a new message.
 */
export const ListMatcherSchema = /*@__PURE__*/
  messageDesc(file_envoy_type_matcher_value, 1);

