// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/quic/server_preferred_address/v3/fixed_server_preferred_address_config.proto (package envoy.extensions.quic.server_preferred_address.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { SocketAddress } from "../../../../config/core/v3/address_pb";

/**
 * Describes the file envoy/extensions/quic/server_preferred_address/v3/fixed_server_preferred_address_config.proto.
 */
export declare const file_envoy_extensions_quic_server_preferred_address_v3_fixed_server_preferred_address_config: GenFile;

/**
 * Configuration for FixedServerPreferredAddressConfig.
 *
 * @generated from message envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig
 */
export declare type FixedServerPreferredAddressConfig = Message<"envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig"> & {
  /**
   * String representation of IPv4 address, i.e. "127.0.0.2".
   * If not specified, none will be configured.
   *
   * @generated from field: string ipv4_address = 1;
   */
  ipv4Address: string;

  /**
   * The IPv4 address to advertise to clients for Server Preferred Address.
   * This field takes precedence over
   * :ref:`ipv4_address <envoy_v3_api_field_extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.ipv4_address>`.
   *
   * @generated from field: envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.AddressFamilyConfig ipv4_config = 3;
   */
  ipv4Config?: FixedServerPreferredAddressConfig_AddressFamilyConfig;

  /**
   * String representation of IPv6 address, i.e. "::1".
   * If not specified, none will be configured.
   *
   * @generated from field: string ipv6_address = 2;
   */
  ipv6Address: string;

  /**
   * The IPv6 address to advertise to clients for Server Preferred Address.
   * This field takes precedence over
   * :ref:`ipv6_address <envoy_v3_api_field_extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.ipv6_address>`.
   *
   * @generated from field: envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.AddressFamilyConfig ipv6_config = 4;
   */
  ipv6Config?: FixedServerPreferredAddressConfig_AddressFamilyConfig;
};

/**
 * Describes the message envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.
 * Use `create(FixedServerPreferredAddressConfigSchema)` to create a new message.
 */
export declare const FixedServerPreferredAddressConfigSchema: GenMessage<FixedServerPreferredAddressConfig>;

/**
 * Addresses for server preferred address for a single address family (IPv4 or IPv6).
 *
 * @generated from message envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.AddressFamilyConfig
 */
export declare type FixedServerPreferredAddressConfig_AddressFamilyConfig = Message<"envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.AddressFamilyConfig"> & {
  /**
   * The server preferred address sent to clients.
   *
   * .. note::
   *
   *   Envoy currently requires all packets for a QUIC connection to arrive on the same port. Therefore, unless a
   *   :ref:`dnat_address <envoy_v3_api_field_extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.AddressFamilyConfig.dnat_address>`
   *   is explicitly configured, the port specified here must be set to zero. In such cases, Envoy will automatically
   *   use the listener's port.
   *
   *
   * @generated from field: envoy.config.core.v3.SocketAddress address = 1;
   */
  address?: SocketAddress;

  /**
   * If a DNAT exists between the client and Envoy, this is the address where Envoy will observe incoming server
   * preferred address packets. If unspecified, Envoy assumes there is no DNAT, and packets will be sent directly
   * to the address advertised to clients as the server preferred address.
   *
   * .. note::
   *
   *   Envoy currently requires all packets for a QUIC connection to arrive on the same port. Consequently, the
   *   port for this address must be set to zero, with Envoy defaulting to the listener's port instead.
   *
   *
   * @generated from field: envoy.config.core.v3.SocketAddress dnat_address = 2;
   */
  dnatAddress?: SocketAddress;
};

/**
 * Describes the message envoy.extensions.quic.server_preferred_address.v3.FixedServerPreferredAddressConfig.AddressFamilyConfig.
 * Use `create(FixedServerPreferredAddressConfig_AddressFamilyConfigSchema)` to create a new message.
 */
export declare const FixedServerPreferredAddressConfig_AddressFamilyConfigSchema: GenMessage<FixedServerPreferredAddressConfig_AddressFamilyConfig>;

