// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/retry/priority/previous_priorities/v3/previous_priorities_config.proto (package envoy.extensions.retry.priority.previous_priorities.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../../../udpa/annotations/versioning_pb";
import { file_validate_validate } from "../../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/retry/priority/previous_priorities/v3/previous_priorities_config.proto.
 */
export const file_envoy_extensions_retry_priority_previous_priorities_v3_previous_priorities_config = /*@__PURE__*/
  fileDesc("CldlbnZveS9leHRlbnNpb25zL3JldHJ5L3ByaW9yaXR5L3ByZXZpb3VzX3ByaW9yaXRpZXMvdjMvcHJldmlvdXNfcHJpb3JpdGllc19jb25maWcucHJvdG8SNmVudm95LmV4dGVuc2lvbnMucmV0cnkucHJpb3JpdHkucHJldmlvdXNfcHJpb3JpdGllcy52MyKFAQoYUHJldmlvdXNQcmlvcml0aWVzQ29uZmlnEiEKEHVwZGF0ZV9mcmVxdWVuY3kYASABKAVCB/pCBBoCIAA6RprFiB5BCj9lbnZveS5jb25maWcucmV0cnkucHJldmlvdXNfcHJpb3JpdGllcy5QcmV2aW91c1ByaW9yaXRpZXNDb25maWdC5AEKRGlvLmVudm95cHJveHkuZW52b3kuZXh0ZW5zaW9ucy5yZXRyeS5wcmlvcml0eS5wcmV2aW91c19wcmlvcml0aWVzLnYzQh1QcmV2aW91c1ByaW9yaXRpZXNDb25maWdQcm90b1ABWnNnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9leHRlbnNpb25zL3JldHJ5L3ByaW9yaXR5L3ByZXZpb3VzX3ByaW9yaXRpZXMvdjM7cHJldmlvdXNfcHJpb3JpdGllc3YzuoDI0QYCEAJiBnByb3RvMw", [file_udpa_annotations_status, file_udpa_annotations_versioning, file_validate_validate]);

/**
 * Describes the message envoy.extensions.retry.priority.previous_priorities.v3.PreviousPrioritiesConfig.
 * Use `create(PreviousPrioritiesConfigSchema)` to create a new message.
 */
export const PreviousPrioritiesConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_retry_priority_previous_priorities_v3_previous_priorities_config, 0);

