// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/cdn_loop/v3/cdn_loop.proto (package envoy.extensions.filters.http.cdn_loop.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/extensions/filters/http/cdn_loop/v3/cdn_loop.proto.
 */
export declare const file_envoy_extensions_filters_http_cdn_loop_v3_cdn_loop: GenFile;

/**
 * CDN-Loop Header filter config. See the :ref:`configuration overview
 * <config_http_filters_cdn_loop>` for more information.
 *
 * @generated from message envoy.extensions.filters.http.cdn_loop.v3.CdnLoopConfig
 */
export declare type CdnLoopConfig = Message<"envoy.extensions.filters.http.cdn_loop.v3.CdnLoopConfig"> & {
  /**
   * The CDN identifier to use for loop checks and to append to the
   * CDN-Loop header.
   *
   * RFC 8586 calls this the cdn-id. The cdn-id can either be a
   * pseudonym or hostname the CDN is in control of.
   *
   * cdn_id must not be empty.
   *
   * @generated from field: string cdn_id = 1;
   */
  cdnId: string;

  /**
   * The maximum allowed count of cdn_id in the downstream CDN-Loop
   * request header.
   *
   * The default of 0 means a request can transit the CdnLoopFilter
   * once. A value of 1 means that a request can transit the
   * CdnLoopFilter twice and so on.
   *
   * @generated from field: uint32 max_allowed_occurrences = 2;
   */
  maxAllowedOccurrences: number;
};

/**
 * Describes the message envoy.extensions.filters.http.cdn_loop.v3.CdnLoopConfig.
 * Use `create(CdnLoopConfigSchema)` to create a new message.
 */
export declare const CdnLoopConfigSchema: GenMessage<CdnLoopConfig>;

