// @generated by protoc-gen-es v2.10.0
// @generated from file xds/annotations/v3/migrate.proto (package xds.annotations.v3, syntax proto3)
/* eslint-disable */

import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file xds/annotations/v3/migrate.proto.
 */
export const file_xds_annotations_v3_migrate = /*@__PURE__*/
  fileDesc("CiB4ZHMvYW5ub3RhdGlvbnMvdjMvbWlncmF0ZS5wcm90bxISeGRzLmFubm90YXRpb25zLnYzIiMKEU1pZ3JhdGVBbm5vdGF0aW9uEg4KBnJlbmFtZRgBIAEoCSJBChZGaWVsZE1pZ3JhdGVBbm5vdGF0aW9uEg4KBnJlbmFtZRgBIAEoCRIXCg9vbmVvZl9wcm9tb3Rpb24YAiABKAkiMAoVRmlsZU1pZ3JhdGVBbm5vdGF0aW9uEhcKD21vdmVfdG9fcGFja2FnZRgCIAEoCTpyCg9tZXNzYWdlX21pZ3JhdGUSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYzuntNSABKAsyJS54ZHMuYW5ub3RhdGlvbnMudjMuTWlncmF0ZUFubm90YXRpb25SDm1lc3NhZ2VNaWdyYXRlOnEKDWZpZWxkX21pZ3JhdGUSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGM7p7TUgASgLMioueGRzLmFubm90YXRpb25zLnYzLkZpZWxkTWlncmF0ZUFubm90YXRpb25SDGZpZWxkTWlncmF0ZTppCgxlbnVtX21pZ3JhdGUSHC5nb29nbGUucHJvdG9idWYuRW51bU9wdGlvbnMYzuntNSABKAsyJS54ZHMuYW5ub3RhdGlvbnMudjMuTWlncmF0ZUFubm90YXRpb25SC2VudW1NaWdyYXRlOnkKEmVudW1fdmFsdWVfbWlncmF0ZRIhLmdvb2dsZS5wcm90b2J1Zi5FbnVtVmFsdWVPcHRpb25zGM7p7TUgASgLMiUueGRzLmFubm90YXRpb25zLnYzLk1pZ3JhdGVBbm5vdGF0aW9uUhBlbnVtVmFsdWVNaWdyYXRlOm0KDGZpbGVfbWlncmF0ZRIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxjO6e01IAEoCzIpLnhkcy5hbm5vdGF0aW9ucy52My5GaWxlTWlncmF0ZUFubm90YXRpb25SC2ZpbGVNaWdyYXRlQitaKWdpdGh1Yi5jb20vY25jZi94ZHMvZ28veGRzL2Fubm90YXRpb25zL3YzYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * Describes the message xds.annotations.v3.MigrateAnnotation.
 * Use `create(MigrateAnnotationSchema)` to create a new message.
 */
export const MigrateAnnotationSchema = /*@__PURE__*/
  messageDesc(file_xds_annotations_v3_migrate, 0);

/**
 * Describes the message xds.annotations.v3.FieldMigrateAnnotation.
 * Use `create(FieldMigrateAnnotationSchema)` to create a new message.
 */
export const FieldMigrateAnnotationSchema = /*@__PURE__*/
  messageDesc(file_xds_annotations_v3_migrate, 1);

/**
 * Describes the message xds.annotations.v3.FileMigrateAnnotation.
 * Use `create(FileMigrateAnnotationSchema)` to create a new message.
 */
export const FileMigrateAnnotationSchema = /*@__PURE__*/
  messageDesc(file_xds_annotations_v3_migrate, 2);

/**
 * @generated from extension: xds.annotations.v3.MigrateAnnotation message_migrate = 112948430;
 */
export const message_migrate = /*@__PURE__*/
  extDesc(file_xds_annotations_v3_migrate, 0);

/**
 * @generated from extension: xds.annotations.v3.FieldMigrateAnnotation field_migrate = 112948430;
 */
export const field_migrate = /*@__PURE__*/
  extDesc(file_xds_annotations_v3_migrate, 1);

/**
 * @generated from extension: xds.annotations.v3.MigrateAnnotation enum_migrate = 112948430;
 */
export const enum_migrate = /*@__PURE__*/
  extDesc(file_xds_annotations_v3_migrate, 2);

/**
 * @generated from extension: xds.annotations.v3.MigrateAnnotation enum_value_migrate = 112948430;
 */
export const enum_value_migrate = /*@__PURE__*/
  extDesc(file_xds_annotations_v3_migrate, 3);

/**
 * @generated from extension: xds.annotations.v3.FileMigrateAnnotation file_migrate = 112948430;
 */
export const file_migrate = /*@__PURE__*/
  extDesc(file_xds_annotations_v3_migrate, 4);

