// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/core/v3/grpc_method_list.proto (package envoy.config.core.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/config/core/v3/grpc_method_list.proto.
 */
export declare const file_envoy_config_core_v3_grpc_method_list: GenFile;

/**
 * A list of gRPC methods which can be used as an allowlist, for example.
 *
 * @generated from message envoy.config.core.v3.GrpcMethodList
 */
export declare type GrpcMethodList = Message<"envoy.config.core.v3.GrpcMethodList"> & {
  /**
   * @generated from field: repeated envoy.config.core.v3.GrpcMethodList.Service services = 1;
   */
  services: GrpcMethodList_Service[];
};

/**
 * Describes the message envoy.config.core.v3.GrpcMethodList.
 * Use `create(GrpcMethodListSchema)` to create a new message.
 */
export declare const GrpcMethodListSchema: GenMessage<GrpcMethodList>;

/**
 * @generated from message envoy.config.core.v3.GrpcMethodList.Service
 */
export declare type GrpcMethodList_Service = Message<"envoy.config.core.v3.GrpcMethodList.Service"> & {
  /**
   * The name of the gRPC service.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The names of the gRPC methods in this service.
   *
   * @generated from field: repeated string method_names = 2;
   */
  methodNames: string[];
};

/**
 * Describes the message envoy.config.core.v3.GrpcMethodList.Service.
 * Use `create(GrpcMethodList_ServiceSchema)` to create a new message.
 */
export declare const GrpcMethodList_ServiceSchema: GenMessage<GrpcMethodList_Service>;

