// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/core/v3/resolver.proto (package envoy.config.core.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_config_core_v3_address } from "./address_pb";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../validate/validate_pb";

/**
 * Describes the file envoy/config/core/v3/resolver.proto.
 */
export const file_envoy_config_core_v3_resolver = /*@__PURE__*/
  fileDesc("CiNlbnZveS9jb25maWcvY29yZS92My9yZXNvbHZlci5wcm90bxIUZW52b3kuY29uZmlnLmNvcmUudjMiVwoSRG5zUmVzb2x2ZXJPcHRpb25zEh8KF3VzZV90Y3BfZm9yX2Ruc19sb29rdXBzGAEgASgIEiAKGG5vX2RlZmF1bHRfc2VhcmNoX2RvbWFpbhgCIAEoCCKZAQoTRG5zUmVzb2x1dGlvbkNvbmZpZxI6CglyZXNvbHZlcnMYASADKAsyHS5lbnZveS5jb25maWcuY29yZS52My5BZGRyZXNzQgj6QgWSAQIIARJGChRkbnNfcmVzb2x2ZXJfb3B0aW9ucxgCIAEoCzIoLmVudm95LmNvbmZpZy5jb3JlLnYzLkRuc1Jlc29sdmVyT3B0aW9uc0KBAQoiaW8uZW52b3lwcm94eS5lbnZveS5jb25maWcuY29yZS52M0INUmVzb2x2ZXJQcm90b1ABWkJnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9jb25maWcvY29yZS92Mztjb3JldjO6gMjRBgIQAmIGcHJvdG8z", [file_envoy_config_core_v3_address, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.config.core.v3.DnsResolverOptions.
 * Use `create(DnsResolverOptionsSchema)` to create a new message.
 */
export const DnsResolverOptionsSchema = /*@__PURE__*/
  messageDesc(file_envoy_config_core_v3_resolver, 0);

/**
 * Describes the message envoy.config.core.v3.DnsResolutionConfig.
 * Use `create(DnsResolutionConfigSchema)` to create a new message.
 */
export const DnsResolutionConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_config_core_v3_resolver, 1);

