// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/filter/listener/proxy_protocol/v2/proxy_protocol.proto (package envoy.config.filter.listener.proxy_protocol.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_migrate } from "../../../../../../udpa/annotations/migrate_pb";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/config/filter/listener/proxy_protocol/v2/proxy_protocol.proto.
 */
export const file_envoy_config_filter_listener_proxy_protocol_v2_proxy_protocol = /*@__PURE__*/
  fileDesc("CkNlbnZveS9jb25maWcvZmlsdGVyL2xpc3RlbmVyL3Byb3h5X3Byb3RvY29sL3YyL3Byb3h5X3Byb3RvY29sLnByb3RvEi5lbnZveS5jb25maWcuZmlsdGVyLmxpc3RlbmVyLnByb3h5X3Byb3RvY29sLnYyIg8KDVByb3h5UHJvdG9jb2xC/wEKPGlvLmVudm95cHJveHkuZW52b3kuY29uZmlnLmZpbHRlci5saXN0ZW5lci5wcm94eV9wcm90b2NvbC52MkISUHJveHlQcm90b2NvbFByb3RvUAFaZmdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2NvbmZpZy9maWx0ZXIvbGlzdGVuZXIvcHJveHlfcHJvdG9jb2wvdjI7cHJveHlfcHJvdG9jb2x2MvKY/o8FNRIzZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmxpc3RlbmVyLnByb3h5X3Byb3RvY29sLnYzuoDI0QYCEAFiBnByb3RvMw", [file_udpa_annotations_migrate, file_udpa_annotations_status]);

/**
 * Describes the message envoy.config.filter.listener.proxy_protocol.v2.ProxyProtocol.
 * Use `create(ProxyProtocolSchema)` to create a new message.
 */
export const ProxyProtocolSchema = /*@__PURE__*/
  messageDesc(file_envoy_config_filter_listener_proxy_protocol_v2_proxy_protocol, 0);

