// @generated by protoc-gen-es v2.10.0
// @generated from file xds/type/v3/range.proto (package xds.type.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file xds/type/v3/range.proto.
 */
export declare const file_xds_type_v3_range: GenFile;

/**
 * Specifies the int64 start and end of the range using half-open interval
 * semantics [start, end).
 *
 * @generated from message xds.type.v3.Int64Range
 */
export declare type Int64Range = Message<"xds.type.v3.Int64Range"> & {
  /**
   * start of the range (inclusive)
   *
   * @generated from field: int64 start = 1;
   */
  start: bigint;

  /**
   * end of the range (exclusive)
   *
   * @generated from field: int64 end = 2;
   */
  end: bigint;
};

/**
 * Describes the message xds.type.v3.Int64Range.
 * Use `create(Int64RangeSchema)` to create a new message.
 */
export declare const Int64RangeSchema: GenMessage<Int64Range>;

/**
 * Specifies the int32 start and end of the range using half-open interval
 * semantics [start, end).
 *
 * @generated from message xds.type.v3.Int32Range
 */
export declare type Int32Range = Message<"xds.type.v3.Int32Range"> & {
  /**
   * start of the range (inclusive)
   *
   * @generated from field: int32 start = 1;
   */
  start: number;

  /**
   * end of the range (exclusive)
   *
   * @generated from field: int32 end = 2;
   */
  end: number;
};

/**
 * Describes the message xds.type.v3.Int32Range.
 * Use `create(Int32RangeSchema)` to create a new message.
 */
export declare const Int32RangeSchema: GenMessage<Int32Range>;

/**
 * Specifies the double start and end of the range using half-open interval
 * semantics [start, end).
 *
 * @generated from message xds.type.v3.DoubleRange
 */
export declare type DoubleRange = Message<"xds.type.v3.DoubleRange"> & {
  /**
   * start of the range (inclusive)
   *
   * @generated from field: double start = 1;
   */
  start: number;

  /**
   * end of the range (exclusive)
   *
   * @generated from field: double end = 2;
   */
  end: number;
};

/**
 * Describes the message xds.type.v3.DoubleRange.
 * Use `create(DoubleRangeSchema)` to create a new message.
 */
export declare const DoubleRangeSchema: GenMessage<DoubleRange>;

