// @generated by protoc-gen-es v2.10.0
// @generated from file contrib/envoy/extensions/regex_engines/hyperscan/v3alpha/hyperscan.proto (package envoy.extensions.regex_engines.hyperscan.v3alpha, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";

/**
 * Describes the file contrib/envoy/extensions/regex_engines/hyperscan/v3alpha/hyperscan.proto.
 */
export const file_contrib_envoy_extensions_regex_engines_hyperscan_v3alpha_hyperscan = /*@__PURE__*/
  fileDesc("Ckhjb250cmliL2Vudm95L2V4dGVuc2lvbnMvcmVnZXhfZW5naW5lcy9oeXBlcnNjYW4vdjNhbHBoYS9oeXBlcnNjYW4ucHJvdG8SMGVudm95LmV4dGVuc2lvbnMucmVnZXhfZW5naW5lcy5oeXBlcnNjYW4udjNhbHBoYSILCglIeXBlcnNjYW5CuwEKPmlvLmVudm95cHJveHkuZW52b3kuZXh0ZW5zaW9ucy5yZWdleF9lbmdpbmVzLmh5cGVyc2Nhbi52M2FscGhhQg5IeXBlcnNjYW5Qcm90b1ABWl9naXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9jb250cmliL2Vudm95L2V4dGVuc2lvbnMvcmVnZXhfZW5naW5lcy9oeXBlcnNjYW4vdjNhbHBoYbqAyNEGAhACYgZwcm90bzM", [file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.regex_engines.hyperscan.v3alpha.Hyperscan.
 * Use `create(HyperscanSchema)` to create a new message.
 */
export const HyperscanSchema = /*@__PURE__*/
  messageDesc(file_contrib_envoy_extensions_regex_engines_hyperscan_v3alpha_hyperscan, 0);

