// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/api/v2/lds.proto (package envoy.api.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_api_v2_discovery } from "./discovery_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import { file_envoy_annotations_resource } from "../../annotations/resource_pb";
import { file_udpa_annotations_migrate } from "../../../udpa/annotations/migrate_pb";
import { file_udpa_annotations_status } from "../../../udpa/annotations/status_pb";
import { file_envoy_api_v2_listener } from "./listener_pb";

/**
 * Describes the file envoy/api/v2/lds.proto.
 */
export const file_envoy_api_v2_lds = /*@__PURE__*/
  fileDesc("ChZlbnZveS9hcGkvdjIvbGRzLnByb3RvEgxlbnZveS5hcGkudjIiCgoITGRzRHVtbXky7QIKGExpc3RlbmVyRGlzY292ZXJ5U2VydmljZRJhCg5EZWx0YUxpc3RlbmVycxIjLmVudm95LmFwaS52Mi5EZWx0YURpc2NvdmVyeVJlcXVlc3QaJC5lbnZveS5hcGkudjIuRGVsdGFEaXNjb3ZlcnlSZXNwb25zZSIAKAEwARJYCg9TdHJlYW1MaXN0ZW5lcnMSHi5lbnZveS5hcGkudjIuRGlzY292ZXJ5UmVxdWVzdBofLmVudm95LmFwaS52Mi5EaXNjb3ZlcnlSZXNwb25zZSIAKAEwARJ1Cg5GZXRjaExpc3RlbmVycxIeLmVudm95LmFwaS52Mi5EaXNjb3ZlcnlSZXF1ZXN0Gh8uZW52b3kuYXBpLnYyLkRpc2NvdmVyeVJlc3BvbnNlIiKC0+STAhw6ASoiFy92Mi9kaXNjb3Zlcnk6bGlzdGVuZXJzGh2KpJbzBxcKFWVudm95LmFwaS52Mi5MaXN0ZW5lckKMAQoaaW8uZW52b3lwcm94eS5lbnZveS5hcGkudjJCCExkc1Byb3RvUAFaOWdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2FwaS92MjthcGl2MvKY/o8FGxIZZW52b3kuc2VydmljZS5saXN0ZW5lci52M7qAyNEGAhABUAViBnByb3RvMw", [file_envoy_api_v2_discovery, file_google_api_annotations, file_envoy_annotations_resource, file_udpa_annotations_migrate, file_udpa_annotations_status, file_envoy_api_v2_listener]);

/**
 * Describes the message envoy.api.v2.LdsDummy.
 * Use `create(LdsDummySchema)` to create a new message.
 */
export const LdsDummySchema = /*@__PURE__*/
  messageDesc(file_envoy_api_v2_lds, 0);

/**
 * The Envoy instance initiates an RPC at startup to discover a list of
 * listeners. Updates are delivered via streaming from the LDS server and
 * consist of a complete update of all listeners. Existing connections will be
 * allowed to drain from listeners that are no longer present.
 *
 * @generated from service envoy.api.v2.ListenerDiscoveryService
 */
export const ListenerDiscoveryService = /*@__PURE__*/
  serviceDesc(file_envoy_api_v2_lds, 0);

