// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/service/listener/v3/lds.proto (package envoy.service.listener.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DeltaDiscoveryRequestSchema, DeltaDiscoveryResponseSchema, DiscoveryRequestSchema, DiscoveryResponseSchema } from "../../discovery/v3/discovery_pb";

/**
 * Describes the file envoy/service/listener/v3/lds.proto.
 */
export declare const file_envoy_service_listener_v3_lds: GenFile;

/**
 * [#not-implemented-hide:] Not configuration. Workaround c++ protobuf issue with importing
 * services: https://github.com/google/protobuf/issues/4221 and protoxform to upgrade the file.
 *
 * @generated from message envoy.service.listener.v3.LdsDummy
 */
export declare type LdsDummy = Message<"envoy.service.listener.v3.LdsDummy"> & {
};

/**
 * Describes the message envoy.service.listener.v3.LdsDummy.
 * Use `create(LdsDummySchema)` to create a new message.
 */
export declare const LdsDummySchema: GenMessage<LdsDummy>;

/**
 * The Envoy instance initiates an RPC at startup to discover a list of
 * listeners. Updates are delivered via streaming from the LDS server and
 * consist of a complete update of all listeners. Existing connections will be
 * allowed to drain from listeners that are no longer present.
 *
 * @generated from service envoy.service.listener.v3.ListenerDiscoveryService
 */
export declare const ListenerDiscoveryService: GenService<{
  /**
   * @generated from rpc envoy.service.listener.v3.ListenerDiscoveryService.DeltaListeners
   */
  deltaListeners: {
    methodKind: "bidi_streaming";
    input: typeof DeltaDiscoveryRequestSchema;
    output: typeof DeltaDiscoveryResponseSchema;
  },
  /**
   * @generated from rpc envoy.service.listener.v3.ListenerDiscoveryService.StreamListeners
   */
  streamListeners: {
    methodKind: "bidi_streaming";
    input: typeof DiscoveryRequestSchema;
    output: typeof DiscoveryResponseSchema;
  },
  /**
   * @generated from rpc envoy.service.listener.v3.ListenerDiscoveryService.FetchListeners
   */
  fetchListeners: {
    methodKind: "unary";
    input: typeof DiscoveryRequestSchema;
    output: typeof DiscoveryResponseSchema;
  },
}>;

