// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/filter/http/aws_lambda/v2alpha/aws_lambda.proto (package envoy.config.filter.http.aws_lambda.v2alpha, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/config/filter/http/aws_lambda/v2alpha/aws_lambda.proto.
 */
export declare const file_envoy_config_filter_http_aws_lambda_v2alpha_aws_lambda: GenFile;

/**
 * AWS Lambda filter config
 *
 * @generated from message envoy.config.filter.http.aws_lambda.v2alpha.Config
 */
export declare type Config = Message<"envoy.config.filter.http.aws_lambda.v2alpha.Config"> & {
  /**
   * The ARN of the AWS Lambda to invoke when the filter is engaged
   * Must be in the following format:
   * arn:<partition>:lambda:<region>:<account-number>:function:<function-name>
   *
   * @generated from field: string arn = 1;
   */
  arn: string;

  /**
   * Whether to transform the request (headers and body) to a JSON payload or pass it as is.
   *
   * @generated from field: bool payload_passthrough = 2;
   */
  payloadPassthrough: boolean;

  /**
   * Determines the way to invoke the Lambda function.
   *
   * @generated from field: envoy.config.filter.http.aws_lambda.v2alpha.Config.InvocationMode invocation_mode = 3;
   */
  invocationMode: Config_InvocationMode;
};

/**
 * Describes the message envoy.config.filter.http.aws_lambda.v2alpha.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export declare const ConfigSchema: GenMessage<Config>;

/**
 * @generated from enum envoy.config.filter.http.aws_lambda.v2alpha.Config.InvocationMode
 */
export enum Config_InvocationMode {
  /**
   * This is the more common mode of invocation, in which Lambda responds after it has completed the function. In
   * this mode the output of the Lambda function becomes the response of the HTTP request.
   *
   * @generated from enum value: SYNCHRONOUS = 0;
   */
  SYNCHRONOUS = 0,

  /**
   * In this mode Lambda responds immediately but continues to process the function asynchronously. This mode can be
   * used to signal events for example. In this mode, Lambda responds with an acknowledgment that it received the
   * call which is translated to an HTTP 200 OK by the filter.
   *
   * @generated from enum value: ASYNCHRONOUS = 1;
   */
  ASYNCHRONOUS = 1,
}

/**
 * Describes the enum envoy.config.filter.http.aws_lambda.v2alpha.Config.InvocationMode.
 */
export declare const Config_InvocationModeSchema: GenEnum<Config_InvocationMode>;

/**
 * Per-route configuration for AWS Lambda. This can be useful when invoking a different Lambda function or a different
 * version of the same Lambda depending on the route.
 *
 * @generated from message envoy.config.filter.http.aws_lambda.v2alpha.PerRouteConfig
 */
export declare type PerRouteConfig = Message<"envoy.config.filter.http.aws_lambda.v2alpha.PerRouteConfig"> & {
  /**
   * @generated from field: envoy.config.filter.http.aws_lambda.v2alpha.Config invoke_config = 1;
   */
  invokeConfig?: Config;
};

/**
 * Describes the message envoy.config.filter.http.aws_lambda.v2alpha.PerRouteConfig.
 * Use `create(PerRouteConfigSchema)` to create a new message.
 */
export declare const PerRouteConfigSchema: GenMessage<PerRouteConfig>;

