// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/annotations/deprecation.proto (package envoy.annotations, syntax proto3)
/* eslint-disable */

import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file envoy/annotations/deprecation.proto.
 */
export const file_envoy_annotations_deprecation = /*@__PURE__*/
  fileDesc("CiNlbnZveS9hbm5vdGF0aW9ucy9kZXByZWNhdGlvbi5wcm90bxIRZW52b3kuYW5ub3RhdGlvbnM6VAoVZGlzYWxsb3dlZF9ieV9kZWZhdWx0Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjnra5aIAEoCFITZGlzYWxsb3dlZEJ5RGVmYXVsdDpfChtkZXByZWNhdGVkX2F0X21pbm9yX3ZlcnNpb24SHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGPLogEsgASgJUhhkZXByZWNhdGVkQXRNaW5vclZlcnNpb246YQoaZGlzYWxsb3dlZF9ieV9kZWZhdWx0X2VudW0SIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxj1zrYhIAEoCFIXZGlzYWxsb3dlZEJ5RGVmYXVsdEVudW06bAogZGVwcmVjYXRlZF9hdF9taW5vcl92ZXJzaW9uX2VudW0SIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxjBvrNWIAEoCVIcZGVwcmVjYXRlZEF0TWlub3JWZXJzaW9uRW51bUI6WjhnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9hbm5vdGF0aW9uc2IGcHJvdG8z", [file_google_protobuf_descriptor]);

/**
 * @generated from extension: bool disallowed_by_default = 189503207;
 */
export const disallowed_by_default = /*@__PURE__*/
  extDesc(file_envoy_annotations_deprecation, 0);

/**
 * The API major and minor version on which the field was deprecated
 * (e.g., "3.5" for major version 3 and minor version 5).
 *
 * @generated from extension: string deprecated_at_minor_version = 157299826;
 */
export const deprecated_at_minor_version = /*@__PURE__*/
  extDesc(file_envoy_annotations_deprecation, 1);

/**
 * @generated from extension: bool disallowed_by_default_enum = 70100853;
 */
export const disallowed_by_default_enum = /*@__PURE__*/
  extDesc(file_envoy_annotations_deprecation, 2);

/**
 * The API major and minor version on which the enum value was deprecated
 * (e.g., "3.5" for major version 3 and minor version 5).
 *
 * @generated from extension: string deprecated_at_minor_version_enum = 181198657;
 */
export const deprecated_at_minor_version_enum = /*@__PURE__*/
  extDesc(file_envoy_annotations_deprecation, 3);

