// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/gcp_authn/v3/gcp_authn.proto (package envoy.extensions.filters.http.gcp_authn.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { HttpUri } from "../../../../../config/core/v3/http_uri_pb";
import type { RetryPolicy } from "../../../../../config/core/v3/base_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file envoy/extensions/filters/http/gcp_authn/v3/gcp_authn.proto.
 */
export declare const file_envoy_extensions_filters_http_gcp_authn_v3_gcp_authn: GenFile;

/**
 * Filter configuration.
 * [#next-free-field: 7]
 *
 * @generated from message envoy.extensions.filters.http.gcp_authn.v3.GcpAuthnFilterConfig
 */
export declare type GcpAuthnFilterConfig = Message<"envoy.extensions.filters.http.gcp_authn.v3.GcpAuthnFilterConfig"> & {
  /**
   * The HTTP URI to fetch tokens from GCE Metadata Server(https://cloud.google.com/compute/docs/metadata/overview).
   * The URL format is "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=[AUDIENCE]"
   *
   * This field is deprecated because it does not match the API surface provided by the google auth libraries.
   * Control planes should not attempt to override the metadata server URI.
   * The cluster and timeout can be configured using the ``cluster`` and ``timeout`` fields instead.
   * For backward compatibility, the cluster and timeout configured in this field will be used
   * if the new ``cluster`` and ``timeout`` fields are not set.
   *
   * @generated from field: envoy.config.core.v3.HttpUri http_uri = 1 [deprecated = true];
   * @deprecated
   */
  httpUri?: HttpUri;

  /**
   * Retry policy for fetching tokens.
   * Not supported by all data planes.
   *
   * @generated from field: envoy.config.core.v3.RetryPolicy retry_policy = 2;
   */
  retryPolicy?: RetryPolicy;

  /**
   * Token cache configuration. This field is optional.
   *
   * @generated from field: envoy.extensions.filters.http.gcp_authn.v3.TokenCacheConfig cache_config = 3;
   */
  cacheConfig?: TokenCacheConfig;

  /**
   * Request header location to extract the token. By default (i.e. if this field is not specified), the token
   * is extracted to the Authorization HTTP header, in the format "Authorization: Bearer <token>".
   * Not supported by all data planes.
   *
   * @generated from field: envoy.extensions.filters.http.gcp_authn.v3.TokenHeader token_header = 4;
   */
  tokenHeader?: TokenHeader;

  /**
   * Cluster to send traffic to the GCE metadata server. Not supported
   * by all data planes; a data plane may instead have its own mechanism
   * for contacting the metadata server.
   *
   * @generated from field: string cluster = 5;
   */
  cluster: string;

  /**
   * Timeout for fetching the tokens from the GCE metadata server.
   * Not supported by all data planes.
   *
   * @generated from field: google.protobuf.Duration timeout = 6;
   */
  timeout?: Duration;
};

/**
 * Describes the message envoy.extensions.filters.http.gcp_authn.v3.GcpAuthnFilterConfig.
 * Use `create(GcpAuthnFilterConfigSchema)` to create a new message.
 */
export declare const GcpAuthnFilterConfigSchema: GenMessage<GcpAuthnFilterConfig>;

/**
 * Audience is the URL of the receiving service that performs token authentication.
 * It will be provided to the filter through cluster's typed_filter_metadata.
 *
 * @generated from message envoy.extensions.filters.http.gcp_authn.v3.Audience
 */
export declare type Audience = Message<"envoy.extensions.filters.http.gcp_authn.v3.Audience"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;
};

/**
 * Describes the message envoy.extensions.filters.http.gcp_authn.v3.Audience.
 * Use `create(AudienceSchema)` to create a new message.
 */
export declare const AudienceSchema: GenMessage<Audience>;

/**
 * Token Cache configuration.
 *
 * @generated from message envoy.extensions.filters.http.gcp_authn.v3.TokenCacheConfig
 */
export declare type TokenCacheConfig = Message<"envoy.extensions.filters.http.gcp_authn.v3.TokenCacheConfig"> & {
  /**
   * The number of cache entries. The maximum number of entries is INT64_MAX as it is constrained by underlying cache implementation.
   * Default value 0 (i.e., proto3 defaults) disables the cache by default. Other default values will enable the cache.
   *
   * @generated from field: google.protobuf.UInt64Value cache_size = 1;
   */
  cacheSize?: bigint;
};

/**
 * Describes the message envoy.extensions.filters.http.gcp_authn.v3.TokenCacheConfig.
 * Use `create(TokenCacheConfigSchema)` to create a new message.
 */
export declare const TokenCacheConfigSchema: GenMessage<TokenCacheConfig>;

/**
 * @generated from message envoy.extensions.filters.http.gcp_authn.v3.TokenHeader
 */
export declare type TokenHeader = Message<"envoy.extensions.filters.http.gcp_authn.v3.TokenHeader"> & {
  /**
   * The HTTP header's name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The header's prefix. The format is "value_prefix<token>"
   * For example, for "Authorization: Bearer <token>", value_prefix="Bearer " with a space at the
   * end.
   *
   * @generated from field: string value_prefix = 2;
   */
  valuePrefix: string;
};

/**
 * Describes the message envoy.extensions.filters.http.gcp_authn.v3.TokenHeader.
 * Use `create(TokenHeaderSchema)` to create a new message.
 */
export declare const TokenHeaderSchema: GenMessage<TokenHeader>;

