// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/quic/connection_debug_visitor/quic_stats/v3/quic_stats.proto (package envoy.extensions.quic.connection_debug_visitor.quic_stats.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/quic/connection_debug_visitor/quic_stats/v3/quic_stats.proto.
 */
export const file_envoy_extensions_quic_connection_debug_visitor_quic_stats_v3_quic_stats = /*@__PURE__*/
  fileDesc("Ck1lbnZveS9leHRlbnNpb25zL3F1aWMvY29ubmVjdGlvbl9kZWJ1Z192aXNpdG9yL3F1aWNfc3RhdHMvdjMvcXVpY19zdGF0cy5wcm90bxI8ZW52b3kuZXh0ZW5zaW9ucy5xdWljLmNvbm5lY3Rpb25fZGVidWdfdmlzaXRvci5xdWljX3N0YXRzLnYzIkgKBkNvbmZpZxI+Cg11cGRhdGVfcGVyaW9kGAIgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQgz6QgmqAQYyBBDAhD1C2AEKSmlvLmVudm95cHJveHkuZW52b3kuZXh0ZW5zaW9ucy5xdWljLmNvbm5lY3Rpb25fZGVidWdfdmlzaXRvci5xdWljX3N0YXRzLnYzQg5RdWljU3RhdHNQcm90b1ABWnBnaXRodWIuY29tL2Vudm95cHJveHkvZ28tY29udHJvbC1wbGFuZS9lbnZveS9leHRlbnNpb25zL3F1aWMvY29ubmVjdGlvbl9kZWJ1Z192aXNpdG9yL3F1aWNfc3RhdHMvdjM7cXVpY19zdGF0c3YzuoDI0QYCEAJiBnByb3RvMw", [file_google_protobuf_duration, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.extensions.quic.connection_debug_visitor.quic_stats.v3.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export const ConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_quic_connection_debug_visitor_quic_stats_v3_quic_stats, 0);

