// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/set_metadata/v3/set_metadata.proto (package envoy.extensions.filters.http.set_metadata.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_any, file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import { file_envoy_annotations_deprecation } from "../../../../../annotations/deprecation_pb";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_validate_validate } from "../../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/filters/http/set_metadata/v3/set_metadata.proto.
 */
export const file_envoy_extensions_filters_http_set_metadata_v3_set_metadata = /*@__PURE__*/
  fileDesc("CkBlbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9zZXRfbWV0YWRhdGEvdjMvc2V0X21ldGFkYXRhLnByb3RvEi1lbnZveS5leHRlbnNpb25zLmZpbHRlcnMuaHR0cC5zZXRfbWV0YWRhdGEudjMimwEKCE1ldGFkYXRhEiMKEm1ldGFkYXRhX25hbWVzcGFjZRgBIAEoCUIH+kIEcgIQARIXCg9hbGxvd19vdmVyd3JpdGUYAiABKAgSJgoFdmFsdWUYAyABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0EikKC3R5cGVkX3ZhbHVlGAQgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueSKxAQoGQ29uZmlnEicKEm1ldGFkYXRhX25hbWVzcGFjZRgBIAEoCUILGAGSx4bYBAMzLjASMwoFdmFsdWUYAiABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0QgsYAZLHhtgEAzMuMBJJCghtZXRhZGF0YRgDIAMoCzI3LmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLnNldF9tZXRhZGF0YS52My5NZXRhZGF0YUK+AQo7aW8uZW52b3lwcm94eS5lbnZveS5leHRlbnNpb25zLmZpbHRlcnMuaHR0cC5zZXRfbWV0YWRhdGEudjNCEFNldE1ldGFkYXRhUHJvdG9QAVpjZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9maWx0ZXJzL2h0dHAvc2V0X21ldGFkYXRhL3YzO3NldF9tZXRhZGF0YXYzuoDI0QYCEAJiBnByb3RvMw", [file_google_protobuf_any, file_google_protobuf_struct, file_envoy_annotations_deprecation, file_udpa_annotations_status, file_validate_validate]);

/**
 * Describes the message envoy.extensions.filters.http.set_metadata.v3.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_set_metadata_v3_set_metadata, 0);

/**
 * Describes the message envoy.extensions.filters.http.set_metadata.v3.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export const ConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_set_metadata_v3_set_metadata, 1);

