// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/grpc_service/call_credentials/google_refresh_token/v3/google_refresh_token_credentials.proto (package envoy.extensions.grpc_service.call_credentials.google_refresh_token.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";

/**
 * Describes the file envoy/extensions/grpc_service/call_credentials/google_refresh_token/v3/google_refresh_token_credentials.proto.
 */
export const file_envoy_extensions_grpc_service_call_credentials_google_refresh_token_v3_google_refresh_token_credentials = /*@__PURE__*/
  fileDesc("Cm1lbnZveS9leHRlbnNpb25zL2dycGNfc2VydmljZS9jYWxsX2NyZWRlbnRpYWxzL2dvb2dsZV9yZWZyZXNoX3Rva2VuL3YzL2dvb2dsZV9yZWZyZXNoX3Rva2VuX2NyZWRlbnRpYWxzLnByb3RvEkZlbnZveS5leHRlbnNpb25zLmdycGNfc2VydmljZS5jYWxsX2NyZWRlbnRpYWxzLmdvb2dsZV9yZWZyZXNoX3Rva2VuLnYzIi4KHUdvb2dsZVJlZnJlc2hUb2tlbkNyZWRlbnRpYWxzEg0KBXRva2VuGAEgASgJQosCClRpby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMuZ3JwY19zZXJ2aWNlLmNhbGxfY3JlZGVudGlhbHMuZ29vZ2xlX3JlZnJlc2hfdG9rZW4udjNCIkdvb2dsZVJlZnJlc2hUb2tlbkNyZWRlbnRpYWxzUHJvdG9QAVqEAWdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2V4dGVuc2lvbnMvZ3JwY19zZXJ2aWNlL2NhbGxfY3JlZGVudGlhbHMvZ29vZ2xlX3JlZnJlc2hfdG9rZW4vdjM7Z29vZ2xlX3JlZnJlc2hfdG9rZW52M7qAyNEGAhACYgZwcm90bzM", [file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.grpc_service.call_credentials.google_refresh_token.v3.GoogleRefreshTokenCredentials.
 * Use `create(GoogleRefreshTokenCredentialsSchema)` to create a new message.
 */
export const GoogleRefreshTokenCredentialsSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_grpc_service_call_credentials_google_refresh_token_v3_google_refresh_token_credentials, 0);

