// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/trace/v3/datadog.proto (package envoy.config.trace.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file envoy/config/trace/v3/datadog.proto.
 */
export declare const file_envoy_config_trace_v3_datadog: GenFile;

/**
 * Configuration for the Remote Configuration feature.
 *
 * @generated from message envoy.config.trace.v3.DatadogRemoteConfig
 */
export declare type DatadogRemoteConfig = Message<"envoy.config.trace.v3.DatadogRemoteConfig"> & {
  /**
   * Frequency at which new configuration updates are queried.
   * If no value is provided, the default value is delegated to the Datadog tracing library.
   *
   * @generated from field: google.protobuf.Duration polling_interval = 1;
   */
  pollingInterval?: Duration;
};

/**
 * Describes the message envoy.config.trace.v3.DatadogRemoteConfig.
 * Use `create(DatadogRemoteConfigSchema)` to create a new message.
 */
export declare const DatadogRemoteConfigSchema: GenMessage<DatadogRemoteConfig>;

/**
 * Configuration for the Datadog tracer.
 * [#extension: envoy.tracers.datadog]
 *
 * @generated from message envoy.config.trace.v3.DatadogConfig
 */
export declare type DatadogConfig = Message<"envoy.config.trace.v3.DatadogConfig"> & {
  /**
   * The cluster to use for submitting traces to the Datadog agent.
   *
   * @generated from field: string collector_cluster = 1;
   */
  collectorCluster: string;

  /**
   * The name used for the service when traces are generated by envoy.
   *
   * @generated from field: string service_name = 2;
   */
  serviceName: string;

  /**
   * Optional hostname to use when sending spans to the collector_cluster. Useful for collectors
   * that require a specific hostname. Defaults to :ref:`collector_cluster <envoy_v3_api_field_config.trace.v3.DatadogConfig.collector_cluster>` above.
   *
   * @generated from field: string collector_hostname = 3;
   */
  collectorHostname: string;

  /**
   * Enables and configures remote configuration.
   * Remote Configuration allows to configure the tracer from Datadog's user interface.
   * This feature can drastically increase the number of connections to the Datadog Agent.
   * Each tracer regularly polls for configuration updates, and the number of tracers is the product
   * of the number of listeners and worker threads.
   *
   * @generated from field: envoy.config.trace.v3.DatadogRemoteConfig remote_config = 4;
   */
  remoteConfig?: DatadogRemoteConfig;
};

/**
 * Describes the message envoy.config.trace.v3.DatadogConfig.
 * Use `create(DatadogConfigSchema)` to create a new message.
 */
export declare const DatadogConfigSchema: GenMessage<DatadogConfig>;

