// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/config/trace/v3/http_tracer.proto (package envoy.config.trace.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../udpa/annotations/versioning_pb";
import { file_validate_validate } from "../../../../validate/validate_pb";

/**
 * Describes the file envoy/config/trace/v3/http_tracer.proto.
 */
export const file_envoy_config_trace_v3_http_tracer = /*@__PURE__*/
  fileDesc("CidlbnZveS9jb25maWcvdHJhY2UvdjMvaHR0cF90cmFjZXIucHJvdG8SFWVudm95LmNvbmZpZy50cmFjZS52MyL4AQoHVHJhY2luZxIxCgRodHRwGAEgASgLMiMuZW52b3kuY29uZmlnLnRyYWNlLnYzLlRyYWNpbmcuSHR0cBqTAQoESHR0cBIVCgRuYW1lGAEgASgJQgf6QgRyAhABEiwKDHR5cGVkX2NvbmZpZxgDIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlIADopmsWIHiQKImVudm95LmNvbmZpZy50cmFjZS52Mi5UcmFjaW5nLkh0dHBCDQoLY29uZmlnX3R5cGVKBAgCEANSBmNvbmZpZzokmsWIHh8KHWVudm95LmNvbmZpZy50cmFjZS52Mi5UcmFjaW5nQoYBCiNpby5lbnZveXByb3h5LmVudm95LmNvbmZpZy50cmFjZS52M0IPSHR0cFRyYWNlclByb3RvUAFaRGdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2NvbmZpZy90cmFjZS92Mzt0cmFjZXYzuoDI0QYCEAJiBnByb3RvMw", [file_google_protobuf_any, file_udpa_annotations_status, file_udpa_annotations_versioning, file_validate_validate]);

/**
 * Describes the message envoy.config.trace.v3.Tracing.
 * Use `create(TracingSchema)` to create a new message.
 */
export const TracingSchema = /*@__PURE__*/
  messageDesc(file_envoy_config_trace_v3_http_tracer, 0);

/**
 * Describes the message envoy.config.trace.v3.Tracing.Http.
 * Use `create(Tracing_HttpSchema)` to create a new message.
 */
export const Tracing_HttpSchema = /*@__PURE__*/
  messageDesc(file_envoy_config_trace_v3_http_tracer, 0, 0);

