// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/access_loggers/wasm/v3/wasm.proto (package envoy.extensions.access_loggers.wasm.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { PluginConfig } from "../../../wasm/v3/wasm_pb";

/**
 * Describes the file envoy/extensions/access_loggers/wasm/v3/wasm.proto.
 */
export declare const file_envoy_extensions_access_loggers_wasm_v3_wasm: GenFile;

/**
 * Custom configuration for an :ref:`AccessLog <envoy_v3_api_msg_config.accesslog.v3.AccessLog>`
 * that calls into a WASM VM. Configures the built-in ``envoy.access_loggers.wasm``
 * AccessLog.
 *
 * @generated from message envoy.extensions.access_loggers.wasm.v3.WasmAccessLog
 */
export declare type WasmAccessLog = Message<"envoy.extensions.access_loggers.wasm.v3.WasmAccessLog"> & {
  /**
   * @generated from field: envoy.extensions.wasm.v3.PluginConfig config = 1;
   */
  config?: PluginConfig;
};

/**
 * Describes the message envoy.extensions.access_loggers.wasm.v3.WasmAccessLog.
 * Use `create(WasmAccessLogSchema)` to create a new message.
 */
export declare const WasmAccessLogSchema: GenMessage<WasmAccessLog>;

