// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/clusters/dynamic_forward_proxy/v3/cluster.proto (package envoy.extensions.clusters.dynamic_forward_proxy.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_envoy_config_cluster_v3_cluster } from "../../../../config/cluster/v3/cluster_pb";
import { file_envoy_config_core_v3_address } from "../../../../config/core/v3/address_pb";
import { file_envoy_extensions_common_dynamic_forward_proxy_v3_dns_cache } from "../../../common/dynamic_forward_proxy/v3/dns_cache_pb";
import { file_google_protobuf_duration, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_udpa_annotations_status } from "../../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../../udpa/annotations/versioning_pb";
import { file_validate_validate } from "../../../../../validate/validate_pb";

/**
 * Describes the file envoy/extensions/clusters/dynamic_forward_proxy/v3/cluster.proto.
 */
export const file_envoy_extensions_clusters_dynamic_forward_proxy_v3_cluster = /*@__PURE__*/
  fileDesc("CkBlbnZveS9leHRlbnNpb25zL2NsdXN0ZXJzL2R5bmFtaWNfZm9yd2FyZF9wcm94eS92My9jbHVzdGVyLnByb3RvEjJlbnZveS5leHRlbnNpb25zLmNsdXN0ZXJzLmR5bmFtaWNfZm9yd2FyZF9wcm94eS52MyKNAwoNQ2x1c3RlckNvbmZpZxJcChBkbnNfY2FjaGVfY29uZmlnGAEgASgLMkAuZW52b3kuZXh0ZW5zaW9ucy5jb21tb24uZHluYW1pY19mb3J3YXJkX3Byb3h5LnYzLkRuc0NhY2hlQ29uZmlnSAASZAoTc3ViX2NsdXN0ZXJzX2NvbmZpZxgEIAEoCzJFLmVudm95LmV4dGVuc2lvbnMuY2x1c3RlcnMuZHluYW1pY19mb3J3YXJkX3Byb3h5LnYzLlN1YkNsdXN0ZXJzQ29uZmlnSAASJgoeYWxsb3dfaW5zZWN1cmVfY2x1c3Rlcl9vcHRpb25zGAIgASgIEiMKG2FsbG93X2NvYWxlc2NlZF9jb25uZWN0aW9ucxgDIAEoCDpHmsWIHkIKQGVudm95LmNvbmZpZy5jbHVzdGVyLmR5bmFtaWNfZm9yd2FyZF9wcm94eS52MmFscGhhLkNsdXN0ZXJDb25maWdCIgogY2x1c3Rlcl9pbXBsZW1lbnRhdGlvbl9zcGVjaWZpZXIinAIKEVN1YkNsdXN0ZXJzQ29uZmlnEkYKCWxiX3BvbGljeRgBIAEoDjIpLmVudm95LmNvbmZpZy5jbHVzdGVyLnYzLkNsdXN0ZXIuTGJQb2xpY3lCCPpCBYIBAhABEj8KEG1heF9zdWJfY2x1c3RlcnMYAiABKAsyHC5nb29nbGUucHJvdG9idWYuVUludDMyVmFsdWVCB/pCBCoCIAASPAoPc3ViX2NsdXN0ZXJfdHRsGAMgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQgj6QgWqAQIqABJAChNwcmVyZXNvbHZlX2NsdXN0ZXJzGAQgAygLMiMuZW52b3kuY29uZmlnLmNvcmUudjMuU29ja2V0QWRkcmVzc0LNAQpAaW8uZW52b3lwcm94eS5lbnZveS5leHRlbnNpb25zLmNsdXN0ZXJzLmR5bmFtaWNfZm9yd2FyZF9wcm94eS52M0IMQ2x1c3RlclByb3RvUAFacWdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2V4dGVuc2lvbnMvY2x1c3RlcnMvZHluYW1pY19mb3J3YXJkX3Byb3h5L3YzO2R5bmFtaWNfZm9yd2FyZF9wcm94eXYzuoDI0QYCEAJiBnByb3RvMw", [file_envoy_config_cluster_v3_cluster, file_envoy_config_core_v3_address, file_envoy_extensions_common_dynamic_forward_proxy_v3_dns_cache, file_google_protobuf_duration, file_google_protobuf_wrappers, file_udpa_annotations_status, file_udpa_annotations_versioning, file_validate_validate]);

/**
 * Describes the message envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig.
 * Use `create(ClusterConfigSchema)` to create a new message.
 */
export const ClusterConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_clusters_dynamic_forward_proxy_v3_cluster, 0);

/**
 * Describes the message envoy.extensions.clusters.dynamic_forward_proxy.v3.SubClustersConfig.
 * Use `create(SubClustersConfigSchema)` to create a new message.
 */
export const SubClustersConfigSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_clusters_dynamic_forward_proxy_v3_cluster, 1);

