// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/geoip_providers/common/v3/common.proto (package envoy.extensions.geoip_providers.common.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/extensions/geoip_providers/common/v3/common.proto.
 */
export declare const file_envoy_extensions_geoip_providers_common_v3_common: GenFile;

/**
 * @generated from message envoy.extensions.geoip_providers.common.v3.CommonGeoipProviderConfig
 */
export declare type CommonGeoipProviderConfig = Message<"envoy.extensions.geoip_providers.common.v3.CommonGeoipProviderConfig"> & {
  /**
   * Configuration for geolocation headers to add to the request.
   *
   * @generated from field: envoy.extensions.geoip_providers.common.v3.CommonGeoipProviderConfig.GeolocationHeadersToAdd geo_headers_to_add = 1;
   */
  geoHeadersToAdd?: CommonGeoipProviderConfig_GeolocationHeadersToAdd;
};

/**
 * Describes the message envoy.extensions.geoip_providers.common.v3.CommonGeoipProviderConfig.
 * Use `create(CommonGeoipProviderConfigSchema)` to create a new message.
 */
export declare const CommonGeoipProviderConfigSchema: GenMessage<CommonGeoipProviderConfig>;

/**
 * The set of geolocation headers to add to the request. If any of the configured headers is present
 * in the incoming request, it will be overridden by the :ref:`GeoIP filter <config_http_filters_geoip>`.
 * [#next-free-field: 13]
 *
 * @generated from message envoy.extensions.geoip_providers.common.v3.CommonGeoipProviderConfig.GeolocationHeadersToAdd
 */
export declare type CommonGeoipProviderConfig_GeolocationHeadersToAdd = Message<"envoy.extensions.geoip_providers.common.v3.CommonGeoipProviderConfig.GeolocationHeadersToAdd"> & {
  /**
   * If set, the header will be used to populate the country ISO code associated with the IP address.
   *
   * @generated from field: string country = 1;
   */
  country: string;

  /**
   * If set, the header will be used to populate the city associated with the IP address.
   *
   * @generated from field: string city = 2;
   */
  city: string;

  /**
   * If set, the header will be used to populate the region ISO code associated with the IP address.
   * The least specific subdivision will be selected as the region value.
   *
   * @generated from field: string region = 3;
   */
  region: string;

  /**
   * If set, the header will be used to populate the ASN associated with the IP address.
   *
   * @generated from field: string asn = 4;
   */
  asn: string;

  /**
   * This field is deprecated; use ``anon`` instead.
   *
   * @generated from field: string is_anon = 5 [deprecated = true];
   * @deprecated
   */
  isAnon: string;

  /**
   * If set, the IP address will be checked if it belongs to any type of anonymization network (e.g., VPN, public proxy).
   * The header will be populated with the check result. Header value will be set to either ``true`` or ``false`` depending on the check result.
   *
   * @generated from field: string anon = 12;
   */
  anon: string;

  /**
   * If set, the IP address will be checked if it belongs to a VPN and the header will be populated with the check result.
   * Header value will be set to either ``true`` or ``false`` depending on the check result.
   *
   * @generated from field: string anon_vpn = 6;
   */
  anonVpn: string;

  /**
   * If set, the IP address will be checked if it belongs to a hosting provider and the header will be populated with the check result.
   * Header value will be set to either ``true`` or ``false`` depending on the check result.
   *
   * @generated from field: string anon_hosting = 7;
   */
  anonHosting: string;

  /**
   * If set, the IP address will be checked if it belongs to a TOR exit node and the header will be populated with the check result.
   * Header value will be set to either ``true`` or ``false`` depending on the check result.
   *
   * @generated from field: string anon_tor = 8;
   */
  anonTor: string;

  /**
   * If set, the IP address will be checked if it belongs to a public proxy and the header will be populated with the check result.
   * Header value will be set to either ``true`` or ``false`` depending on the check result.
   *
   * @generated from field: string anon_proxy = 9;
   */
  anonProxy: string;

  /**
   * If set, the header will be used to populate the ISP associated with the IP address.
   *
   * @generated from field: string isp = 10;
   */
  isp: string;

  /**
   * If set, the IP address will be checked if it belongs to the ISP named iCloud Private Relay and the header will be populated with the check result.
   * Header value will be set to either ``true`` or ``false`` depending on the check result.
   *
   * @generated from field: string apple_private_relay = 11;
   */
  applePrivateRelay: string;
};

/**
 * Describes the message envoy.extensions.geoip_providers.common.v3.CommonGeoipProviderConfig.GeolocationHeadersToAdd.
 * Use `create(CommonGeoipProviderConfig_GeolocationHeadersToAddSchema)` to create a new message.
 */
export declare const CommonGeoipProviderConfig_GeolocationHeadersToAddSchema: GenMessage<CommonGeoipProviderConfig_GeolocationHeadersToAdd>;

