// @generated by protoc-gen-es v2.10.0
// @generated from file bazel/cc_proto_descriptor_library/testdata/test.proto (package testdata.dynamic_descriptors, syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Any } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file bazel/cc_proto_descriptor_library/testdata/test.proto.
 */
export declare const file_bazel_cc_proto_descriptor_library_testdata_test: GenFile;

/**
 * @generated from message testdata.dynamic_descriptors.Foo
 */
export declare type Foo = Message<"testdata.dynamic_descriptors.Foo"> & {
  /**
   * @generated from field: optional string bar = 1;
   */
  bar: string;

  /**
   * @generated from field: optional google.protobuf.Any baz = 2;
   */
  baz?: Any;
};

/**
 * Describes the message testdata.dynamic_descriptors.Foo.
 * Use `create(FooSchema)` to create a new message.
 */
export declare const FooSchema: GenMessage<Foo>;

