// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/listener/original_src/v3/original_src.proto (package envoy.extensions.filters.listener.original_src.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb";
import { file_udpa_annotations_versioning } from "../../../../../../udpa/annotations/versioning_pb";

/**
 * Describes the file envoy/extensions/filters/listener/original_src/v3/original_src.proto.
 */
export const file_envoy_extensions_filters_listener_original_src_v3_original_src = /*@__PURE__*/
  fileDesc("CkRlbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvbGlzdGVuZXIvb3JpZ2luYWxfc3JjL3YzL29yaWdpbmFsX3NyYy5wcm90bxIxZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmxpc3RlbmVyLm9yaWdpbmFsX3NyYy52MyJ1CgtPcmlnaW5hbFNyYxIRCgliaW5kX3BvcnQYASABKAgSDAoEbWFyaxgCIAEoDTpFmsWIHkAKPmVudm95LmNvbmZpZy5maWx0ZXIubGlzdGVuZXIub3JpZ2luYWxfc3JjLnYyYWxwaGExLk9yaWdpbmFsU3JjQsYBCj9pby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5saXN0ZW5lci5vcmlnaW5hbF9zcmMudjNCEE9yaWdpbmFsU3JjUHJvdG9QAVpnZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9maWx0ZXJzL2xpc3RlbmVyL29yaWdpbmFsX3NyYy92MztvcmlnaW5hbF9zcmN2M7qAyNEGAhACYgZwcm90bzM", [file_udpa_annotations_status, file_udpa_annotations_versioning]);

/**
 * Describes the message envoy.extensions.filters.listener.original_src.v3.OriginalSrc.
 * Use `create(OriginalSrcSchema)` to create a new message.
 */
export const OriginalSrcSchema = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_listener_original_src_v3_original_src, 0);

