// @generated by protoc-gen-es v2.10.0
// @generated from file xds/type/matcher/v3/http_inputs.proto (package xds.type.matcher.v3, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file xds/type/matcher/v3/http_inputs.proto.
 */
export const file_xds_type_matcher_v3_http_inputs = /*@__PURE__*/
  fileDesc("CiV4ZHMvdHlwZS9tYXRjaGVyL3YzL2h0dHBfaW5wdXRzLnByb3RvEhN4ZHMudHlwZS5tYXRjaGVyLnYzIh0KG0h0dHBBdHRyaWJ1dGVzQ2VsTWF0Y2hJbnB1dEJfCh5jb20uZ2l0aHViLnhkcy50eXBlLm1hdGNoZXIudjNCD0h0dHBJbnB1dHNQcm90b1ABWipnaXRodWIuY29tL2NuY2YveGRzL2dvL3hkcy90eXBlL21hdGNoZXIvdjNiBnByb3RvMw");

/**
 * Describes the message xds.type.matcher.v3.HttpAttributesCelMatchInput.
 * Use `create(HttpAttributesCelMatchInputSchema)` to create a new message.
 */
export const HttpAttributesCelMatchInputSchema = /*@__PURE__*/
  messageDesc(file_xds_type_matcher_v3_http_inputs, 0);

