// @generated by protoc-gen-es v2.10.0
// @generated from file xds/type/matcher/v3/regex.proto (package xds.type.matcher.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file xds/type/matcher/v3/regex.proto.
 */
export declare const file_xds_type_matcher_v3_regex: GenFile;

/**
 * A regex matcher designed for safety when used with untrusted input.
 *
 * @generated from message xds.type.matcher.v3.RegexMatcher
 */
export declare type RegexMatcher = Message<"xds.type.matcher.v3.RegexMatcher"> & {
  /**
   * @generated from oneof xds.type.matcher.v3.RegexMatcher.engine_type
   */
  engineType: {
    /**
     * Google's RE2 regex engine.
     *
     * @generated from field: xds.type.matcher.v3.RegexMatcher.GoogleRE2 google_re2 = 1;
     */
    value: RegexMatcher_GoogleRE2;
    case: "googleRe2";
  } | { case: undefined; value?: undefined };

  /**
   * The regex match string. The string must be supported by the configured
   * engine.
   *
   * @generated from field: string regex = 2;
   */
  regex: string;
};

/**
 * Describes the message xds.type.matcher.v3.RegexMatcher.
 * Use `create(RegexMatcherSchema)` to create a new message.
 */
export declare const RegexMatcherSchema: GenMessage<RegexMatcher>;

/**
 * Google's `RE2 <https://github.com/google/re2>`_ regex engine. The regex
 * string must adhere to the documented `syntax
 * <https://github.com/google/re2/wiki/Syntax>`_. The engine is designed to
 * complete execution in linear time as well as limit the amount of memory
 * used.
 *
 * Envoy supports program size checking via runtime. The runtime keys
 * `re2.max_program_size.error_level` and `re2.max_program_size.warn_level`
 * can be set to integers as the maximum program size or complexity that a
 * compiled regex can have before an exception is thrown or a warning is
 * logged, respectively. `re2.max_program_size.error_level` defaults to 100,
 * and `re2.max_program_size.warn_level` has no default if unset (will not
 * check/log a warning).
 *
 * Envoy emits two stats for tracking the program size of regexes: the
 * histogram `re2.program_size`, which records the program size, and the
 * counter `re2.exceeded_warn_level`, which is incremented each time the
 * program size exceeds the warn level threshold.
 *
 * @generated from message xds.type.matcher.v3.RegexMatcher.GoogleRE2
 */
export declare type RegexMatcher_GoogleRE2 = Message<"xds.type.matcher.v3.RegexMatcher.GoogleRE2"> & {
};

/**
 * Describes the message xds.type.matcher.v3.RegexMatcher.GoogleRE2.
 * Use `create(RegexMatcher_GoogleRE2Schema)` to create a new message.
 */
export declare const RegexMatcher_GoogleRE2Schema: GenMessage<RegexMatcher_GoogleRE2>;

