// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/grpc_web/v3/grpc_web.proto (package envoy.extensions.filters.http.grpc_web.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/extensions/filters/http/grpc_web/v3/grpc_web.proto.
 */
export declare const file_envoy_extensions_filters_http_grpc_web_v3_grpc_web: GenFile;

/**
 * gRPC Web filter config.
 *
 * @generated from message envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
 */
export declare type GrpcWeb = Message<"envoy.extensions.filters.http.grpc_web.v3.GrpcWeb"> & {
};

/**
 * Describes the message envoy.extensions.filters.http.grpc_web.v3.GrpcWeb.
 * Use `create(GrpcWebSchema)` to create a new message.
 */
export declare const GrpcWebSchema: GenMessage<GrpcWeb>;

