// @generated by protoc-gen-es v2.10.0
// @generated from file envoy/extensions/filters/http/dynamic_modules/v3/dynamic_modules.proto (package envoy.extensions.filters.http.dynamic_modules.v3, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DynamicModuleConfig } from "../../../../dynamic_modules/v3/dynamic_modules_pb";
import type { Any } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file envoy/extensions/filters/http/dynamic_modules/v3/dynamic_modules.proto.
 */
export declare const file_envoy_extensions_filters_http_dynamic_modules_v3_dynamic_modules: GenFile;

/**
 * Configuration of the HTTP filter for dynamic modules. This filter allows loading shared object files
 * that can be loaded via dlopen by the HTTP filter.
 *
 * A module can be loaded by multiple HTTP filters, hence the program can be structured in a way that
 * the module is loaded only once and shared across multiple filters providing multiple functionalities.
 *
 * A dynamic module HTTP filter can opt into being a terminal filter with no upstream by setting ``terminal_filter`` to
 * true in the configuration. A terminal dynamic module can use ``send_`` ABI methods to send response headers,
 * body and trailers to the downstream.
 *
 * @generated from message envoy.extensions.filters.http.dynamic_modules.v3.DynamicModuleFilter
 */
export declare type DynamicModuleFilter = Message<"envoy.extensions.filters.http.dynamic_modules.v3.DynamicModuleFilter"> & {
  /**
   * Specifies the shared-object level configuration.
   *
   * @generated from field: envoy.extensions.dynamic_modules.v3.DynamicModuleConfig dynamic_module_config = 1;
   */
  dynamicModuleConfig?: DynamicModuleConfig;

  /**
   * The name for this filter configuration. This can be used to distinguish between different filter implementations
   * inside a dynamic module. For example, a module can have completely different filter implementations.
   * When Envoy receives this configuration, it passes the filter_name to the dynamic module's HTTP filter config init function
   * together with the filter_config.
   * That way a module can decide which in-module filter implementation to use based on the name at load time.
   *
   * @generated from field: string filter_name = 2;
   */
  filterName: string;

  /**
   * The configuration for the filter chosen by filter_name. This is passed to the module's HTTP filter initialization function.
   * Together with the filter_name, the module can decide which in-module filter implementation to use and
   * fine-tune the behavior of the filter.
   *
   * For example, if a module has two filter implementations, one for logging and one for header manipulation,
   * filter_name is used to choose either logging or header manipulation. The filter_config can be used to
   * configure the logging level or the header manipulation behavior.
   *
   * ``google.protobuf.Struct`` is serialized as JSON before
   * passing it to the plugin. ``google.protobuf.BytesValue`` and
   * ``google.protobuf.StringValue`` are passed directly without the wrapper.
   *
   * .. code-block:: yaml
   *
   *  # Passing in a string
   *  filter_config:
   *    "@type": "type.googleapis.com/google.protobuf.StringValue"
   *    value: hello
   *
   *  # Passing in raw bytes
   *  filter_config:
   *    "@type": "type.googleapis.com/google.protobuf.BytesValue"
   *    value: aGVsbG8= # echo -n "hello" | base64
   *
   *
   * @generated from field: google.protobuf.Any filter_config = 3;
   */
  filterConfig?: Any;

  /**
   * Set true if the dynamic module is a terminal filter to use without an upstream.
   * The dynamic module is responsible for creating and sending the response to downstream.
   *
   * @generated from field: bool terminal_filter = 4;
   */
  terminalFilter: boolean;
};

/**
 * Describes the message envoy.extensions.filters.http.dynamic_modules.v3.DynamicModuleFilter.
 * Use `create(DynamicModuleFilterSchema)` to create a new message.
 */
export declare const DynamicModuleFilterSchema: GenMessage<DynamicModuleFilter>;

/**
 * Configuration of the HTTP per-route filter for dynamic modules. This filter allows loading shared object files
 * that can be loaded via dlopen by the HTTP filter.
 *
 * @generated from message envoy.extensions.filters.http.dynamic_modules.v3.DynamicModuleFilterPerRoute
 */
export declare type DynamicModuleFilterPerRoute = Message<"envoy.extensions.filters.http.dynamic_modules.v3.DynamicModuleFilterPerRoute"> & {
  /**
   * Specifies the shared-object level configuration.
   *
   * @generated from field: envoy.extensions.dynamic_modules.v3.DynamicModuleConfig dynamic_module_config = 1;
   */
  dynamicModuleConfig?: DynamicModuleConfig;

  /**
   * The name for this filter configuration. This can be used to distinguish between different filter implementations
   * inside a dynamic module. For example, a module can have completely different filter implementations.
   * When Envoy receives this configuration, it passes the filter_name to the dynamic module's HTTP per-route filter config init function
   * together with the filter_config.
   * That way a module can decide which in-module filter implementation to use based on the name at load time.
   *
   * @generated from field: string per_route_config_name = 2;
   */
  perRouteConfigName: string;

  /**
   * The configuration for the filter chosen by filter_name. This is passed to the module's HTTP per-route filter initialization function.
   * Together with the filter_name, the module can decide which in-module filter implementation to use and
   * fine-tune the behavior of the filter on a specific route.
   *
   * For example, if a module has two filter implementations, one for logging and one for header manipulation,
   * filter_name is used to choose either logging or header manipulation. The filter_config can be used to
   * configure the logging level or the header manipulation behavior.
   *
   * ``google.protobuf.Struct`` is serialized as JSON before
   * passing it to the plugin. ``google.protobuf.BytesValue`` and
   * ``google.protobuf.StringValue`` are passed directly without the wrapper.
   *
   * .. code-block:: yaml
   *
   *  # Passing in a string
   *  filter_config:
   *    "@type": "type.googleapis.com/google.protobuf.StringValue"
   *    value: hello
   *
   *  # Passing in raw bytes
   *  filter_config:
   *    "@type": "type.googleapis.com/google.protobuf.BytesValue"
   *    value: aGVsbG8= # echo -n "hello" | base64
   *
   *
   * @generated from field: google.protobuf.Any filter_config = 3;
   */
  filterConfig?: Any;
};

/**
 * Describes the message envoy.extensions.filters.http.dynamic_modules.v3.DynamicModuleFilterPerRoute.
 * Use `create(DynamicModuleFilterPerRouteSchema)` to create a new message.
 */
export declare const DynamicModuleFilterPerRouteSchema: GenMessage<DynamicModuleFilterPerRoute>;

