// @generated by protoc-gen-es v2.10.0
// @generated from file contrib/envoy/extensions/vcl/v3alpha/vcl_socket_interface.proto (package envoy.extensions.vcl.v3alpha, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../udpa/annotations/status_pb";

/**
 * Describes the file contrib/envoy/extensions/vcl/v3alpha/vcl_socket_interface.proto.
 */
export const file_contrib_envoy_extensions_vcl_v3alpha_vcl_socket_interface = /*@__PURE__*/
  fileDesc("Cj9jb250cmliL2Vudm95L2V4dGVuc2lvbnMvdmNsL3YzYWxwaGEvdmNsX3NvY2tldF9pbnRlcmZhY2UucHJvdG8SHGVudm95LmV4dGVuc2lvbnMudmNsLnYzYWxwaGEiFAoSVmNsU29ja2V0SW50ZXJmYWNlQp4BCippby5lbnZveXByb3h5LmVudm95LmV4dGVuc2lvbnMudmNsLnYzYWxwaGFCF1ZjbFNvY2tldEludGVyZmFjZVByb3RvUAFaS2dpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2NvbnRyaWIvZW52b3kvZXh0ZW5zaW9ucy92Y2wvdjNhbHBoYbqAyNEGBAgBEAJiBnByb3RvMw", [file_udpa_annotations_status]);

/**
 * Describes the message envoy.extensions.vcl.v3alpha.VclSocketInterface.
 * Use `create(VclSocketInterfaceSchema)` to create a new message.
 */
export const VclSocketInterfaceSchema = /*@__PURE__*/
  messageDesc(file_contrib_envoy_extensions_vcl_v3alpha_vcl_socket_interface, 0);

